{{-- نص المقال بالعربية لصفحة /features/ai-agent.
     البنية مطابقة للنسخة الإنجليزية: النص وحده يتغيّر، حتى تبقى معرّفات
     الأقسام في config/seo_pages.php صالحة. --}}
<section id="what"><h2>ما الذي يفعله وكيل الذكاء الاصطناعي فعلًا</h2>
<p>نادرًا ما يتكوّن حجم الدعم من أسئلة صعبة. بل يتكوّن من الأسئلة الأربعين نفسها بصياغات مختلفة: أين طلبي، هل تسلّمون أيام الأحد، هل أستطيع تغيير عنواني، ما ساعات عملكم، كيف أُرجع منتجًا.</p>
<p>يقرأ وكيل الذكاء الاصطناعي الرسالة الواردة، ويطابقها مع المعرفة التي منحتها له، ثم ينتج إجابة بصياغتك أنت. وبحسب الوضع الذي تختاره، يسلّم المسوّدة إلى موظف أو يرسلها مباشرة. وكل ما يفعله يصل إلى صندوق الوارد المشترك نفسه مع الردود البشرية، موسومًا لتتمكّن دائمًا من التمييز بينهما.</p>
<div class="note"><svg width="17" height="17" viewBox="0 0 24 24" fill="none"><circle cx="12" cy="12" r="9" stroke="#0f7e7a" stroke-width="2"/><path d="M12 11v5" stroke="#0f7e7a" stroke-width="2" stroke-linecap="round"/><circle cx="12" cy="7.8" r="1.1" fill="#0f7e7a"/></svg><div class="m"><div class="h">مبنيّ على مصدر، لا تخمين توليدي</div><p>يجيب الوكيل من قاعدة معرفتك. وإن لم تكن الإجابة موجودة فيها فهو لا يخترعها — بل يصعّد. انظر <a href="/features/knowledge-base">قاعدة المعرفة</a> لمعرفة كيفية تغذيتها.</p></div></div>
</section>
<section id="modes"><h2>ثلاثة أوضاع ومتى تستخدم كلًّا منها</h2>
<p>أكثر المخاوف شيوعًا من الدعم بالذكاء الاصطناعي هو فقدان السيطرة على ما يُقال للعملاء. ويجيب wavadesk عن ذلك بأوضاع لا بوعود: أنت تختار قدر الاستقلالية الممنوح للوكيل، ويمكنك تغييره في أي وقت.</p>
<div class="cards"><div class="fc"><div class="ic"><svg width="19" height="19" viewBox="0 0 24 24" fill="none"><path d="M4 4h16v12l-4 4H4z" stroke="#0f7e7a" stroke-width="2" stroke-linejoin="round"/><path d="M8 9h8M8 13h5" stroke="#0f7e7a" stroke-width="2" stroke-linecap="round"/></svg></div><div class="h">الاقتراح</div><p>يصوغ الذكاء الاصطناعي، ويقرأ موظفك المسوّدة ويعدّلها إن لزم ثم يرسل. لا يصل شيء إلى العميل دون أن يضغط إنسان على الإرسال. ابدأ من هنا.</p></div><div class="fc"><div class="ic"><svg width="19" height="19" viewBox="0 0 24 24" fill="none"><path d="M4 13h6l-1 8 9-12h-6l1-8z" stroke="#0f7e7a" stroke-width="2" stroke-linejoin="round"/></svg></div><div class="h">المستقل</div><p>يردّ الذكاء الاصطناعي مباشرة دون انتظار موظف. وهو الأنسب بعد أن تثق بإجاباته في مجموعة محدّدة من المواضيع.</p></div><div class="fc"><div class="ic"><svg width="19" height="19" viewBox="0 0 24 24" fill="none"><path d="M12 3v6M12 15v6M3 12h6M15 12h6" stroke="#0f7e7a" stroke-width="2" stroke-linecap="round"/><circle cx="12" cy="12" r="2.6" stroke="#0f7e7a" stroke-width="2"/></svg></div><div class="h">الهجين</div><p>مستقل في الأسئلة التي اعتمدتها، واقتراح فقط في ما عداها. وهنا تستقرّ معظم الفرق.</p></div><div class="fc"><div class="ic"><svg width="19" height="19" viewBox="0 0 24 24" fill="none"><path d="M12 2l8 4v6c0 5-3.4 8.8-8 10-4.6-1.2-8-5-8-10V6l8-4z" stroke="#0f7e7a" stroke-width="2" stroke-linejoin="round"/></svg></div><div class="h">معطّل</div><p>لا تدخّل للذكاء الاصطناعي إطلاقًا. وتظل قاعدة المعرفة تغذّي الردود المحفوظة للموظفين.</p></div></div>
<h3>تدرّج معقول</h3>
<ol class="numbered"><li><span>شغّل وضع الاقتراح أسبوعًا وراقب ما يصوغه. ستكتشف بسرعة الثغرات في أسئلتك الشائعة.</span></li><li><span>عالج تلك الثغرات. فتتحسّن المسوّدات فورًا لأن المصدر تحسّن.</span></li><li><span>حوّل الأسئلة التي يجيب عنها بدقة باستمرار إلى الوضع المستقل، واترك الباقي على الاقتراح.</span></li><li><span>راجع أرقام تخفيف الحِمل شهريًا ووسّع نطاق الوضع المستقل كلما زادت الثقة.</span></li></ol>
<div class="note amber"><svg width="17" height="17" viewBox="0 0 24 24" fill="none"><path d="M12 8v5" stroke="#92400e" stroke-width="2.2" stroke-linecap="round"/><circle cx="12" cy="16.5" r="1.2" fill="#92400e"/><circle cx="12" cy="12" r="9" stroke="#92400e" stroke-width="2"/></svg><div class="m"><div class="h">لا تبدأ بالوضع المستقل</div><p>وضع الاقتراح ليس نسخة تجريبية — بل هو الطريقة التي تكتشف بها ما ينقص قاعدة معرفتك، دون أن يكون العميل هو من يكتشفه.</p></div></div>
</section>
<section id="grounding"><h2>كيف يحافظ على دقّته</h2>
<p>لا يساوي وكيل الدعم الذكي أكثر ممّا يُسمح له بقوله. وآليتان تُبقيان وكيل wavadesk داخل الحدود.</p>
<h3>لا يجيب إلا من قاعدة معرفتك</h3>
<p>مرجع الوكيل هو المعرفة التي ترفعها: أسئلتك الشائعة وسياساتك وشروط التوصيل وساعات العمل وقواعد الإرجاع. وهو لا يجيب من معرفة عامة عن العالم، ما يعني أنه لا يستطيع أن يخترع بثقة سياسة استرداد لا تملكها.</p>
<h3>يصعّد حين لا يعرف</h3>
<p>حين تقع الرسالة خارج ما تغطّيه معرفتك، أو تطابق كلمة تصعيد، يتوقّف الوكيل ويسلّم المحادثة إلى إنسان بدل إنتاج شيء يبدو معقولًا. وعدم الإجابة يُعدّ هنا النتيجة الصحيحة لا الإخفاق.</p>
<ul><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>إجابات مستمدّة من أسئلتك الشائعة وسياساتك المرفوعة</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>ردود بنبرتك أنت، لأن نصّك المصدر هو ما يحدّدها</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>لا إجابة مخترعة عند غياب المعرفة</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>كلمات التصعيد تفرض تسليمًا فوريًا</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>كل ردّ آلي مسجَّل ومنسوب في سجلّ التدقيق</span></li></ul>
</section>
<section id="escalation"><h2>التصعيد والتسليم</h2>
<p>اللحظة التي يتوقّف عندها الذكاء الاصطناعي أهم من اللحظة التي يبدأ فيها. فنزاع استرداد أو شكوى أو تهديد قانوني أو عميل متضايق ينبغي أن يصل إلى شخص فورًا، وألا يبقى يدور في حلقة مع روبوت.</p>
<p>أنت تحدّد كلمات التصعيد — كلمات وعبارات تعني أن وجود إنسان ضروري. وحين تظهر إحداها ينسحب الذكاء الاصطناعي من المحادثة، وتنتقل المحادثة إلى طابور الفريق المناسب، ويستلمها موظف كالمعتاد. ولا يُخبَر العميل بأنه حُوِّل؛ بل تستمر المحادثة ببساطة.</p>
<h3>مُحفّزات التصعيد المعتادة</h3>
<ul><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>لغة الشكوى والنزاع: استرداد، ردّ مبلغ، شكوى، محامٍ</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>إشارات الانفعال: رسائل متتابعة بسرعة، أحرف كبيرة، ألفاظ نابية</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>حسابات مهمة محدّدة تريد دائمًا أن يتولّاها شخص</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>مواضيع استثنيتها عمدًا من الأتمتة</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>أي سؤال لا تعيد فيه قاعدة المعرفة إجابة موثوقة</span></li></ul>
<div class="note"><svg width="17" height="17" viewBox="0 0 24 24" fill="none"><circle cx="12" cy="12" r="9" stroke="#0f7e7a" stroke-width="2"/><path d="M12 11v5" stroke="#0f7e7a" stroke-width="2" stroke-linecap="round"/><circle cx="12" cy="7.8" r="1.1" fill="#0f7e7a"/></svg><div class="m"><div class="h">التصعيد فوري لا ينتظر خلف الروبوت</div><p>لا يحاول الذكاء الاصطناعي إجابة إضافية قبل التسليم. فحين ينطلق مُحفّز، يتوقّف.</p></div></div>
</section>
<section id="measure"><h2>قياس ما إذا كان ينجح</h2>
<p>الرقم المهم ليس عدد الرسائل التي أرسلها الذكاء الاصطناعي، بل عدد المحادثات التي أغلقها دون إنسان، وهل كانت التي صعّدها هي الصحيحة.</p>
<figure><div class="shot"><img src="/img/features/ai-performance.png" alt="لوحة أداء الذكاء الاصطناعي تعرض نسبة تخفيف الحِمل ووسيط زمن الردّ وعدد التصعيدات في شريط مكدّس" loading="lazy" decoding="async" width="2552" height="438"></div><figcaption><svg width="13" height="13" viewBox="0 0 24 24" fill="none"><rect x="2.5" y="6" width="19" height="14" rx="2.5" stroke="currentColor" stroke-width="2"/><circle cx="12" cy="13" r="3.4" stroke="currentColor" stroke-width="2"/><path d="M8.5 6l1.2-2h4.6L15.5 6" stroke="currentColor" stroke-width="2" stroke-linejoin="round"/></svg><span>أداء الذكاء الاصطناعي في لوحة التحكّم: محلولة دون موظف، ومدعومة بالذكاء الاصطناعي، ومُصعَّدة — كنِسَب لا كعدد رسائل خام.</span></figcaption></figure>
<p>ثلاثة أرقام تخبرك بكل شيء تقريبًا. نسبة تخفيف الحِمل هي حصّة المحادثات التي حلّها الذكاء الاصطناعي من أولها إلى آخرها. ووسيط زمن ردّه يُظهر أفضلية السرعة على طابور بشري. وعدد التصعيدات هو صمام الأمان — فإن هبط إلى صفر فالوكيل غالبًا يجيب عن أمور كان ينبغي أن يسلّمها.</p>
<div class="stats"><div class="sc"><b>68٪</b><span>حُلّت دون موظف في مساحة العمل المرجعية</span></div><div class="sc"><b>2.4 ثانية</b><span>وسيط زمن ردّ الذكاء الاصطناعي</span></div><div class="sc"><b>31</b><span>صُعِّدت إلى إنسان عن قصد</span></div></div>
<p>التقارير الكاملة مشروحة في <a href="/features/reports-analytics">تقارير الدعم والتحليلات</a>.</p>
</section>
<section id="cost"><h2>كيف تُسعَّر استخدامات الذكاء الاصطناعي</h2>
<p>تُحتسَب ردود الذكاء الاصطناعي كرسائل ذكاء اصطناعي. وتشمل كل باقة حصّة شهرية، ويمكنك إضافة باقات رسائل دون تغيير الباقة إذا طال شهر مزدحم.</p>
<div class="tw"><table><thead><tr><th>الباقة</th><th>رسائل الذكاء الاصطناعي المشمولة</th><th>إن احتجت المزيد</th></tr></thead><tbody><tr><td>Starter</td><td>1000 شهريًا</td><td>أضف باقات من 2500 رسالة</td></tr><tr><td>Growth</td><td>5000 شهريًا</td><td>أضف باقات من 2500 رسالة</td></tr><tr><td>Scale</td><td>غير محدودة</td><td>بلا سقف، ولا حاجة إلى باقات</td></tr></tbody></table></div>
<figure><div class="shot"><img src="/img/features/usage-meters.png" alt="مؤشرات الاستهلاك تعرض رسائل الذكاء الاصطناعي المستهلكة مقابل الحصّة الشهرية" loading="lazy" decoding="async" width="1760" height="322"></div><figcaption><svg width="13" height="13" viewBox="0 0 24 24" fill="none"><rect x="2.5" y="6" width="19" height="14" rx="2.5" stroke="currentColor" stroke-width="2"/><circle cx="12" cy="13" r="3.4" stroke="currentColor" stroke-width="2"/><path d="M8.5 6l1.2-2h4.6L15.5 6" stroke="currentColor" stroke-width="2" stroke-linejoin="round"/></svg><span>الاستهلاك ظاهر في الفوترة قبل بلوغ السقف، مع إمكانية إضافة باقة في منتصف الدورة.</span></figcaption></figure>
<p>أما محادثات واتساب نفسها فغير محدودة دائمًا في كل الباقات — بلا رسوم لكل رسالة وبلا رسوم محادثة من Meta. ولا يُحتسَب سوى ردود الذكاء الاصطناعي.</p>
</section>
