{{-- نص المقال بالعربية لصفحة /features/api-integrations.
     البنية مطابقة للنسخة الإنجليزية: النص وحده يتغيّر، حتى تبقى معرّفات
     الأقسام في config/seo_pages.php صالحة. --}}
<section id="why"><h2>ما الغرض من التكامل</h2>
<p>تتضاعف قيمة أداة الدعم حين تعرف ما تعرفه شركتك أصلًا. فالموظف الذي يجيب عن «أين طلبي» لا ينبغي أن يبحث عن رقم الطلب في نظام ثانٍ — بل ينبغي أن تكون تلك المعلومة أمامه على الشاشة.</p>
<p>والتكامل يسير في الاتجاهين. فأنت تدفع السياق إلى الداخل ليستخدمه الموظفون والذكاء الاصطناعي. وتسحب الأحداث إلى الخارج لتتفاعل أنظمتك حين يقع شيء في الدعم.</p>
<div class="cards"><div class="fc"><div class="ic"><svg width="19" height="19" viewBox="0 0 24 24" fill="none"><path d="M8 6l-5 6 5 6M16 6l5 6-5 6" stroke="#0f7e7a" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/></svg></div><div class="h">واجهة REST</div><p>اقرأ واكتب المحادثات وجهات الاتصال والوسوم والرسائل من نظامك الخلفي.</p></div><div class="fc"><div class="ic"><svg width="19" height="19" viewBox="0 0 24 24" fill="none"><path d="M4 13h6l-1 8 9-12h-6l1-8z" stroke="#0f7e7a" stroke-width="2" stroke-linejoin="round"/></svg></div><div class="h">Webhooks</div><p>استقبل حدثًا عند إنشاء محادثة أو استلامها أو الردّ عليها أو حلّها أو تصعيدها.</p></div><div class="fc"><div class="ic"><svg width="19" height="19" viewBox="0 0 24 24" fill="none"><circle cx="8" cy="12" r="4.2" stroke="#0f7e7a" stroke-width="2"/><path d="M12 12h9M17 12v4" stroke="#0f7e7a" stroke-width="2" stroke-linecap="round"/></svg></div><div class="h">واجهة رموز التحقّق</div><p>أرسل رموز مرور لمرة واحدة عبر واتساب وتحقّق منها من تطبيقك.</p></div><div class="fc"><div class="ic"><svg width="19" height="19" viewBox="0 0 24 24" fill="none"><path d="M4 20V10M10 20V4M16 20v-7M22 20H2" stroke="#0f7e7a" stroke-width="2" stroke-linecap="round"/></svg></div><div class="h">تصدير التقارير</div><p>اسحب المؤشرات التي تقف خلف لوحة التحكّم إلى أدوات التحليل أو مستودع البيانات لديك.</p></div></div>
</section>
<section id="auth"><h2>المصادقة</h2>
<p>يستخدم الوصول إلى الواجهة رمز وصول محصورًا بمساحة عمل، يُنشَأ من الإعدادات ويمكن إلغاؤه في أي وقت. والرموز محصورة بمساحة عمل واحدة، فلا يستطيع رمز من عميل قراءة بيانات عميل آخر.</p>
<p>تُرسَل الطلبات عبر HTTPS إلى نقطة مساحة عملك، مع الرمز في ترويسة Authorization. ولا توجد خطوة توقيع منفصلة لاستدعاءات REST؛ أما تسليمات Webhooks فموقّعة لتتمكّن من التأكّد أنها منّا.</p>
<ul><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>رمز وصول لكل مساحة عمل، يُنشَأ ويُلغى من الإعدادات</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>محصور بحيث لا يستطيع الرمز القراءة خارج مساحة عمله</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>حمولات Webhooks موقّعة بسرّ مشترك للتحقّق</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>حدّ للمعدّل لكل رمز، مع إعادة الحدود في ترويسات الاستجابة</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>كل إجراء عبر الواجهة مسجَّل في سجلّ التدقيق نفسه مع الإجراءات البشرية</span></li></ul>
<div class="note amber"><svg width="17" height="17" viewBox="0 0 24 24" fill="none"><path d="M12 8v5" stroke="#92400e" stroke-width="2.2" stroke-linecap="round"/><circle cx="12" cy="16.5" r="1.2" fill="#92400e"/><circle cx="12" cy="12" r="9" stroke="#92400e" stroke-width="2"/></svg><div class="m"><div class="h">تعامل مع الرموز كبيانات اعتماد</div><p>رمز مساحة العمل يستطيع قراءة سجلّ محادثاتك. أبقِه على الخادم — لا في كود الواجهة الأمامية ولا داخل تطبيق جوال.</p></div></div>
</section>
<section id="rest"><h2>ما تغطّيه واجهة REST</h2>
<p>الواجهة منظّمة حول الكائنات نفسها التي في الواجهة الرسومية، فما تراه تستطيع غالبًا قراءته والكتابة فيه.</p>
<div class="tw"><table><thead><tr><th>المورد</th><th>ما يمكنك فعله</th></tr></thead><tbody><tr><td>المحادثات</td><td>السرد، والتصفية حسب القناة أو الحالة، وقراءة الرسائل، والإنشاء، والاستلام، والإسناد، والحل</td></tr><tr><td>الرسائل</td><td>الإرسال داخل محادثة، وقراءة السجلّ، وإرفاق ملاحظات داخلية</td></tr><tr><td>جهات الاتصال</td><td>الإنشاء والتحديث والبحث بالهاتف أو البريد والدمج وإرفاق حقول مخصّصة</td></tr><tr><td>الوسوم</td><td>الإضافة والإزالة، والسرد حسب المحادثة أو جهة الاتصال</td></tr><tr><td>الفرق والموظفون</td><td>السرد، وقراءة التوفّر، وقراءة الإسناد</td></tr><tr><td>التقارير</td><td>سحب المؤشرات التي خلف لوحة التحكّم لفترة محدّدة</td></tr><tr><td>رموز التحقّق</td><td>إرسال رمز والتحقّق منه</td></tr></tbody></table></div>
<h3>أشيع تكامل أول</h3>
<p>دفع سياق العميل إلى بطاقة جهة الاتصال. فإن كان نظامك يعرف سجلّ طلبات العميل أو باقته أو حالة حسابه، فكتابة ذلك كحقول مخصّصة على جهة الاتصال تجعل الموظف يراه في لوحة السياق دون مغادرة المحادثة.</p>
</section>
<section id="webhooks"><h2>Webhooks والأحداث</h2>
<p>تتيح Webhooks لأنظمتك التفاعل مع نشاط الدعم بدل استجوابه باستمرار. فتسجّل نقطة نهاية، وتختار الأحداث التي تهمّك، ونرسل حمولة موقّعة بطلب POST عند وقوعها.</p>
<h3>الأحداث التي يمكنك الاشتراك فيها</h3>
<ul><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>conversation.created — وصلت محادثة جديدة على إحدى القنوات</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>conversation.claimed — استلمها موظف</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>conversation.resolved — وُسمت بأنها محلولة، مع اسم من حلّها</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>conversation.escalated — سلّمها الذكاء الاصطناعي، مع المُحفّز</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>message.received — رسالة واردة من عميل</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>message.sent — ردّ صادر، بشري أو من الذكاء الاصطناعي</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>contact.created و contact.updated</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>otp.verified — جرى التحقّق من رمز بنجاح</span></li></ul>
<h3>استخدامات عملية</h3>
<p>ثلاثة تكاملات تغطّي معظم ما تبنيه الفرق. إنشاء نشاط في نظام إدارة العملاء عند <code>conversation.resolved</code>، ليظهر سجلّ الدعم على الحساب. وتنبيه قناة Slack عند <code>conversation.escalated</code> للحسابات المحدّدة. وفتح ميزة في منتجك عند <code>otp.verified</code>.</p>
<div class="note"><svg width="17" height="17" viewBox="0 0 24 24" fill="none"><circle cx="12" cy="12" r="9" stroke="#0f7e7a" stroke-width="2"/><path d="M12 11v5" stroke="#0f7e7a" stroke-width="2" stroke-linecap="round"/><circle cx="12" cy="7.8" r="1.1" fill="#0f7e7a"/></svg><div class="m"><div class="h">يُعاد إرسال التسليمات</div><p>يُعاد إرسال أي Webhook يفشل بتأخير متزايد. فاستجب سريعًا برمز 2xx ونفّذ العمل بشكل غير متزامن — إذ إن المعالجة الطويلة داخل الطلب ستتجاوز المهلة وتسبّب تسليمات مكرّرة.</p></div></div>
</section>
<section id="otp"><h2>نقاط رموز التحقّق</h2>
<p>استدعاءان، وبلا حالة تحفظها لديك. فالرمز يُولَّد ويُجزَّأ ويُخزَّن عندنا ولا يُعاد إليك أبدًا.</p>
<div class="steps"><div class="step"><span class="n">1</span><div class="m"><div class="h">POST للإرسال</div><p>مع رقم الهاتف ووسم غرض اختياري مثل تسجيل الدخول أو إنشاء حساب. ويعيد معرّف الطلب لا الرمز.</p></div></div><div class="step"><span class="n">2</span><div class="m"><div class="h">يستلمه العميل على واتساب</div><p>من رقم عملك المتصل.</p></div></div><div class="step"><span class="n">3</span><div class="m"><div class="h">POST للتحقّق</div><p>مع الرقم والرمز الذي أدخله العميل. ويعيد نجاحًا أو فشلًا.</p></div></div><div class="step"><span class="n">4</span><div class="m"><div class="h">عالج سبب الفشل</div><p>تعود حالات الفشل مميَّزة: خطأ، أو انتهاء صلاحية، أو تجاوز حدّ المحاولات — لتعرض الرسالة المناسبة.</p></div></div></div>
<p>الانتهاء وحدود المحاولات وحدّ المعدّل لكل رقم كلها مطبَّقة على الخادم. التفاصيل الكاملة في <a href="/features/otp-service">رموز التحقّق عبر واتساب</a>.</p>
</section>
<section id="widget"><h2>التضمين والأداة</h2>
<p>أداة الدردشة المباشرة هي نفسها نقطة تكامل. فإلى جانب مقتطف التثبيت، يمكنك تعريف الزائر من تطبيقك لتُربَط المحادثة بجهة اتصال معروفة بدل جلسة مجهولة.</p>
<p>واستدعاء دالة التعريف ببيانات المستخدم عند تحميل الصفحة يجعل الموظف يرى عميلًا معروفًا بسجلّه الكامل عبر القنوات بدل زائر مجهول.</p>
<figure><div class="shot"><img src="/img/features/livechat-settings.png" alt="شاشة إعدادات الدردشة المباشرة مع مقتطف التثبيت وخيارات الضبط" loading="lazy" decoding="async" width="3186" height="1766"></div><figcaption><svg width="13" height="13" viewBox="0 0 24 24" fill="none"><rect x="2.5" y="6" width="19" height="14" rx="2.5" stroke="currentColor" stroke-width="2"/><circle cx="12" cy="13" r="3.4" stroke="currentColor" stroke-width="2"/><path d="M8.5 6l1.2-2h4.6L15.5 6" stroke="currentColor" stroke-width="2" stroke-linejoin="round"/></svg><span>مقتطف التثبيت وضبط الأداة موجودان في شاشة الإعدادات نفسها، إلى جانب معاينة مباشرة.</span></figcaption></figure>
<p>انظر <a href="/features/live-chat-widget">أداة الدردشة المباشرة</a> للتثبيت والهوية البصرية.</p>
</section>
<section id="limits"><h2>الحدود والإصدارات</h2>
<p>أمران تريد معرفتهما قبل البناء على أي واجهة برمجية: إلى أي حدّ تستطيع الضغط عليها، وهل ستتغيّر من تحتك.</p>
<ul><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>حدود معدّل لكل رمز، مع إعادة الحصّة المتبقّية في ترويسات الاستجابة</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>استجابات 429 تتضمّن قيمة retry-after</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>التغييرات الكاسرة تُطرَح خلف إصدار، وتبقى الإصدارات القائمة مدعومة</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>الإضافات — حقول جديدة وأنواع أحداث جديدة — قد تصل دون تغيير الإصدار، فحلّل الحمولات بأسلوب دفاعي</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>حمولات Webhooks تُصدَّر مع الواجهة نفسها</span></li></ul>
<p>الوصول إلى الواجهة البرمجية مشمول في باقة Scale. اطّلع على <a href="{{ url('/#pricing') }}">الأسعار</a>.</p>
</section>
