{{-- نص المقال بالعربية لصفحة /features/live-chat-widget.
     البنية مطابقة للنسخة الإنجليزية: النص وحده يتغيّر، حتى تبقى معرّفات
     الأقسام في config/seo_pages.php صالحة. --}}
<section id="why"><h2>لماذا صندوق وارد واحد للقناتين</h2>
<p>إضافة دردشة مباشرة إلى موقع أمر سهل. أما الصعب فهو إضافتها دون تفتيت عملية الدعم لديك. والنتيجة المعتادة أداتان وطابوران وسجلّان، وموظفون يتنقّلون بينهما، ولا أحد يستطيع إعداد تقرير عن الصورة كاملة.</p>
<p>يتعامل wavadesk مع القناة بوصفها خاصية للمحادثة لا منتجًا منفصلًا. فدردشة الموقع ومحادثة واتساب تظهران في القائمة نفسها، وتُستلمان بالطريقة نفسها، ويُردّ عليهما من محرّر الكتابة نفسه. والفارق الوحيد شارة تُعلم الموظف بمصدر المحادثة.</p>
<figure><div class="shot"><img src="/img/features/inbox-full.png" alt="صندوق وارد مشترك يعرض محادثات واتساب والدردشة المباشرة في قائمة واحدة مع شارات القنوات" loading="lazy" decoding="async" width="3186" height="1766"></div><figcaption><svg width="13" height="13" viewBox="0 0 24 24" fill="none"><rect x="2.5" y="6" width="19" height="14" rx="2.5" stroke="currentColor" stroke-width="2"/><circle cx="12" cy="13" r="3.4" stroke="currentColor" stroke-width="2"/><path d="M8.5 6l1.2-2h4.6L15.5 6" stroke="currentColor" stroke-width="2" stroke-linejoin="round"/></svg><span>محادثات واتساب والموقع في طابور واحد. والشارة على كل صورة هي الشيء الوحيد الذي يميّزها.</span></figcaption></figure>
<div class="cards"><div class="fc"><div class="ic"><svg width="19" height="19" viewBox="0 0 24 24" fill="none"><path d="M21 11.5a8.4 8.4 0 01-9 8.4 8.9 8.9 0 01-3.9-.9L3 20.5l1.5-4.6A8.4 8.4 0 013.6 11.5a8.4 8.4 0 018.4-8.4 8.4 8.4 0 019 8.4z" stroke="#0f7e7a" stroke-width="2" stroke-linejoin="round"/></svg></div><div class="h">طابور واحد</div><p>صفِّ حسب القناة متى شئت، لكن لا شيء مخبّأ في أداة ثانية.</p></div><div class="fc"><div class="ic"><svg width="19" height="19" viewBox="0 0 24 24" fill="none"><path d="M16 20v-2a4 4 0 00-4-4H6a4 4 0 00-4 4v2" stroke="#0f7e7a" stroke-width="2" stroke-linecap="round"/><circle cx="9" cy="7" r="3.4" stroke="#0f7e7a" stroke-width="2"/><path d="M22 20v-2a4 4 0 00-3-3.9" stroke="#0f7e7a" stroke-width="2" stroke-linecap="round"/></svg></div><div class="h">عميل واحد</div><p>الزائر الذي يراسلك لاحقًا على واتساب يحتفظ بالسجلّ نفسه، ولا يبدأ من الصفر.</p></div><div class="fc"><div class="ic"><svg width="19" height="19" viewBox="0 0 24 24" fill="none"><path d="M13 2 4 14h6l-1 8 9-12h-6l1-8z" fill="#0f7e7a"/></svg></div><div class="h">وكيل ذكاء اصطناعي واحد</div><p>قاعدة المعرفة نفسها تجيب على القناتين، فلا يمكن أن تتباعد الإجابات.</p></div><div class="fc"><div class="ic"><svg width="19" height="19" viewBox="0 0 24 24" fill="none"><path d="M4 20V10M10 20V4M16 20v-7M22 20H2" stroke="#0f7e7a" stroke-width="2" stroke-linecap="round"/></svg></div><div class="h">مجموعة أرقام واحدة</div><p>زمن الاستجابة والحجم يُقاسان عبر القنوات مجتمعةً ولكل قناة على حدة.</p></div></div>
</section>
<section id="install"><h2>تثبيت الأداة</h2>
<p>التثبيت وسم script واحد قبل وسم إغلاق body في موقعك. لا خطوة بناء ولا اشتراط إطار عمل — فهو يعمل على موقع ثابت أو WordPress أو Shopify أو تطبيق Laravel أو أي شيء آخر يقدّم HTML.</p>
<div class="steps"><div class="step"><span class="n">1</span><div class="m"><div class="h">انسخ المقتطف</div><p>تُنشئ مساحة عملك مقتطفًا يحتوي مفتاح الأداة الخاص بك.</p></div></div><div class="step"><span class="n">2</span><div class="m"><div class="h">الصقه في موقعك</div><p>قبل وسم إغلاق body، في كل صفحة تريد إتاحة الدردشة فيها. وتضيفه معظم الفرق إلى قالب مشترك أو إلى التذييل.</p></div></div><div class="step"><span class="n">3</span><div class="m"><div class="h">تأكّد من الاتصال</div><p>افتح موقعك وأرسل رسالة تجريبية وراقب ظهورها في الصندوق المشترك.</p></div></div><div class="step"><span class="n">4</span><div class="m"><div class="h">اضبط السلوك</div><p>اختر رسالة الترحيب والموضع وساعات العمل وهل يجيب الذكاء الاصطناعي أولًا.</p></div></div></div>
<figure><div class="shot"><img src="/img/features/livechat-settings.png" alt="شاشة إعدادات الدردشة المباشرة مع ضبط الأداة ولوحة معاينة مباشرة" loading="lazy" decoding="async" width="3186" height="1766"></div><figcaption><svg width="13" height="13" viewBox="0 0 24 24" fill="none"><rect x="2.5" y="6" width="19" height="14" rx="2.5" stroke="currentColor" stroke-width="2"/><circle cx="12" cy="13" r="3.4" stroke="currentColor" stroke-width="2"/><path d="M8.5 6l1.2-2h4.6L15.5 6" stroke="currentColor" stroke-width="2" stroke-linejoin="round"/></svg><span>تحمل شاشة الإعدادات معاينة مباشرة، فترى أثر كل تغيير قبل نشره.</span></figcaption></figure>
<div class="note"><svg width="17" height="17" viewBox="0 0 24 24" fill="none"><circle cx="12" cy="12" r="9" stroke="#0f7e7a" stroke-width="2"/><path d="M12 11v5" stroke="#0f7e7a" stroke-width="2" stroke-linecap="round"/><circle cx="12" cy="7.8" r="1.1" fill="#0f7e7a"/></svg><div class="m"><div class="h">لا حاجة إلى تثبيت من جهة العميل</div><p>لا يحتاج زوّار الموقع إلى شيء. تُحمَّل الأداة في صفحتك وتبدأ المحادثة هناك.</p></div></div>
</section>
<section id="customise"><h2>الهوية البصرية والسلوك</h2>
<p>ينبغي أن تبدو الأداة جزءًا من موقعك لا من مزوّد دعم. وكل ما يراه الزائر قابل للضبط، مع معاينة مباشرة بجانب عناصر التحكّم.</p>
<h3>ما يمكنك تغييره</h3>
<ul><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>لون التمييز، ليطابق زرّ التشغيل هويّتك</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>موضع زرّ التشغيل يمينًا أو يسارًا، مع إزاحة لعناصر عائمة أخرى</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>نص الترحيب وسطر تعريفي قصير، لكل لغة</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>ساعات التوفّر، وما تقوله الأداة خارجها</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>هل يجيب وكيل الذكاء الاصطناعي أولًا أم تنتظر المحادثة شخصًا</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>حقول ما قبل الدردشة، إن أردت اسمًا أو بريدًا قبل بدء المحادثة</span></li></ul>
<h3>تعدّد اللغات</h3>
<p>يمكن ضبط نصوص الأداة لكل لغة، فيرى الزائر الفرنسي الفرنسية ويرى الزائر العربي العربية. ويجيب وكيل الذكاء الاصطناعي باللغة التي يكتب بها الزائر، معتمدًا على قاعدة المعرفة نفسها.</p>
</section>
<section id="context"><h2>سياق الزائر الذي يستفيد منه موظفوك</h2>
<p>زائر الموقع مجهول افتراضيًا، وهو ما يبدو عيبًا حتى تلاحظ كم تخبرك الجلسة نفسها. فمن أمضى أربع دقائق في صفحة الأسعار يسأل سؤالًا مختلفًا عمّن وصل لتوّه إلى الصفحة الرئيسية.</p>
<p>تعرض لوحة السياق الجلسة لا بطاقة جهة اتصال: الصفحة التي يتصفّحها، وكيف وصل، والمتصفّح والجهاز، ومدة بقائه في الموقع، والصفحات التي مرّ بها.</p>
<ul><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>الصفحة الحالية، ليعرف الموظف ما ينظر إليه الزائر</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>مسار الصفحات، وهو يكشف النية غالبًا أفضل من الرسالة الأولى</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>المتصفّح والجهاز ونظام التشغيل، لتشخيص المشكلات</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>المُحيل، لتعرف إن جاء من إعلان أم من بحث</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>مدة البقاء في الموقع وبداية الجلسة</span></li></ul>
<p>وإذا عرّف الزائر عن نفسه — عبر حقل ما قبل الدردشة أو بإعطاء بريده في المحادثة — رُبطت الجلسة بجهة اتصال وظهر سجلّه من القنوات الأخرى.</p>
</section>
<section id="ai"><h2>الذكاء الاصطناعي في الأداة</h2>
<p>لدردشة الموقع توقّع مختلف عن واتساب. فالزائر الجالس في صفحة الأسعار ينتظر إجابة خلال ثوانٍ، وسيغلق التبويب بدل أن ينتظر. وهنا يحقّق الوضع المستقل أكبر فائدة.</p>
<p>ينطبق وكيل الذكاء الاصطناعي نفسه وقاعدة المعرفة نفسها وقواعد التصعيد نفسها. غير أنه يمكنك ضبط وضع مختلف لكل قناة: فكثير من الفرق تشغّل الوضع المستقل في الأداة لردود فورية، والاقتراح فقط في واتساب حيث يُقبل ردّ بشري أبطأ قليلًا.</p>
<div class="note"><svg width="17" height="17" viewBox="0 0 24 24" fill="none"><circle cx="12" cy="12" r="9" stroke="#0f7e7a" stroke-width="2"/><path d="M12 11v5" stroke="#0f7e7a" stroke-width="2" stroke-linecap="round"/><circle cx="12" cy="7.8" r="1.1" fill="#0f7e7a"/></svg><div class="m"><div class="h">التصعيد يبقى ساريًا</div><p>الزائر الذي يسأل عن استرداد أو يستخدم كلمة محفّزة يُسلَّم إلى إنسان في الأداة تمامًا كما يحدث في واتساب.</p></div></div>
<p>مزيد من التفاصيل في <a href="/features/ai-agent">وكيل الذكاء الاصطناعي للدعم</a>.</p>
</section>
<section id="perf"><h2>الأداء والخصوصية</h2>
<p>أداة الدردشة موجودة في كل صفحة من موقعك، فوزنها وزنك. وأداة wavadesk تُحمَّل بشكل غير متزامن ولا تعيق العرض — إذ يظهر زرّ التشغيل بعد أن تصبح صفحتك تفاعلية لا قبلها.</p>
<ul><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>تحميل غير متزامن بلا إعاقة للعرض</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>بلا وحدات إعلان أو تتبّع من أطراف ثالثة</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>بيانات الجلسة محصورة بما تعرضه لوحة السياق</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>المحادثات مخزّنة في مساحة عملك لا مشتركة بين العملاء</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>تحترم الأداة ساعات توفّرك بدل الإيحاء بوجود أحد</span></li></ul>
</section>
