{{-- نص المقال بالعربية لصفحة /features/otp-service.
     البنية مطابقة للنسخة الإنجليزية: النص وحده يتغيّر، حتى تبقى معرّفات
     الأقسام في config/seo_pages.php صالحة. --}}
<section id="what"><h2>ما الذي تفعله خدمة رموز التحقّق</h2>
<p>رموز المرور لمرة واحدة هي عماد أمان الحسابات: تأكيد التسجيل، والتحقّق عند الدخول، وإعادة تعيين كلمة المرور، وتأكيد معاملة كبيرة، والتحقّق من رقم قبل التسليم. تحتاجها كل المنتجات تقريبًا، وترسلها كلها تقريبًا عبر الرسائل النصية افتراضيًا.</p>
<p>ترسل وحدة OTP في wavadesk تلك الرموز عبر واتساب بدلًا من ذلك. تستدعي نقطة نهاية مع رقم هاتف، فنسلّم رسالة تحمل الرمز، ثم تتحقّق من الرمز الذي أدخله العميل عبر استدعاء ثانٍ. أما التسليم والانتهاء وحدود المحاولات فتُدار نيابةً عنك.</p>
<div class="cards"><div class="fc"><div class="ic"><svg width="19" height="19" viewBox="0 0 24 24" fill="none"><circle cx="8" cy="12" r="4.2" stroke="#0f7e7a" stroke-width="2"/><path d="M12 12h9M17 12v4" stroke="#0f7e7a" stroke-width="2" stroke-linecap="round"/></svg></div><div class="h">التوليد والإرسال</div><p>طلب واحد ينشئ رمزًا ويخزّنه مجزّأً ويسلّمه إلى واتساب العميل.</p></div><div class="fc"><div class="ic"><svg width="19" height="19" viewBox="0 0 24 24" fill="none"><path d="M12 2l8 4v6c0 5-3.4 8.8-8 10-4.6-1.2-8-5-8-10V6l8-4z" stroke="#0f7e7a" stroke-width="2" stroke-linejoin="round"/></svg></div><div class="h">التحقّق</div><p>طلب ثانٍ يفحص الرمز الذي أدخله العميل، مع تطبيق حدود المحاولات والانتهاء.</p></div><div class="fc"><div class="ic"><svg width="19" height="19" viewBox="0 0 24 24" fill="none"><circle cx="12" cy="12" r="9" stroke="#0f7e7a" stroke-width="2"/><path d="M12 7v5.4l3.4 2" stroke="#0f7e7a" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/></svg></div><div class="h">إدارة الانتهاء</div><p>تنتهي صلاحية الرموز وفق مهلة تحدّدها. والرمز المنتهي يُرفض بدل أن يبقى صالحًا.</p></div><div class="fc"><div class="ic"><svg width="19" height="19" viewBox="0 0 24 24" fill="none"><path d="M4 20V10M10 20V4M16 20v-7M22 20H2" stroke="#0f7e7a" stroke-width="2" stroke-linecap="round"/></svg></div><div class="h">تقارير التسليم</div><p>أعداد المُرسَل والمُسلَّم والمُتحقَّق منه، لترى مواضع التسرّب في المسار بدل تخمينها.</p></div></div>
</section>
<section id="why"><h2>لماذا يتفوّق واتساب على الرسائل النصية في التحقّق</h2>
<p>ليست المسألة تفضيلًا شخصيًا. بل هناك أربعة فروق تشغيلية ملموسة.</p>
<h3>تسليم يمكنك تأكيده فعلًا</h3>
<p>تمنحك الرسائل النصية إيصال إرسال من وسيط، لا دليلًا على أن إنسانًا رآها. أما واتساب فيمنح حالتي التسليم والقراءة، فحين يقول عميل إن الرمز لم يصل يمكنك التحقّق بدل التخمين.</p>
<h3>تكلفة كل عملية تحقّق</h3>
<p>تُسعَّر الرسائل النصية لكل رسالة ولكل بلد، وتتراكم تكاليف التحقّق الدولي بسرعة. أما محادثات واتساب في wavadesk فغير محدودة في كل الباقات، فتكون التكلفة الحدّية لأي تحقّق إضافي صفرًا.</p>
<h3>يصل حيث توجد المحادثة أصلًا</h3>
<p>إن كان عميلك يراسلك أصلًا على واتساب، فسيظهر الرمز في محادثة يعرفها من مُرسِل سبق أن تحدّث إليه. وهذا يقلّل فعليًا شبهة التصيّد التي تثيرها الأرقام القصيرة المجهولة.</p>
<h3>بلا اعتماد لأرقام قصيرة أو أسماء مُرسِل</h3>
<p>يختلف تسجيل مُرسِل الرسائل النصية من بلد لآخر وقد يستغرق أسابيع. أما رقم واتساب فمتصل بالفعل وهو ملكك بالفعل.</p>
<div class="tw"><table><thead><tr><th></th><th>الرسائل النصية</th><th>واتساب عبر wavadesk</th></tr></thead><tbody><tr><td>تكلفة الرسالة</td><td>لكل رسالة ولكل بلد</td><td>مشمولة — محادثات غير محدودة</td></tr><tr><td>تأكيد الاستلام</td><td>إيصال إرسال فقط</td><td>حالتا التسليم والقراءة</td></tr><tr><td>معرفة المُرسِل</td><td>رقم قصير مجهول</td><td>رقم عملك الحالي</td></tr><tr><td>الإعداد</td><td>اعتماد اسم مُرسِل أو رقم قصير</td><td>متصل بالفعل عبر رمز QR</td></tr><tr><td>محتوى غني</td><td>160 حرفًا بلا تنسيق</td><td>تنسيق وهوية بصرية متاحان</td></tr></tbody></table></div>
<div class="note amber"><svg width="17" height="17" viewBox="0 0 24 24" fill="none"><path d="M12 8v5" stroke="#92400e" stroke-width="2.2" stroke-linecap="round"/><circle cx="12" cy="16.5" r="1.2" fill="#92400e"/><circle cx="12" cy="12" r="9" stroke="#92400e" stroke-width="2"/></svg><div class="m"><div class="h">أبقِ الرسائل النصية خيارًا احتياطيًا للتغطية</div><p>نسبة صغيرة من العملاء لن يكون لديهم واتساب. وترسل معظم الفرق عبر واتساب أولًا ثم تتحوّل إلى الرسائل النصية عند عدم التسليم — والوحدة تُبلّغ عن عدم التسليم لتتمكّن من تفعيل ذلك.</p></div></div>
</section>
<section id="how"><h2>كيف تعمل عمليًا</h2>
<p>نقطتا نهاية، وبلا أي حالة تحفظها أنت. فالرمز نفسه يُولَّد ويُجزَّأ ويُخزَّن لدينا؛ ولا تحتفظ به أبدًا.</p>
<div class="steps"><div class="step"><span class="n">1</span><div class="m"><div class="h">اطلب رمزًا</div><p>يستدعي نظامك نقطة الإرسال مع رقم هاتف العميل ووسم غرض اختياري مثل تسجيل الدخول أو إنشاء حساب.</p></div></div><div class="step"><span class="n">2</span><div class="m"><div class="h">يستلمه العميل على واتساب</div><p>تصل الرسالة من رقم عملك المتصل، وباللغة التي تحدّدها.</p></div></div><div class="step"><span class="n">3</span><div class="m"><div class="h">يُدخل العميل الرمز</div><p>في تطبيقك أو موقعك أو صفحة الدفع — حيثما يجري التحقّق.</p></div></div><div class="step"><span class="n">4</span><div class="m"><div class="h">يتحقّق نظامك</div><p>استدعِ نقطة التحقّق بالرقم والرمز. فتحصل على نجاح أو فشل، ومع الفشل يأتي السبب: خطأ أو انتهاء صلاحية أو محاولات كثيرة.</p></div></div></div>
<div class="note"><svg width="17" height="17" viewBox="0 0 24 24" fill="none"><circle cx="12" cy="12" r="9" stroke="#0f7e7a" stroke-width="2"/><path d="M12 11v5" stroke="#0f7e7a" stroke-width="2" stroke-linecap="round"/><circle cx="12" cy="7.8" r="1.1" fill="#0f7e7a"/></svg><div class="m"><div class="h">لا تُعاد الرموز إليك أبدًا</div><p>لا يعيد استدعاء الإرسال الرمز إليك. فالتحقّق يجري عبر نقطة التحقّق، ومن ثمّ لا يمكن لتسريب في سجلّاتك أن يكشف رموزًا فعّالة.</p></div></div>
<p>تفاصيل الطلبات والاستجابات كاملة في <a href="/features/api-integrations">الواجهة البرمجية والتكاملات</a>.</p>
</section>
<section id="security"><h2>ضوابط الأمان</h2>
<p>نظام رموز التحقّق هو نفسه ضابط أمني، لذا تهمّ إعداداته الافتراضية. وهذه مفروضة لا اختيارية.</p>
<ul><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>الرموز مخزّنة مجزّأة، لا كنص صريح أبدًا، ولا تعيدها نقطة الإرسال</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>مهلة انتهاء قابلة للضبط، وعمرها الافتراضي قصير</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>حدّ للمحاولات لكل رمز، وبعده يُحرَق الرمز ويجب طلب رمز جديد</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>حدّ للمعدّل لكل رقم، حتى لا يستخدم مهاجم نقطتك لإزعاج ضحية</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>حدّ للمعدّل لكل مفتاح واجهة، لاحتواء أي بيانات اعتماد مسرَّبة</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>رموز لمرة واحدة — لا يمكن إعادة استخدام رمز جرى التحقّق منه</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>سجلّ تدقيق كامل لكل إرسال ولكل محاولة تحقّق مع الأختام الزمنية</span></li></ul>
<h3>إساءة الاستخدام التي ينبغي التفكير فيها</h3>
<p>الخطر الأساسي في أي نقطة لرموز التحقّق ليس تخمين الرمز، بل استخدامها مدفعًا مجانيًا للرسائل ضد هاتف شخص آخر. وحدود المعدّل لكل رقم هي الدفاع، وهي مفعّلة افتراضيًا. وإن كنت تعرض نموذج تسجيل عامًّا، فضع أيضًا كابتشا أو ما يعادلها أمام استدعاء الإرسال.</p>
</section>
<section id="reporting"><h2>تقارير التسليم والتحويل</h2>
<p>التحقّق مسار، والمسارات تتسرّب. وتعرض التقارير عمليات الإرسال والتسليم والتحقّق الناجح لترى أين يحدث التسرّب.</p>
<figure><div class="shot"><img src="/img/features/kpis.png" alt="بطاقات مؤشرات لوحة التحكّم مع رسوم مصغّرة وفروق بين الفترات" loading="lazy" decoding="async" width="2552" height="370"></div><figcaption><svg width="13" height="13" viewBox="0 0 24 24" fill="none"><rect x="2.5" y="6" width="19" height="14" rx="2.5" stroke="currentColor" stroke-width="2"/><circle cx="12" cy="13" r="3.4" stroke="currentColor" stroke-width="2"/><path d="M8.5 6l1.2-2h4.6L15.5 6" stroke="currentColor" stroke-width="2" stroke-linejoin="round"/></svg><span>تظهر أعداد تسليم رموز التحقّق والتحقّق منها كمؤشرات بخطوط اتجاه، في مساحة التقارير نفسها التي يظهر فيها حجم المحادثات.</span></figcaption></figure>
<p>الفجوة بين المُسلَّم والمُتحقَّق منه هي الرقم الجدير بالمتابعة. واتّساعها يعني عادةً أحد ثلاثة أمور: شاشة إدخال الرمز مربكة، أو مهلة الانتهاء أقصر من اللازم لمستخدمين حقيقيين، أو أنك تتحقّق في نقطة من الرحلة يتخلّى الناس عندها أصلًا.</p>
<div class="stats"><div class="sc"><b>مُرسَلة</b><span>رموز طلبها نظامك</span></div><div class="sc"><b>مُسلَّمة</b><span>تأكّد وصولها إلى الهاتف</span></div><div class="sc"><b>مُتحقَّق منها</b><span>رموز أدخلها العميل بشكل صحيح</span></div></div>
</section>
<section id="cases"><h2>أين تستخدمها الفرق</h2>
<div class="cards"><div class="fc"><div class="ic"><svg width="19" height="19" viewBox="0 0 24 24" fill="none"><path d="M12 2l8 4v6c0 5-3.4 8.8-8 10-4.6-1.2-8-5-8-10V6l8-4z" stroke="#0f7e7a" stroke-width="2" stroke-linejoin="round"/></svg></div><div class="h">الدخول وإنشاء الحساب</div><p>تأكيد رقم الهاتف عند إنشاء الحساب، وتحقّق إضافي عند تسجيل الدخول.</p></div><div class="fc"><div class="ic"><svg width="19" height="19" viewBox="0 0 24 24" fill="none"><circle cx="8" cy="12" r="4.2" stroke="#0f7e7a" stroke-width="2"/><path d="M12 12h9M17 12v4" stroke="#0f7e7a" stroke-width="2" stroke-linecap="round"/></svg></div><div class="h">إعادة تعيين كلمة المرور</div><p>رمز إلى رقم موثّق، دون الاعتماد على وصول البريد الإلكتروني.</p></div><div class="fc"><div class="ic"><svg width="19" height="19" viewBox="0 0 24 24" fill="none"><rect x="3" y="5" width="18" height="16" rx="2.6" stroke="#0f7e7a" stroke-width="2"/><path d="M3 10h18M8 3v4M16 3v4" stroke="#0f7e7a" stroke-width="2" stroke-linecap="round"/></svg></div><div class="h">تأكيد الحجز</div><p>التحقّق من الرقم قبل تثبيت الحجز، ما يقلّل الحجوزات الوهمية.</p></div><div class="fc"><div class="ic"><svg width="19" height="19" viewBox="0 0 24 24" fill="none"><rect x="6" y="2.5" width="12" height="19" rx="2.6" stroke="#0f7e7a" stroke-width="2"/><path d="M11 18.5h2" stroke="#0f7e7a" stroke-width="2" stroke-linecap="round"/></svg></div><div class="h">تأكيد الاستلام</div><p>تأكيد رقم المستلم قبل الشحن، ما يقلّل عمليات التسليم الفاشلة.</p></div></div>
<p>وحدة رموز التحقّق مشمولة في باقة Scale ومتاحة كإضافة في غيرها. اطّلع على <a href="{{ url('/#pricing') }}">الأسعار</a>.</p>
</section>
