{{-- نص المقال بالعربية لصفحة /features/reservations.
     البنية مطابقة للنسخة الإنجليزية: النص وحده يتغيّر، حتى تبقى معرّفات
     الأقسام في config/seo_pages.php صالحة. --}}
<section id="why"><h2>لماذا ينجح الحجز عبر واتساب</h2>
<p>في العيادات والصالونات والورش والمطاعم والخدمات المهنية، يبدأ طلب الحجز دائمًا تقريبًا برسالة. يسأل أحدهم إن كان لديك موعد يوم الخميس. وما يحدث بعد ذلك هو ما يقرّر إن كنت ستحصل على الحجز.</p>
<p>والجواب المعتاد رابط إلى صفحة حجز، وهو ما يضيف خطوة لم يطلبها العميل. ونسبة معتبرة منهم لا يصلون أبدًا، لا لأنهم غيّروا رأيهم بل لأن العائق وقع في أسوأ لحظة ممكنة. وإبقاء الحجز داخل المحادثة يزيل هذا التسرّب.</p>
<div class="cards"><div class="fc"><div class="ic"><svg width="19" height="19" viewBox="0 0 24 24" fill="none"><rect x="3" y="5" width="18" height="16" rx="2.6" stroke="#0f7e7a" stroke-width="2"/><path d="M3 10h18M8 3v4M16 3v4" stroke="#0f7e7a" stroke-width="2" stroke-linecap="round"/></svg></div><div class="h">بلا انتقال بين السياقات</div><p>لا يغادر العميل المحادثة التي بدأها، فلا يضيع أحد بسبب تحويل.</p></div><div class="fc"><div class="ic"><svg width="19" height="19" viewBox="0 0 24 24" fill="none"><path d="M18 8.5a6 6 0 10-12 0c0 6-2.5 7.5-2.5 7.5h17S18 14.5 18 8.5z" stroke="#0f7e7a" stroke-width="2" stroke-linejoin="round"/><path d="M13.7 20a2 2 0 01-3.4 0" stroke="#0f7e7a" stroke-width="2" stroke-linecap="round"/></svg></div><div class="h">تذكيرات تُقرأ فعلًا</div><p>التذكير عبر واتساب في محادثة قائمة يُفتَح بموثوقية أعلى بكثير من رسالة نصية أو بريد إلكتروني.</p></div><div class="fc"><div class="ic"><svg width="19" height="19" viewBox="0 0 24 24" fill="none"><path d="M16 20v-2a4 4 0 00-4-4H6a4 4 0 00-4 4v2" stroke="#0f7e7a" stroke-width="2" stroke-linecap="round"/><circle cx="9" cy="7" r="3.4" stroke="#0f7e7a" stroke-width="2"/><path d="M22 20v-2a4 4 0 00-3-3.9" stroke="#0f7e7a" stroke-width="2" stroke-linecap="round"/></svg></div><div class="h">مكان واحد للمراجعة</div><p>الحجوزات والمحادثة التي أنتجتها في مكان واحد، فيرى الموظفون الاثنين معًا.</p></div><div class="fc"><div class="ic"><svg width="19" height="19" viewBox="0 0 24 24" fill="none"><circle cx="12" cy="12" r="9" stroke="#0f7e7a" stroke-width="2"/><path d="M12 7v5.4l3.4 2" stroke="#0f7e7a" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/></svg></div><div class="h">إعادة الجدولة تبقى بسيطة</div><p>تغيير الموعد ردّ لا نموذج. ولذلك يفعله الناس فعلًا بدل التغيّب.</p></div></div>
</section>
<section id="flow"><h2>مسار الحجز</h2>
<p>المسار قصير عن قصد، ويستطيع وكيل الذكاء الاصطناعي تولّي معظمه قبل تدخّل إنسان.</p>
<div class="steps"><div class="step"><span class="n">1</span><div class="m"><div class="h">يسأل العميل عن المواعيد المتاحة</div><p>إما بلغة حرّة أو باختيار من الخيارات التي يعرضها الذكاء الاصطناعي.</p></div></div><div class="step"><span class="n">2</span><div class="m"><div class="h">تُعرَض المواعيد المتاحة</div><p>مستمدّة من ساعات عملك المضبوطة ومدد الخدمات والحجوزات القائمة، فلا يقع حجز مزدوج.</p></div></div><div class="step"><span class="n">3</span><div class="m"><div class="h">يختار العميل موعدًا</div><p>يُؤكَّد داخل المحادثة. ويُحجَز الموعد فورًا.</p></div></div><div class="step"><span class="n">4</span><div class="m"><div class="h">تُجدوَل رسالة التأكيد والتذكير</div><p>تأكيد فوري، ثم تذكير وفق الجدول الذي تحدّده — عادةً قبل 24 ساعة ثم قبل ساعتين.</p></div></div></div>
<div class="note"><svg width="17" height="17" viewBox="0 0 24 24" fill="none"><circle cx="12" cy="12" r="9" stroke="#0f7e7a" stroke-width="2"/><path d="M12 11v5" stroke="#0f7e7a" stroke-width="2" stroke-linecap="round"/><circle cx="12" cy="7.8" r="1.1" fill="#0f7e7a"/></svg><div class="m"><div class="h">يستطيع الموظفون التدخّل دائمًا</div><p>إن احتاج العميل إلى ما لا تستطيع الأتمتة تولّيه — أخصائي بعينه أو موعد مزدوج أو حالة خاصة — استلم موظف المحادثة وحجز يدويًا. ويظل جدول التذكير ساريًا.</p></div></div>
</section>
<section id="noshows"><h2>تقليل حالات عدم الحضور</h2>
<p>عدم الحضور هو أكبر بند تكلفة في الأعمال القائمة على المواعيد، وهو في معظمه مشكلة نسيان لا مشكلة التزام. والحل تذكير يُرى فعلًا، مع وسيلة سهلة لتغيير الموعد.</p>
<p>التذكير الذي يقول فقط «لديك موعد غدًا» حلّ ناقص. فينبغي أن يجعل إعادة الجدولة سهلة سهولة التجاهل، لأن الموعد المعاد جدولته يمكن ملؤه أما الغياب فلا.</p>
<h3>ما الذي يفعله التذكير الفعّال</h3>
<ul><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>يصل في محادثة واتساب القائمة لا من مُرسِل مجهول</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>يذكر الخدمة والوقت والتاريخ والمكان دون أن يضطر العميل للبحث عن شيء</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>يتيح التأكيد أو إعادة الجدولة بردّ مباشر</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>يُرسَل وفق جدول تتحكّم به، عادةً قبل 24 ساعة وقبل ساعتين</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>يسجّل الردّ على الحجز، ليعرف الموظفون من أكّد</span></li></ul>
<div class="note amber"><svg width="17" height="17" viewBox="0 0 24 24" fill="none"><path d="M12 8v5" stroke="#92400e" stroke-width="2.2" stroke-linecap="round"/><circle cx="12" cy="16.5" r="1.2" fill="#92400e"/><circle cx="12" cy="12" r="9" stroke="#92400e" stroke-width="2"/></svg><div class="m"><div class="h">تذكيران هما السقف عادةً</div><p>قبل يوم وقبل ساعتين يغطّيان نافذة النسيان الواقعية. وأكثر من ذلك يُقرأ إلحاحًا فتُكتَم المحادثة، وتخسر القناة كلها.</p></div></div>
</section>
<section id="calendar"><h2>التقويم والطاقة</h2>
<p>لا تكون المواعيد المتاحة موثوقة إلا إذا عكست الواقع. وتعمل الوحدة انطلاقًا من طاقتك المضبوطة لا من تخمين يكتبه من يردّ.</p>
<ul><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>ساعات العمل لكل يوم، بما فيها الفترات المتقطّعة والإغلاق</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>مدد الخدمات، حتى لا يستهلك موعد من 20 دقيقة وآخر من 90 دقيقة الطاقة نفسها</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>موارد متعدّدة — أخصائيون وكراسٍ ومواقع وطاولات — لكل منها جدوله</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>وقت فاصل بين المواعيد حيث يلزم التجهيز</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>تواريخ محجوبة للعطلات والصيانة</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>حدّ أقصى للحجوزات المتزامنة في الموعد الواحد</span></li></ul>
<p>ولأن الطاقة تُعرَّف مرة واحدة، لا يمكن أن يتناقض موعد يعرضه الذكاء الاصطناعي مع موعد يعرضه موظف. فيصير الحجز المزدوج مسألة إعداد لا خطأً بشريًا.</p>
</section>
<section id="verify"><h2>التأكّد من أن الحجز حقيقي</h2>
<p>الأعمال ذات الطاقة الشحيحة — المطاعم في أوقات الذروة والعيادات ذات المواعيد المحدودة — تخسر مالًا بسبب حجوزات برقم خاطئ أو وهمي. وربط الحجوزات بوحدة رموز التحقّق يسدّ هذه الثغرة.</p>
<p>وحين تشترط التحقّق، يؤكّد العميل رقمه برمز لمرة واحدة قبل تثبيت الموعد. فتضيف خطوة واحدة على العميل وتزيل فئة كاملة من الخسائر عنك.</p>
<p>انظر <a href="/features/otp-service">رموز التحقّق عبر واتساب</a>.</p>
</section>
<section id="who"><h2>من يستخدم الحجوزات</h2>
<div class="cards"><div class="fc"><div class="ic"><svg width="19" height="19" viewBox="0 0 24 24" fill="none"><path d="M16 20v-2a4 4 0 00-4-4H6a4 4 0 00-4 4v2" stroke="#0f7e7a" stroke-width="2" stroke-linecap="round"/><circle cx="9" cy="7" r="3.4" stroke="#0f7e7a" stroke-width="2"/><path d="M22 20v-2a4 4 0 00-3-3.9" stroke="#0f7e7a" stroke-width="2" stroke-linecap="round"/></svg></div><div class="h">العيادات وعيادات الأسنان</div><p>طلبات المواعيد وإعادة الجدولة وتذكيرات المتابعة، حيث الرسالة الفائتة تعني حجزًا ضائعًا.</p></div><div class="fc"><div class="ic"><svg width="19" height="19" viewBox="0 0 24 24" fill="none"><rect x="3" y="5" width="18" height="16" rx="2.6" stroke="#0f7e7a" stroke-width="2"/><path d="M3 10h18M8 3v4M16 3v4" stroke="#0f7e7a" stroke-width="2" stroke-linecap="round"/></svg></div><div class="h">الصالونات والحلاقون</div><p>حجم كبير من المواعيد القصيرة، وكثرة في إعادة الجدولة، وتكلفة حقيقية للغياب.</p></div><div class="fc"><div class="ic"><svg width="19" height="19" viewBox="0 0 24 24" fill="none"><rect x="6" y="2.5" width="12" height="19" rx="2.6" stroke="#0f7e7a" stroke-width="2"/><path d="M11 18.5h2" stroke="#0f7e7a" stroke-width="2" stroke-linecap="round"/></svg></div><div class="h">الورش ومراكز الصيانة</div><p>طاقة مواقع العمل مع مدد خدمة طويلة، حيث يكلّف الحجز المزدوج كثيرًا.</p></div><div class="fc"><div class="ic"><svg width="19" height="19" viewBox="0 0 24 24" fill="none"><circle cx="12" cy="12" r="9" stroke="#0f7e7a" stroke-width="2"/><path d="M3 12h18M12 3c2.5 2.6 2.5 15.4 0 18M12 3c-2.5 2.6-2.5 15.4 0 18" stroke="#0f7e7a" stroke-width="2"/></svg></div><div class="h">المطاعم</div><p>طاولات أوقات الذروة، حيث الحجوزات الموثّقة أهم من الكمّ.</p></div></div>
<p>وحدة الحجوزات مشمولة في باقة Scale ومتاحة كإضافة في غيرها.</p>
</section>
