{{-- نص المقال بالعربية لصفحة /features/teams-routing.
     البنية مطابقة للنسخة الإنجليزية: النص وحده يتغيّر، حتى تبقى معرّفات
     الأقسام في config/seo_pages.php صالحة. --}}
<section id="why"><h2>متى يتوقّف الطابور الواحد عن النجاح</h2>
<p>المجمّع المشترك هو الإعداد الافتراضي الصحيح. الجميع يرى كل شيء، وأي أحد يستطيع أخذ أي شيء، وكلفة الإعداد صفر. ويصمد ذلك حتى خمسة أو ستة موظفين تقريبًا يتعاملون مع أسئلة متشابهة عمومًا.</p>
<p>وبعد ذلك ينكسر أمران. يقضي الموظفون وقتًا حقيقيًا في التصفية بأعينهم — يقرؤون ويتخطّون محادثات تخصّ وظيفة أخرى. ويصبح التخصّص مستحيلًا: فإن كان من يتولّى نزاعات الفوترة يرى القائمة غير المميَّزة نفسها التي يراها الجميع، فخبرته غير موجَّهة إلى العمل الصحيح.</p>
<p>التوجيه هو الحل، وغرضه طرحيّ. فهو لا يمنح الناس معلومات أكثر، بل <strong>يمنح كل موظف أشياء أقل لينظر إليها</strong>، فيصير ما تبقّى ملكه.</p>
</section>
<section id="teams"><h2>تكوين الفرق</h2>
<p>الفريق مجموعة موظفين وطابور. وتبني معظم المؤسسات فرقها على الوظائف القائمة أصلًا بدل اختراع وظائف جديدة.</p>
<div class="cards"><div class="fc"><div class="ic"><svg width="19" height="19" viewBox="0 0 24 24" fill="none"><path d="M16 20v-2a4 4 0 00-4-4H6a4 4 0 00-4 4v2" stroke="#0f7e7a" stroke-width="2" stroke-linecap="round"/><circle cx="9" cy="7" r="3.4" stroke="#0f7e7a" stroke-width="2"/><path d="M22 20v-2a4 4 0 00-3-3.9" stroke="#0f7e7a" stroke-width="2" stroke-linecap="round"/></svg></div><div class="h">حسب الوظيفة</div><p>المبيعات والدعم والفوترة والإرجاع. وهو أشيع تقسيم، لأن المهارات مختلفة فعلًا.</p></div><div class="fc"><div class="ic"><svg width="19" height="19" viewBox="0 0 24 24" fill="none"><circle cx="12" cy="12" r="9" stroke="#0f7e7a" stroke-width="2"/><path d="M3 12h18M12 3c2.5 2.6 2.5 15.4 0 18M12 3c-2.5 2.6-2.5 15.4 0 18" stroke="#0f7e7a" stroke-width="2"/></svg></div><div class="h">حسب اللغة</div><p>حين تخدم عدة لغات ولا يتقن كل موظف جميعها.</p></div><div class="fc"><div class="ic"><svg width="19" height="19" viewBox="0 0 24 24" fill="none"><circle cx="12" cy="12" r="9" stroke="#0f7e7a" stroke-width="2"/><path d="M12 7v5.4l3.4 2" stroke="#0f7e7a" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/></svg></div><div class="h">حسب الوردية</div><p>فرق صباحية ومسائية، لتصل محادثات خارج الدوام إلى من هو على رأس العمل فعلًا.</p></div><div class="fc"><div class="ic"><svg width="19" height="19" viewBox="0 0 24 24" fill="none"><path d="M12 2H4a2 2 0 00-2 2v8l10 10 10-10L12 2z" stroke="#0f7e7a" stroke-width="2" stroke-linejoin="round"/><circle cx="7.5" cy="7.5" r="1.4" fill="#0f7e7a"/></svg></div><div class="h">حسب خط المنتجات</div><p>حين تكون المنتجات مختلفة بما يكفي لألا تنتقل المعرفة بينها.</p></div></div>
<p>يمكن أن ينتمي الموظف إلى أكثر من فريق. وكثيرًا ما تضع العمليات الصغيرة الجميع في كل الفرق بداية ثم تضيّق مع النمو — وهو الترتيب الصحيح، لأنك تتعلّم الحدود الحقيقية من حركة المحادثات.</p>
</section>
<section id="rules"><h2>قواعد التوجيه</h2>
<p>تُقيَّم القواعد بالترتيب، وأول تطابق يفوز. وإبقاء القائمة قصيرة ميزة لا قيد — فسلاسل القواعد الطويلة يستحيل تتبّعها حين يذهب شيء إلى المكان الخطأ.</p>
<h3>التوجيه بالكلمة المفتاحية</h3>
<p>كثيرًا ما تسمّي الرسالة نفسها القسم المعني. فـ«استرداد» و«فاتورة» و«ردّ مبلغ» تعني الفوترة؛ و«عرض سعر» و«الأسعار» تعني المبيعات. ويلتقط التوجيه بالكلمات الحالات الواضحة ويترك الملتبسة في المجمّع العام.</p>
<h3>التوجيه حسب القناة</h3>
<p>محادثات أداة الموقع غالبًا ما تكون ما قبل البيع — شخص يقرأ صفحة أسعارك — بينما يميل واتساب إلى العملاء الحاليين. والتوجيه حسب القناة مؤشر خشن لكنه فعّال على النية.</p>
<h3>التوجيه حسب الساعات</h3>
<p>خارج ساعات العمل ينبغي أن تصل المحادثات إلى حيث يوجد من يتابع، أو إلى طابور يُراجَع صراحةً في صباح اليوم التالي، لا إلى مجمّع عام لا يملكه أحد ليلًا.</p>
<h3>التوجيه حسب جهة الاتصال</h3>
<p>يمكن توجيه الحسابات المحدّدة أو العملاء المميّزين أو أرقام بعينها مباشرةً إلى فريق أو موظف معيّن، حتى لا تنتظر أهم علاقاتك خلف الحركة العامة.</p>
<div class="note"><svg width="17" height="17" viewBox="0 0 24 24" fill="none"><circle cx="12" cy="12" r="9" stroke="#0f7e7a" stroke-width="2"/><path d="M12 11v5" stroke="#0f7e7a" stroke-width="2" stroke-linecap="round"/><circle cx="12" cy="7.8" r="1.1" fill="#0f7e7a"/></svg><div class="m"><div class="h">اترك طابورًا افتراضيًا</div><p>كل إعداد توجيه يحتاج إلى طابور احتياطي للمحادثات التي لا تطابق شيئًا. وبدونه تختفي الحالات الاستثنائية.</p></div></div>
</section>
<section id="assignment"><h2>الإسناد والاستلام</h2>
<p>التوجيه يقرّر إلى أي طابور تدخل المحادثة. والإسناد يقرّر من يملكها. وهما أمران منفصلان، والخلط بينهما أشيع خطأ في الإعداد.</p>
<ul><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>موجَّهة إلى فريق وغير مُسنَدة — يستلمها موظفو ذلك الفريق من الطابور</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>إسناد تلقائي بالتناوب — يوزَّع بالتساوي على الموظفين المتاحين في الفريق</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>مُسنَدة إلى موظف بعينه — للحسابات المحدّدة أو لمتابعة محادثة سابقة</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>أُعيد إسنادها من مشرف — مسجَّلة، فيبقى التسليم ظاهرًا في سجلّ التدقيق</span></li></ul>
<p>ينبغي أن تبدأ معظم الفرق بالتوجيه دون إسناد مع الاستلام. فالتناوب يبدو أعدل لكنه يوزّع العمل على أشخاص قد يكونون في منتصف محادثة معقّدة، ويسلب الموظف قدرته على أخذ ما هو الأقدر على الإجابة عنه.</p>
<div class="note amber"><svg width="17" height="17" viewBox="0 0 24 24" fill="none"><path d="M12 8v5" stroke="#92400e" stroke-width="2.2" stroke-linecap="round"/><circle cx="12" cy="16.5" r="1.2" fill="#92400e"/><circle cx="12" cy="12" r="9" stroke="#92400e" stroke-width="2"/></svg><div class="m"><div class="h">الإسناد التلقائي يحتاج إلى حضور موثوق</div><p>إسناد المحادثات إلى موظف غير متصل يخلق طابورًا صامتًا خلف شخص واحد. فلا تفعّله إلا حيث يمكن الاعتماد على دقّة حالة التوفّر.</p></div></div>
</section>
<section id="escalation"><h2>التصعيد والتقادم</h2>
<p>كل إعداد توجيه ينتهي به الأمر إلى ترك محادثة عالقة: هي في الطابور الصحيح ولم يستلمها أحد. وقواعد التصعيد تلتقط ذلك تلقائيًا بدل الاعتماد على انتباه أحدهم.</p>
<div class="steps"><div class="step"><span class="n">1</span><div class="m"><div class="h">حدّد عتبة زمنية</div><p>مثلًا 15 دقيقة دون استلام خلال ساعات العمل.</p></div></div><div class="step"><span class="n">2</span><div class="m"><div class="h">صعّد عند التجاوز</div><p>انقل المحادثة إلى طابور مشرف، أو أبرزها في أعلى طابور الفريق.</p></div></div><div class="step"><span class="n">3</span><div class="m"><div class="h">راقب رقم أطول انتظار</div><p>يُبرز الطابور المحادثة الأطول انتظارًا، فيظهر الرقم المتصاعد قبل أن يشتكي العملاء.</p></div></div><div class="step"><span class="n">4</span><div class="m"><div class="h">اضبط العتبة على الواقع</div><p>العتبة التي لا يستطيع أحد الوفاء بها مجرّد ضجيج. ضعها حيث يكون التجاوز استثنائيًا حقًّا.</p></div></div></div>
<figure><div class="shot"><img src="/img/features/agents-heatmap.png" alt="لوحة حِمل الموظفين بأشرطة الطاقة وخريطة حرارية لساعات الذروة" loading="lazy" decoding="async" width="2552" height="702"></div><figcaption><svg width="13" height="13" viewBox="0 0 24 24" fill="none"><rect x="2.5" y="6" width="19" height="14" rx="2.5" stroke="currentColor" stroke-width="2"/><circle cx="12" cy="13" r="3.4" stroke="currentColor" stroke-width="2"/><path d="M8.5 6l1.2-2h4.6L15.5 6" stroke="currentColor" stroke-width="2" stroke-linejoin="round"/></svg><span>حِمل كل موظف بأشرطة الطاقة، والساعات التي يصل فيها الحجم فعلًا — وهما المدخلان لضبط عتبات واقعية وتغطية الورديات.</span></figcaption></figure>
</section>
<section id="measure"><h2>التأكّد من صحّة توجيهك</h2>
<p>التوجيه فرضية عن كيفية تقسيم العمل. والتقارير تخبرك هل تصمد الفرضية.</p>
<ul><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>نسبة إعادة الإسناد — ارتفاعها يعني أن القواعد ترسل العمل إلى الفريق الخطأ</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>زمن الاستجابة لكل فريق — الطابور البطيء يعني عادةً نقص عدد لا تكاسلًا</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>توازن حِمل الموظفين — التفاوت المستمر يعني أن التوجيه يكدّس العمل</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>تواتر التصعيد — ارتفاعه يعني أن العتبات أو الطاقم بحاجة إلى مراجعة</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>الحجم حسب الساعة مقابل تغطية الورديات — الخريطة الحرارية مقابل جدولك</span></li></ul>
<p>مزيد من التفاصيل في <a href="/features/reports-analytics">تقارير الدعم والتحليلات</a>.</p>
</section>
