{{-- نص المقال بالعربية لصفحة /features/whatsapp-multi-agent.
     البنية مطابقة للنسخة الإنجليزية: النص وحده يتغيّر، حتى تبقى معرّفات
     الأقسام في config/seo_pages.php صالحة. --}}
<section id="why"><h2>لماذا لا يكفي واتساب وحده</h2>
<p>واتساب بيزنس أداة ممتازة لمشغّل واحد. صُمّم حول حساب واحد وجهاز واحد وإدراك شخص واحد لما جرى التعامل معه. وميزة الأجهزة المرتبطة توسّع ذلك إلى بضع شاشات، لكنها لا تغيّر النموذج: الجميع ينظر إلى التدفّق نفسه غير المميَّز، بلا أي مفهوم لمن يملك ماذا.</p>
<p>وفي هذا التمييز تكمن المشكلة كلها. فأن <em>يرى</em> عدة أشخاص الرسائل ليس كأن <em>يعمل</em> عليها عدة أشخاص. فبلا ملكية، تُنشئ الرؤية المشتركة فعليًا أنماط فشل لا يعرفها المشغّل الواحد أبدًا.</p>
<div class="tw"><table><thead><tr><th>ما يحتاجه الفريق</th><th>هاتف مشترك أو أجهزة مرتبطة</th><th>مع wavadesk</th></tr></thead><tbody><tr><td>رؤية ما ينتظر</td><td>تدفّق، وأقدم الرسائل بعيدة عن الأنظار</td><td>طابور بأزمنة انتظار وإبراز للأقدم</td></tr><tr><td>معرفة من يتولّاها</td><td>لا شيء — تسأل بصوت مرتفع</td><td>الاستلام يقفل المحادثة على موظف واحد</td></tr><tr><td>منع الردود المكرّرة</td><td>العُرف والحظ</td><td>مطبَّق في قاعدة البيانات</td></tr><tr><td>حفظ السجلّ عند تغيّر الموظفين</td><td>مرتبط بالجهاز</td><td>مرتبط بمساحة العمل</td></tr><tr><td>التقسيم حسب القسم</td><td>غير ممكن</td><td>توجيه إلى طوابير الفرق</td></tr><tr><td>تقارير زمن الاستجابة</td><td>لا بيانات</td><td>وسيط أول ردّ، والحل، وحِمل كل موظف</td></tr></tbody></table></div>
<p>والنتيجة العملية أن الوصول المشترك بلا ملكية يكون غالبًا أسوأ من شخص واحد متفرّغ، لأن المسؤولية تتشتّت. فيفترض كلٌّ أن غيره قد ردّ.</p>
</section>
<section id="model"><h2>كيف يبدو الوصول متعدّد الموظفين حقًّا</h2>
<p>يحتاج الدعم متعدّد الموظفين إلى أربعة أمور تتجاوز الرؤية المشتركة. كلٌّ منها يجيب عن سؤال لا يضطر المشغّل الواحد إلى طرحه أبدًا.</p>
<div class="cards"><div class="fc"><div class="ic"><svg width="19" height="19" viewBox="0 0 24 24" fill="none"><path d="M21 11.5a8.4 8.4 0 01-9 8.4 8.9 8.9 0 01-3.9-.9L3 20.5l1.5-4.6A8.4 8.4 0 013.6 11.5a8.4 8.4 0 018.4-8.4 8.4 8.4 0 019 8.4z" stroke="#0f7e7a" stroke-width="2" stroke-linejoin="round"/></svg></div><div class="h">طابور</div><p>ما الذي ينتظر، ومنذ متى؟ التدفّق لا يجيب عن هذا؛ أما الطابور المختوم زمنيًا فيجيب.</p></div><div class="fc"><div class="ic"><svg width="19" height="19" viewBox="0 0 24 24" fill="none"><rect x="4.5" y="10.5" width="15" height="10" rx="2.2" stroke="#0f7e7a" stroke-width="2"/><path d="M8 10.5V7a4 4 0 018 0v3.5" stroke="#0f7e7a" stroke-width="2" stroke-linecap="round"/></svg></div><div class="h">ملكية</div><p>من يتولّى هذه الآن، وهل يستطيع غيره الإرسال فيها؟ هذا هو الاستلام، ويجب أن يكون مفروضًا لا متّفقًا عليه.</p></div><div class="fc"><div class="ic"><svg width="19" height="19" viewBox="0 0 24 24" fill="none"><path d="M12 3v6M12 15v6M3 12h6M15 12h6" stroke="#0f7e7a" stroke-width="2" stroke-linecap="round"/><circle cx="12" cy="12" r="2.6" stroke="#0f7e7a" stroke-width="2"/></svg></div><div class="h">توجيه</div><p>أي فريق ينبغي أن يرى هذه أصلًا؟ أسئلة الفوترة لا مكان لها في طابور المبيعات.</p></div><div class="fc"><div class="ic"><svg width="19" height="19" viewBox="0 0 24 24" fill="none"><path d="M4 20V10M10 20V4M16 20v-7M22 20H2" stroke="#0f7e7a" stroke-width="2" stroke-linecap="round"/></svg></div><div class="h">نسبة الإجراءات</div><p>من فعل ماذا ومتى؟ للمساءلة، ولمعرفة أين يذهب الوقت فعلًا.</p></div></div>
<figure><div class="shot"><img src="/img/features/inbox-full.png" alt="صندوق وارد wavadesk مع مجمّع محادثات مشترك ومحادثة مفتوحة ولوحة العميل" loading="lazy" decoding="async" width="3186" height="1766"></div><figcaption><svg width="13" height="13" viewBox="0 0 24 24" fill="none"><rect x="2.5" y="6" width="19" height="14" rx="2.5" stroke="currentColor" stroke-width="2"/><circle cx="12" cy="13" r="3.4" stroke="currentColor" stroke-width="2"/><path d="M8.5 6l1.2-2h4.6L15.5 6" stroke="currentColor" stroke-width="2" stroke-linejoin="round"/></svg><span>الملكية ظاهرة في الطابور نفسه: محادثات غير مستلَمة، ومحادثات مقفلة باسم موظف، ومحادثات يتولّاها الذكاء الاصطناعي.</span></figcaption></figure>
</section>
<section id="claiming"><h2>الاستلام: ملكية لا يمكن إضاعتها</h2>
<p>في wavadesk يعمل الموظفون من مجمّع مشترك ويستلمون المحادثة ليأخذوها. والاستلام يفعل أمرين معًا: يخبر الفريق أن هذه يجري التعامل معها، ويقفل المحادثة فلا يردّ فيها أحد سواه.</p>
<p>والقفل مطبَّق على مستوى قاعدة البيانات. فإن ضغط موظفان على الاستلام في الثانية نفسها، فاز أحدهما وأُبلغ الآخر أن المحادثة مأخوذة. لا توجد لحظة يظنّ فيها كلاهما أنه المالك — وتلك اللحظة بالضبط هي مولد الردود المكرّرة.</p>
<div class="note"><svg width="17" height="17" viewBox="0 0 24 24" fill="none"><circle cx="12" cy="12" r="9" stroke="#0f7e7a" stroke-width="2"/><path d="M12 11v5" stroke="#0f7e7a" stroke-width="2" stroke-linecap="round"/><circle cx="12" cy="7.8" r="1.1" fill="#0f7e7a"/></svg><div class="m"><div class="h">الإفراج وإعادة الإسناد</div><p>الاستلام ليس دائمًا. يستطيع الموظف إعادة المحادثة إلى المجمّع، ويستطيع المشرف إعادة إسنادها — وكلاهما مسجَّل، فيبقى التسليم ظاهرًا.</p></div></div>
</section>
<section id="routing"><h2>التوجيه ليرى الناس أقل لا أكثر</h2>
<p>المجمّع الواحد مناسب لفريق من ثلاثة. وعند خمسة عشر يصير ضجيجًا: يمرّ كل موظف على ثلاثين محادثة لا تخصّه ليجد ما يخصّه.</p>
<p>يضع التوجيه المحادثات أمام الفريق الصحيح وفق قواعد تحدّدها، فيصير طابور كل موظف هو الجزء الذي يستطيع التعامل معه فعلًا. والباقي ما زال موجودًا وقابلًا للتدقيق، لكنه ليس في طريقه.</p>
<ul><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>وجّه حسب الفريق، ليكون للإرجاع والفوترة والمبيعات طابور خاص بكل منها</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>وجّه حسب الكلمة المفتاحية، حين تحدّد الرسالة نفسها القسم المعني</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>وجّه حسب ساعات العمل، لتصل محادثات خارج الدوام إلى حيث يوجد من يتابع</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>صعّد إلى مشرف حين تتجاوز المحادثة عتبة زمنية</span></li></ul>
<p>اقرأ المزيد في <a href="/features/teams-routing">الفرق والتوجيه والإسناد</a>.</p>
</section>
<section id="seats"><h2>كيف تعمل المقاعد والطاقة</h2>
<p>كل شخص يردّ على العملاء يحتاج إلى حساب خاص به، ليكون للاستلام ولسجلّ التدقيق معنى. أما الحسابات المشتركة فتُبطل الاثنين.</p>
<p>تشمل الباقات عددًا أساسيًا من المقاعد، ويمكنك إضافة المزيد دون تغيير الباقة حين يكبر الفريق في منتصف الدورة. والطاقة ظاهرة في شاشة الفوترة بدل أن تكتشفها عند اصطدامك بحائط.</p>
<figure><div class="shot"><img src="/img/features/usage-meters.png" alt="مؤشرات الاستهلاك تعرض المستخدمين ورسائل الذكاء الاصطناعي مقابل حصّة الباقة" loading="lazy" decoding="async" width="1760" height="322"></div><figcaption><svg width="13" height="13" viewBox="0 0 24 24" fill="none"><rect x="2.5" y="6" width="19" height="14" rx="2.5" stroke="currentColor" stroke-width="2"/><circle cx="12" cy="13" r="3.4" stroke="currentColor" stroke-width="2"/><path d="M8.5 6l1.2-2h4.6L15.5 6" stroke="currentColor" stroke-width="2" stroke-linejoin="round"/></svg><span>استهلاك المقاعد ورسائل الذكاء الاصطناعي مقارنةً بحصّة باقتك، مع إمكانية إضافة طاقة دون تغيير الباقة.</span></figcaption></figure>
<p>اطّلع على <a href="{{ url('/#pricing') }}">الأسعار</a> لمعرفة ما تشمله كل باقة.</p>
</section>
<section id="migrate"><h2>نقل فريق من هاتف مشترك</h2>
<p>عادةً ما يكون الانتقال أقل اضطرابًا مما تتوقّعه الفرق، لأن الجانب الذي يراه العميل لا يتغيّر إطلاقًا.</p>
<div class="steps"><div class="step"><span class="n">1</span><div class="m"><div class="h">اربط الرقم الحالي</div><p>امسح رمز QR بالهاتف الذي يحمل حساب واتساب بيزنس. وتبدأ المحادثات بالوصول إلى المجمّع المشترك.</p></div></div><div class="step"><span class="n">2</span><div class="m"><div class="h">أضف من يردّون بالفعل</div><p>امنح كلًّا منهم مقعدًا. ابدأ بالمجموعة نفسها التي تتشارك الهاتف اليوم.</p></div></div><div class="step"><span class="n">3</span><div class="m"><div class="h">اتفقوا على قاعدة واحدة: استلم قبل أن تردّ</div><p>هذا هو التغيير السلوكي الوحيد، والواجهة تفرضه على أي حال.</p></div></div><div class="step"><span class="n">4</span><div class="m"><div class="h">توقّف عن الردّ من الهاتف</div><p>هذه هي الخطوة التي تتخطّاها الفرق، وهي الأهم. فالردود المرسَلة من الهاتف تتجاوز الطابور وسجلّ التدقيق.</p></div></div></div>
<div class="note amber"><svg width="17" height="17" viewBox="0 0 24 24" fill="none"><path d="M12 8v5" stroke="#92400e" stroke-width="2.2" stroke-linecap="round"/><circle cx="12" cy="16.5" r="1.2" fill="#92400e"/><circle cx="12" cy="12" r="9" stroke="#92400e" stroke-width="2"/></svg><div class="m"><div class="h">لا تُبقِ الطريقتين معًا طويلًا</div><p>أسبوع من التداخل مقبول ريثما يعتاد الناس. وأطول من ذلك يعني مرجعين للحقيقة، وهي المشكلة التي كنت تحاول حلّها.</p></div></div>
</section>
