{{-- نص المقال بالعربية لصفحة /features/whatsapp-shared-inbox.
     البنية مطابقة للنسخة الإنجليزية: النص وحده يتغيّر، حتى تبقى معرّفات
     الأقسام في config/seo_pages.php صالحة. --}}
<section id="problem"><h2>مشكلة الهاتف الواحد</h2>
<p>تبدأ كل فرق الدعم على واتساب تقريبًا بالطريقة نفسها: هاتف واحد، أو حساب واحد على واتساب ويب، يتشاركه من هو في الوردية. ينجح الأمر فترة. ثم يكبر الحجم فيتبيّن أن الشقوق بنيوية لا عارضة.</p>
<p>لا يوجد طابور، فلا أحد يرى ما ينتظر. ولا توجد ملكية، فيفتح موظفان المحادثة نفسها ويرسلان ردّين مختلفين. ولا يوجد سجلّ، فحين يترك أحدهم الفريق يرحل معه كل وعد قطعه لعميل. ولا سبيل للإجابة عن أبسط سؤال إداري ممكن: كم ينتظر الناس؟</p>
<ul><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>الرسالة التي يقرأها موظف تبدو مقروءة للجميع، فتُتخطّى</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>موظفان يردّان على العميل نفسه بإجابتين متناقضتين</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>لا أحد يعرف من وعد باسترداد أو خصم أو موعد تسليم</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>سجلّ مرتبط بجهاز بدل أن يكون مرتبطًا بالشركة</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>لا أرقام لزمن الاستجابة أو الحجم يمكن الإدارة بها</span></li></ul>
<p>يعالج صندوق الوارد المشترك ذلك بتغيير وحدة العمل. فبدل تدفّق رسائل على جهاز، تحصل على <strong>محادثات لها مالك وحالة وسجلّ</strong>.</p>
</section>
<section id="how"><h2>كيف يعمل الصندوق المشترك</h2>
<p>كل رسالة واردة على رقم واتساب المتصل تصبح محادثة في قائمة واحدة يراها الفريق كله. ولا يُسنَد شيء تلقائيًا ما لم تضع قواعد توجيه — فهي تبقى افتراضيًا في مجمّع مشترك بانتظار من يستلمها.</p>
<figure><div class="shot"><img src="/img/features/inbox-full.png" alt="صندوق وارد wavadesk المشترك يعرض قائمة المحادثات ومحادثة مفتوحة ولوحة سياق العميل" loading="lazy" decoding="async" width="3186" height="1766"></div><figcaption><svg width="13" height="13" viewBox="0 0 24 24" fill="none"><rect x="2.5" y="6" width="19" height="14" rx="2.5" stroke="currentColor" stroke-width="2"/><circle cx="12" cy="13" r="3.4" stroke="currentColor" stroke-width="2"/><path d="M8.5 6l1.2-2h4.6L15.5 6" stroke="currentColor" stroke-width="2" stroke-linejoin="round"/></svg><span>الصندوق المشترك في wavadesk. القائمة الجانبية هي المجمّع الذي يراه كل موظف؛ واللوحة المقابلة تحمل سياق العميل للمحادثة المفتوحة.</span></figcaption></figure>
<p>تقابل اللوحات الثلاث الأسئلة الثلاثة التي تشغل الموظف في أي لحظة: ما الذي ينتظر، وعلى ماذا أردّ، ومع من أتحدّث. وتخبرك شارة القناة على كل صورة إن كانت المحادثة وصلت عبر واتساب أم عبر أداة الموقع، فيحمل طابور واحد القناتين دون لبس.</p>
<div class="cards"><div class="fc"><div class="ic"><svg width="19" height="19" viewBox="0 0 24 24" fill="none"><path d="M21 11.5a8.4 8.4 0 01-9 8.4 8.9 8.9 0 01-3.9-.9L3 20.5l1.5-4.6A8.4 8.4 0 013.6 11.5a8.4 8.4 0 018.4-8.4 8.4 8.4 0 019 8.4z" stroke="#0f7e7a" stroke-width="2" stroke-linejoin="round"/></svg></div><div class="h">مجمّع واحد، لا صناديق متعددة</div><p>تصل كل محادثة من كل قناة متصلة إلى القائمة نفسها، ويمكن تصفيتها حسب القناة والحالة والمسؤول.</p></div><div class="fc"><div class="ic"><svg width="19" height="19" viewBox="0 0 24 24" fill="none"><rect x="4.5" y="10.5" width="15" height="10" rx="2.2" stroke="#0f7e7a" stroke-width="2"/><path d="M8 10.5V7a4 4 0 018 0v3.5" stroke="#0f7e7a" stroke-width="2" stroke-linecap="round"/></svg></div><div class="h">استلمها لتعمل عليها</div><p>يستلم الموظف المحادثة فتُقفَل باسمه. والقفل مطبَّق على مستوى قاعدة البيانات لا في الواجهة فقط.</p></div><div class="fc"><div class="ic"><svg width="19" height="19" viewBox="0 0 24 24" fill="none"><path d="M4 4h16v12l-4 4H4z" stroke="#0f7e7a" stroke-width="2" stroke-linejoin="round"/><path d="M8 9h8M8 13h5" stroke="#0f7e7a" stroke-width="2" stroke-linecap="round"/></svg></div><div class="h">ملاحظات داخلية</div><p>الملاحظات ظاهرة لفريقك ولا تُرسَل إلى العميل أبدًا، فينتقل السياق مع المحادثة.</p></div><div class="fc"><div class="ic"><svg width="19" height="19" viewBox="0 0 24 24" fill="none"><circle cx="12" cy="12" r="9" stroke="#0f7e7a" stroke-width="2"/><path d="M12 7v5.4l3.4 2" stroke="#0f7e7a" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/></svg></div><div class="h">الحالة والسجلّ</div><p>مفتوحة، مستلَمة، محلولة، أُعيد فتحها. ولكل تغيّر في الحالة ختم زمني واسم مقابله.</p></div></div>
</section>
<section id="claim"><h2>قفل الاستلام ولماذا يهمّ</h2>
<p>أسوأ لحظة في الدعم المشترك هي أن يردّ شخصان على العميل نفسه. وهي أسوأ من ردّ بطيء، لأن العميل صار لديه إجابتان ولا يعرف أيهما الصحيحة — وعلى فريقك أن يفكّ الاشتباك أمامه.</p>
<p>يمنع wavadesk ذلك بنيويًا لا اجتماعيًا. فحين يستلم موظف محادثة، يُكتَب الاستلام قفلًا. والموظف الثاني الذي يفتح المحادثة نفسها يراها مستلَمة ولا يستطيع أخذها ولا الإرسال فيها. لا سباق زمني يُخسَر، ولا عُرف قد ينساه فريق مضغوط.</p>
<div class="note"><svg width="17" height="17" viewBox="0 0 24 24" fill="none"><circle cx="12" cy="12" r="9" stroke="#0f7e7a" stroke-width="2"/><path d="M12 11v5" stroke="#0f7e7a" stroke-width="2" stroke-linecap="round"/><circle cx="12" cy="7.8" r="1.1" fill="#0f7e7a"/></svg><div class="m"><div class="h">الاستلام قابل للتراجع</div><p>يستطيع الموظف إعادة المحادثة إلى المجمّع، ويستطيع المشرف إعادة إسنادها. القفل يمنع التصادم العرضي لا التسليم المقصود.</p></div></div>
<p>وحين يُعاد استلام أو يُعاد إسناده، يُسجَّل ذلك أيضًا. وعلى مدى أسبوع ترى لا من أجاب عن ماذا فحسب، بل أين انتقل العمل بين الأشخاص — وهناك عادةً تختبئ التأخيرات.</p>
</section>
<section id="context"><h2>عميل واحد، سجلّ واحد</h2>
<p>لا تفيد المحادثة إلا بالسجلّ الذي خلفها. وحين يراسلك عميل للمرة الرابعة هذا الشهر، لا ينبغي أن يطلب منه الموظف شرح وضعه من جديد.</p>
<p>تُفتَح كل محادثة ومعها سجلّ العميل السابق كاملًا، أيًّا كان الموظف الذي تعامل مع تلك المراسلات أو القناة التي وصلت عبرها. فإن سأل أحدهم عبر أداة موقعك في أغسطس ثم راسلك على واتساب في سبتمبر، فهو سجلّ واحد لا اثنان.</p>
<h3>ما الذي ينتقل مع العميل</h3>
<ul><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>كل محادثة سابقة على أي قناة متصلة</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>الوسوم التي أضفتها، للتقسيم والتصفية</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>الملاحظات الداخلية التي تركها فريقك على محادثات سابقة</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>سجلّ الإسناد وحالة الحل</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>مراجع الطلبات أو الحجوزات، حيثما ربطتها</span></li></ul>
</section>
<section id="audit"><h2>كل إجراء منسوب إلى صاحبه</h2>
<p>نزاعات الدعم لا تدور غالبًا حول ما قاله العميل، بل حول ما قاله فريقك. وسجلّ التدقيق يحوّل ذلك من جدال إلى عملية بحث.</p>
<p>يسجّل wavadesk من استلم المحادثة، ومن ردّ، وما الذي أُرسل، ومتى تغيّرت الحالات، وأي ملاحظات أُضيفت، وأين تصرّف الذكاء الاصطناعي وحده. لا شيء مجهول ولا شيء قابل للتعديل بصمت.</p>
<p>ويهمّ ذلك في ثلاث حالات عملية: عميل يصرّ على أنه وُعد بشيء، وموظف جديد يحتاج إلى فهم كيف عولجت حالة، ومدير يريد أن يرى هل يُتّبع إجراء ما فعلًا أم أنه قائم على الورق فقط.</p>
</section>
<section id="setup"><h2>ربط الرقم</h2>
<p>الإعداد قصير عن قصد، لأن أداة دعم تستغرق أسبوعًا للتركيب لا تُركَّب أبدًا.</p>
<div class="steps"><div class="step"><span class="n">1</span><div class="m"><div class="h">امسح رمز QR</div><p>اربط رقم واتساب بيزنس الحالي بالطريقة نفسها التي تربط بها واتساب ويب. بلا ترحيل للرقم، ودون أي تغيير بالنسبة لعملائك.</p></div></div><div class="step"><span class="n">2</span><div class="m"><div class="h">ادعُ موظفيك</div><p>أضف الأشخاص الذين سيردّون، وضعهم في فرق إن أردت التوجيه حسب القسم.</p></div></div><div class="step"><span class="n">3</span><div class="m"><div class="h">الصق أسئلتك الشائعة</div><p>امنح وكيل الذكاء الاصطناعي ما يجيب منه. هذه خطوة اختيارية في البداية ويمكن إضافتها لاحقًا.</p></div></div><div class="step"><span class="n">4</span><div class="m"><div class="h">ابدأ الاستلام</div><p>تبدأ المحادثات بالوصول إلى المجمّع المشترك فورًا. ويستلم فريقك ويردّ من المتصفح.</p></div></div></div>
<div class="note"><svg width="17" height="17" viewBox="0 0 24 24" fill="none"><circle cx="12" cy="12" r="9" stroke="#0f7e7a" stroke-width="2"/><path d="M12 11v5" stroke="#0f7e7a" stroke-width="2" stroke-linecap="round"/><circle cx="12" cy="7.8" r="1.1" fill="#0f7e7a"/></svg><div class="m"><div class="h">عملاؤك لن يلاحظوا شيئًا</div><p>يواصلون المراسلة على الرقم الذي يعرفونه. والتغيير كله في جهتك من المحادثة.</p></div></div>
</section>
<section id="who"><h2>لمن صندوق الوارد المشترك</h2>
<p>النمط ثابت: يصبح الصندوق المشترك مجديًا لحظة أن يُتوقَّع من أكثر من شخص الردّ على الرقم نفسه. دون ذلك يكفي هاتف. وفوقه يصير الهاتف عنق الزجاجة.</p>
<div class="cards"><div class="fc"><div class="ic"><svg width="19" height="19" viewBox="0 0 24 24" fill="none"><path d="M16 20v-2a4 4 0 00-4-4H6a4 4 0 00-4 4v2" stroke="#0f7e7a" stroke-width="2" stroke-linecap="round"/><circle cx="9" cy="7" r="3.4" stroke="#0f7e7a" stroke-width="2"/><path d="M22 20v-2a4 4 0 00-3-3.9" stroke="#0f7e7a" stroke-width="2" stroke-linecap="round"/></svg></div><div class="h">التجارة الإلكترونية والتجزئة</div><p>حالة الطلب ومواعيد التسليم والإرجاع والاستبدال — حجم كبير ومتكرّر في معظمه ويسهل فقدان تتبّعه.</p></div><div class="fc"><div class="ic"><svg width="19" height="19" viewBox="0 0 24 24" fill="none"><rect x="3" y="5" width="18" height="16" rx="2.6" stroke="#0f7e7a" stroke-width="2"/><path d="M3 10h18M8 3v4M16 3v4" stroke="#0f7e7a" stroke-width="2" stroke-linecap="round"/></svg></div><div class="h">العيادات والخدمات</div><p>طلبات المواعيد وإعادة الجدولة والتذكير، حيث الرسالة الفائتة تعني حجزًا ضائعًا.</p></div><div class="fc"><div class="ic"><svg width="19" height="19" viewBox="0 0 24 24" fill="none"><rect x="6" y="2.5" width="12" height="19" rx="2.6" stroke="#0f7e7a" stroke-width="2"/><path d="M11 18.5h2" stroke="#0f7e7a" stroke-width="2" stroke-linecap="round"/></svg></div><div class="h">الأعمال ذات الورديات</div><p>التسليم بين الورديات هو أشدّ ما تفشل فيه الهواتف المشتركة، وأكثر ما يفيد فيه طابور له سجلّ.</p></div><div class="fc"><div class="ic"><svg width="19" height="19" viewBox="0 0 24 24" fill="none"><path d="M4 20V10M10 20V4M16 20v-7M22 20H2" stroke="#0f7e7a" stroke-width="2" stroke-linecap="round"/></svg></div><div class="h">الفرق التي تحتاج إلى تقارير</div><p>أي عملية يكون فيها شخص مسؤولًا عن أزمنة الاستجابة بدل تخمينها.</p></div></div>
</section>
