#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# wavadesk — production worker setup
# Installs Supervisor + queue workers + Laravel scheduler cron
#
# Usage (run as root or with sudo):
#   chmod +x deploy/setup-workers.sh
#   sudo bash deploy/setup-workers.sh
# ─────────────────────────────────────────────────────────────────────────────
set -euo pipefail

# ── Config ────────────────────────────────────────────────────────────────────
# Must match the PHP-FPM / web-server user that owns storage/ and writes the logs.
# On this server that user is `www`; a mismatch makes queue jobs fail with
# "Permission denied" when opening storage/logs/*.log. Override via APP_USER=... if needed.
APP_PATH="${APP_PATH:-/www/wwwroot/public/wavadesk.com}"
APP_USER="${APP_USER:-www}"
PHP_BIN="${PHP_BIN:-$(command -v php || echo /usr/bin/php)}"
LOG_DIR="/var/log/supervisor"

echo "======================================================"
echo " wavadesk worker setup"
echo " APP_PATH : $APP_PATH"
echo " APP_USER : $APP_USER"
echo " PHP_BIN  : $PHP_BIN"
echo "======================================================"

# ── 1. Install Supervisor if missing ─────────────────────────────────────────
if ! command -v supervisorctl &>/dev/null; then
    echo "[1/5] Installing Supervisor..."
    apt-get update -qq && apt-get install -y supervisor
else
    echo "[1/5] Supervisor already installed — skipping"
fi

# ── 2. Create log directory ───────────────────────────────────────────────────
echo "[2/5] Creating log directory $LOG_DIR..."
mkdir -p "$LOG_DIR"
chown "$APP_USER":"$APP_USER" "$LOG_DIR" 2>/dev/null || true

# ── 3. Write Supervisor config ────────────────────────────────────────────────
echo "[3/5] Writing Supervisor config..."
CONF_FILE="/etc/supervisor/conf.d/wavadesk.conf"

cat > "$CONF_FILE" <<EOF
; wavadesk.com — auto-generated by deploy/setup-workers.sh

[program:wavadesk-whatsapp]
process_name=%(program_name)s_%(process_num)02d
command=$PHP_BIN $APP_PATH/artisan queue:work database --queue=whatsapp --sleep=1 --tries=3 --max-time=3600 --memory=256
directory=$APP_PATH
user=$APP_USER
numprocs=2
autostart=true
autorestart=true
stopwaitsecs=60
stopasgroup=true
killasgroup=true
redirect_stderr=true
stdout_logfile=$LOG_DIR/wavadesk-whatsapp.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=5

[program:wavadesk-default]
process_name=%(program_name)s_%(process_num)02d
command=$PHP_BIN $APP_PATH/artisan queue:work database --queue=default --sleep=3 --tries=3 --max-time=3600 --memory=256
directory=$APP_PATH
user=$APP_USER
numprocs=1
autostart=true
autorestart=true
stopwaitsecs=60
stopasgroup=true
killasgroup=true
redirect_stderr=true
stdout_logfile=$LOG_DIR/wavadesk-default.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=5

[group:wavadesk]
programs=wavadesk-whatsapp,wavadesk-default
priority=999
EOF

echo "    Written: $CONF_FILE"

# ── 4. Install Laravel scheduler cron ────────────────────────────────────────
echo "[4/5] Installing scheduler cron for $APP_USER..."
CRON_LINE="* * * * * $PHP_BIN $APP_PATH/artisan schedule:run >> /dev/null 2>&1"

# Add only if not already present
if crontab -u "$APP_USER" -l 2>/dev/null | grep -qF "artisan schedule:run"; then
    echo "    Cron already installed — skipping"
else
    (crontab -u "$APP_USER" -l 2>/dev/null; echo "$CRON_LINE") | crontab -u "$APP_USER" -
    echo "    Cron installed for user $APP_USER"
fi

# ── 5. Reload Supervisor ──────────────────────────────────────────────────────
echo "[5/5] Starting workers via Supervisor..."
systemctl enable supervisor 2>/dev/null || true
systemctl start supervisor 2>/dev/null || true
supervisorctl reread
supervisorctl update
supervisorctl start wavadesk: 2>/dev/null || supervisorctl restart wavadesk: || true

echo ""
echo "======================================================"
echo " Done! Worker status:"
supervisorctl status wavadesk:
echo ""
echo " Useful commands:"
echo "   supervisorctl status wavadesk:"
echo "   supervisorctl restart wavadesk:"
echo "   supervisorctl tail -f wavadesk-whatsapp:wavadesk-whatsapp_00"
echo "   tail -f $LOG_DIR/wavadesk-whatsapp.log"
echo "======================================================"
