{{-- Article body for /features/ai-agent.
     Copy is final, from the design handoff. Structure is the shared
     article template in features/show.blade.php; edit copy here. --}}
<section id="what"><h2>What the AI agent actually does</h2>
<p>Support volume is rarely made of hard questions. It is made of the same forty questions arriving in different words: where is my order, do you deliver on Sundays, can I change my address, what are your opening hours, how do I return something.</p>
<p>The AI agent reads an incoming message, matches it against the knowledge you have given it, and produces an answer in your wording. Depending on the mode you choose, it either hands that draft to an agent or sends it directly. Everything it does lands in the same shared inbox as human replies, tagged so you can always tell them apart.</p>
<div class="note"><svg width="17" height="17" viewBox="0 0 24 24" fill="none"><circle cx="12" cy="12" r="9" stroke="#0f7e7a" stroke-width="2"/><path d="M12 11v5" stroke="#0f7e7a" stroke-width="2" stroke-linecap="round"/><circle cx="12" cy="7.8" r="1.1" fill="#0f7e7a"/></svg><div class="m"><div class="h">It is grounded, not generative guesswork</div><p>The agent answers from your knowledge base. If the answer is not in there, it does not invent one — it escalates. See <a href="/features/knowledge-base">Knowledge base</a> for how to feed it.</p></div></div>
</section>
<section id="modes"><h2>Three modes, and when to use each</h2>
<p>The most common worry about AI support is losing control of what customers are told. wavadesk answers that with modes rather than promises: you choose how much autonomy the agent has, and you can change it at any time.</p>
<div class="cards"><div class="fc"><div class="ic"><svg width="19" height="19" viewBox="0 0 24 24" fill="none"><path d="M4 4h16v12l-4 4H4z" stroke="#0f7e7a" stroke-width="2" stroke-linejoin="round"/><path d="M8 9h8M8 13h5" stroke="#0f7e7a" stroke-width="2" stroke-linecap="round"/></svg></div><div class="h">Suggest</div><p>The AI drafts, your agent reads it, edits if needed and sends. Nothing reaches a customer without a human pressing send. Start here.</p></div><div class="fc"><div class="ic"><svg width="19" height="19" viewBox="0 0 24 24" fill="none"><path d="M4 13h6l-1 8 9-12h-6l1-8z" stroke="#0f7e7a" stroke-width="2" stroke-linejoin="round"/></svg></div><div class="h">Autonomous</div><p>The AI replies directly, without waiting for an agent. Best once you trust its answers on a defined set of topics.</p></div><div class="fc"><div class="ic"><svg width="19" height="19" viewBox="0 0 24 24" fill="none"><path d="M12 3v6M12 15v6M3 12h6M15 12h6" stroke="#0f7e7a" stroke-width="2" stroke-linecap="round"/><circle cx="12" cy="12" r="2.6" stroke="#0f7e7a" stroke-width="2"/></svg></div><div class="h">Hybrid</div><p>Autonomous on the questions you have approved, suggest-only on everything else. This is where most teams settle.</p></div><div class="fc"><div class="ic"><svg width="19" height="19" viewBox="0 0 24 24" fill="none"><path d="M12 2l8 4v6c0 5-3.4 8.8-8 10-4.6-1.2-8-5-8-10V6l8-4z" stroke="#0f7e7a" stroke-width="2" stroke-linejoin="round"/></svg></div><div class="h">Off</div><p>No AI involvement at all. The knowledge base still powers agent-facing saved replies.</p></div></div>
<h3>A sensible rollout</h3>
<ol class="numbered"><li><span>Run in suggest mode for a week and watch what it drafts. You will find gaps in your FAQ fast.</span></li><li><span>Fix those gaps. The drafts improve immediately because the source improved.</span></li><li><span>Switch the questions it consistently gets right to autonomous, and leave the rest on suggest.</span></li><li><span>Review the deflection figures monthly and widen the autonomous set as confidence grows.</span></li></ol>
<div class="note amber"><svg width="17" height="17" viewBox="0 0 24 24" fill="none"><path d="M12 8v5" stroke="#92400e" stroke-width="2.2" stroke-linecap="round"/><circle cx="12" cy="16.5" r="1.2" fill="#92400e"/><circle cx="12" cy="12" r="9" stroke="#92400e" stroke-width="2"/></svg><div class="m"><div class="h">Do not start on autonomous</div><p>Suggest mode is not a trial version — it is how you learn what your knowledge base is missing, without a customer being the one to discover it.</p></div></div>
</section>
<section id="grounding"><h2>How it stays accurate</h2>
<p>An AI support agent is only as good as what it is allowed to say. Two mechanisms keep the wavadesk agent inside the lines.</p>
<h3>It answers only from your knowledge base</h3>
<p>The agent's source of truth is the knowledge you upload: your FAQ, policies, delivery terms, opening hours, return rules. It is not answering from general world knowledge, which means it cannot confidently invent a refund policy you do not have.</p>
<h3>It escalates when it does not know</h3>
<p>When a message falls outside what your knowledge covers, or matches an escalation keyword, the agent stops and hands the conversation to a human rather than producing something plausible. Not answering is treated as the correct outcome, not a failure.</p>
<ul><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>Answers drawn from your uploaded FAQ and policies</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>Replies phrased in your tone, because your source text sets it</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>No answer invented when the knowledge is missing</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>Escalation keywords force immediate handover</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>Every automated reply logged and attributable in the audit trail</span></li></ul>
</section>
<section id="escalation"><h2>Escalation and handover</h2>
<p>The point at which AI stops is more important than the point at which it starts. A refund dispute, a complaint, a legal threat or a distressed customer should reach a person immediately, and should never sit in a loop with a bot.</p>
<p>You define escalation keywords — words and phrases that mean a human is required. When one appears, the AI withdraws from the conversation, the conversation moves into the appropriate team queue, and an agent claims it as normal. The customer is not told they have been handed over; the conversation simply continues.</p>
<h3>Typical escalation triggers</h3>
<ul><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>Complaint and dispute language: refund, chargeback, complaint, lawyer</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>Sentiment signals: repeated messages in quick succession, capitals, profanity</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>Named high-value accounts you always want handled by a person</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>Topics you have deliberately excluded from automation</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>Any question where the knowledge base returns nothing confident</span></li></ul>
<div class="note"><svg width="17" height="17" viewBox="0 0 24 24" fill="none"><circle cx="12" cy="12" r="9" stroke="#0f7e7a" stroke-width="2"/><path d="M12 11v5" stroke="#0f7e7a" stroke-width="2" stroke-linecap="round"/><circle cx="12" cy="7.8" r="1.1" fill="#0f7e7a"/></svg><div class="m"><div class="h">Escalation is instant, not queued behind the bot</div><p>The AI does not attempt one more answer before handing over. When a trigger fires, it stops.</p></div></div>
</section>
<section id="measure"><h2>Measuring whether it is working</h2>
<p>The number that matters is not how many messages the AI sent. It is how many conversations it closed without a human, and whether the ones it escalated were the right ones.</p>
<figure><div class="shot"><img src="/img/features/ai-performance.png" alt="AI performance panel showing deflection rate, median AI reply time and escalation count as a stacked bar" loading="lazy" decoding="async" width="2552" height="438"></div><figcaption><svg width="13" height="13" viewBox="0 0 24 24" fill="none"><rect x="2.5" y="6" width="19" height="14" rx="2.5" stroke="currentColor" stroke-width="2"/><circle cx="12" cy="13" r="3.4" stroke="currentColor" stroke-width="2"/><path d="M8.5 6l1.2-2h4.6L15.5 6" stroke="currentColor" stroke-width="2" stroke-linejoin="round"/></svg><span>AI performance on the dashboard: resolved without an agent, AI-assisted, and escalated — as a proportion rather than a raw message count.</span></figcaption></figure>
<p>Three figures tell you almost everything. Deflection rate is the share of conversations the AI resolved end to end. Median AI reply time shows the speed advantage over a human queue. Escalation count is your safety valve — if it drops to zero, the agent is probably answering things it should be handing over.</p>
<div class="stats"><div class="sc"><b>68%</b><span>resolved without an agent in the reference workspace</span></div><div class="sc"><b>2.4s</b><span>median AI reply time</span></div><div class="sc"><b>31</b><span>escalated to a human, deliberately</span></div></div>
<p>Full reporting is covered in <a href="/features/reports-analytics">Support reports and analytics</a>.</p>
</section>
<section id="cost"><h2>How AI usage is priced</h2>
<p>AI replies are metered as AI messages. Each plan includes a monthly allowance, and you can add packs without changing plan if a busy month runs long.</p>
<div class="tw"><table><thead><tr><th>Plan</th><th>Included AI messages</th><th>If you need more</th></tr></thead><tbody><tr><td>Starter</td><td>1,000 / month</td><td>Add 2,500-message packs</td></tr><tr><td>Growth</td><td>5,000 / month</td><td>Add 2,500-message packs</td></tr><tr><td>Scale</td><td>Unlimited</td><td>No cap, no packs needed</td></tr></tbody></table></div>
<figure><div class="shot"><img src="/img/features/usage-meters.png" alt="Usage meters showing AI messages consumed against the monthly allowance" loading="lazy" decoding="async" width="1760" height="322"></div><figcaption><svg width="13" height="13" viewBox="0 0 24 24" fill="none"><rect x="2.5" y="6" width="19" height="14" rx="2.5" stroke="currentColor" stroke-width="2"/><circle cx="12" cy="13" r="3.4" stroke="currentColor" stroke-width="2"/><path d="M8.5 6l1.2-2h4.6L15.5 6" stroke="currentColor" stroke-width="2" stroke-linejoin="round"/></svg><span>Consumption is visible in billing before you hit the ceiling, with the option to add a pack mid-cycle.</span></figcaption></figure>
<p>WhatsApp conversations themselves are always unlimited on every plan — there is no per-message fee and no Meta conversation fee. Only AI replies are metered.</p>
</section>
