{{-- Article body for /features/api-integrations.
     Copy is final, from the design handoff. Structure is the shared
     article template in features/show.blade.php; edit copy here. --}}
<section id="why"><h2>What integration is for</h2>
<p>The value of a support tool multiplies when it knows things your business already knows. An agent answering "where is my order" should not be looking up an order number in a second system — that lookup should already be on screen.</p>
<p>Integration goes both ways. You push context in, so agents and the AI can use it. And you pull events out, so your own systems react when something happens in support.</p>
<div class="cards"><div class="fc"><div class="ic"><svg width="19" height="19" viewBox="0 0 24 24" fill="none"><path d="M8 6l-5 6 5 6M16 6l5 6-5 6" stroke="#0f7e7a" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/></svg></div><div class="h">REST API</div><p>Read and write conversations, contacts, tags and messages from your own backend.</p></div><div class="fc"><div class="ic"><svg width="19" height="19" viewBox="0 0 24 24" fill="none"><path d="M4 13h6l-1 8 9-12h-6l1-8z" stroke="#0f7e7a" stroke-width="2" stroke-linejoin="round"/></svg></div><div class="h">Webhooks</div><p>Receive an event when a conversation is created, claimed, replied to, resolved or escalated.</p></div><div class="fc"><div class="ic"><svg width="19" height="19" viewBox="0 0 24 24" fill="none"><circle cx="8" cy="12" r="4.2" stroke="#0f7e7a" stroke-width="2"/><path d="M12 12h9M17 12v4" stroke="#0f7e7a" stroke-width="2" stroke-linecap="round"/></svg></div><div class="h">OTP API</div><p>Send and verify one-time passcodes over WhatsApp from your application.</p></div><div class="fc"><div class="ic"><svg width="19" height="19" viewBox="0 0 24 24" fill="none"><path d="M4 20V10M10 20V4M16 20v-7M22 20H2" stroke="#0f7e7a" stroke-width="2" stroke-linecap="round"/></svg></div><div class="h">Reporting export</div><p>Pull the metrics behind the dashboard for your own BI or data warehouse.</p></div></div>
</section>
<section id="auth"><h2>Authentication</h2>
<p>API access uses a workspace-scoped bearer token, created in settings and revocable at any time. Tokens are scoped to a workspace, so a token from one tenant cannot read another.</p>
<p>Requests are made over HTTPS to your workspace endpoint, with the token in an Authorization header. There is no separate signing step for REST calls; webhook deliveries are signed so you can verify they came from us.</p>
<ul><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>Bearer token per workspace, created and revoked in settings</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>Scoped so a token cannot read outside its workspace</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>Signed webhook payloads with a shared secret for verification</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>Rate limited per token, with limits returned in response headers</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>Every API action recorded in the same audit trail as human actions</span></li></ul>
<div class="note amber"><svg width="17" height="17" viewBox="0 0 24 24" fill="none"><path d="M12 8v5" stroke="#92400e" stroke-width="2.2" stroke-linecap="round"/><circle cx="12" cy="16.5" r="1.2" fill="#92400e"/><circle cx="12" cy="12" r="9" stroke="#92400e" stroke-width="2"/></svg><div class="m"><div class="h">Treat tokens as credentials</div><p>A workspace token can read your conversation history. Keep it server-side — never in front-end code or a mobile app binary.</p></div></div>
</section>
<section id="rest"><h2>What the REST API covers</h2>
<p>The API is organised around the same objects as the interface, so what you can see you can generally read and write.</p>
<div class="tw"><table><thead><tr><th>Resource</th><th>What you can do</th></tr></thead><tbody><tr><td>Conversations</td><td>List, filter by channel or status, read messages, create, claim, assign, resolve</td></tr><tr><td>Messages</td><td>Send into a conversation, read history, attach internal notes</td></tr><tr><td>Contacts</td><td>Create, update, look up by phone or email, merge, attach custom fields</td></tr><tr><td>Tags</td><td>Apply and remove, list by conversation or contact</td></tr><tr><td>Teams and agents</td><td>List, read availability, read assignment</td></tr><tr><td>Reports</td><td>Pull the metrics behind the dashboard for a period</td></tr><tr><td>OTP</td><td>Send a passcode, verify a passcode</td></tr></tbody></table></div>
<h3>The most common first integration</h3>
<p>Pushing customer context onto the contact record. If your system knows a customer's order history, plan or account status, writing it as custom fields on the contact means the agent sees it in the context panel without leaving the conversation.</p>
</section>
<section id="webhooks"><h2>Webhooks and events</h2>
<p>Webhooks let your systems react to support activity rather than polling for it. You register an endpoint, choose the events you care about, and we POST a signed payload when they happen.</p>
<h3>Events you can subscribe to</h3>
<ul><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>conversation.created — a new conversation arrived on any channel</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>conversation.claimed — an agent took ownership</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>conversation.resolved — marked resolved, with the resolving agent</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>conversation.escalated — the AI handed over, with the trigger</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>message.received — an inbound customer message</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>message.sent — an outbound reply, human or AI</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>contact.created and contact.updated</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>otp.verified — a passcode was successfully verified</span></li></ul>
<h3>Practical uses</h3>
<p>Three integrations cover most of what teams build. Creating a CRM activity on <code>conversation.resolved</code>, so support history appears against the account. Alerting a Slack channel on <code>conversation.escalated</code> for named accounts. Unlocking a feature in your product on <code>otp.verified</code>.</p>
<div class="note"><svg width="17" height="17" viewBox="0 0 24 24" fill="none"><circle cx="12" cy="12" r="9" stroke="#0f7e7a" stroke-width="2"/><path d="M12 11v5" stroke="#0f7e7a" stroke-width="2" stroke-linecap="round"/><circle cx="12" cy="7.8" r="1.1" fill="#0f7e7a"/></svg><div class="m"><div class="h">Deliveries are retried</div><p>A webhook that fails is retried with backoff. Respond 2xx quickly and do the work asynchronously — long processing inside the request will trip the timeout and cause duplicate deliveries.</p></div></div>
</section>
<section id="otp"><h2>The OTP endpoints</h2>
<p>Two calls, and no state to keep on your side. The passcode is generated, hashed and stored by us and is never returned to you.</p>
<div class="steps"><div class="step"><span class="n">1</span><div class="m"><div class="h">POST to send</div><p>With the phone number and an optional purpose label such as login or signup. Returns a request identifier, not the code.</p></div></div><div class="step"><span class="n">2</span><div class="m"><div class="h">Customer receives it on WhatsApp</div><p>From your connected business number.</p></div></div><div class="step"><span class="n">3</span><div class="m"><div class="h">POST to verify</div><p>With the number and the code the customer entered. Returns pass or fail.</p></div></div><div class="step"><span class="n">4</span><div class="m"><div class="h">Handle the failure reason</div><p>Failures come back distinguished: incorrect, expired, or attempt limit exceeded — so you can show the right message.</p></div></div></div>
<p>Expiry, attempt limits and per-number rate limiting are enforced server-side. Full detail in <a href="/features/otp-service">WhatsApp OTP and verification</a>.</p>
</section>
<section id="widget"><h2>Embedding and the widget</h2>
<p>The live chat widget is itself an integration point. Beyond the install snippet, you can identify the visitor from your own application so the conversation is linked to a known contact rather than an anonymous session.</p>
<p>Calling the identify method with your user's details on page load means the agent sees a named customer with full cross-channel history instead of an anonymous visitor.</p>
<figure><div class="shot"><img src="/img/features/livechat-settings.png" alt="Live chat settings screen with the install snippet and configuration options" loading="lazy" decoding="async" width="3186" height="1766"></div><figcaption><svg width="13" height="13" viewBox="0 0 24 24" fill="none"><rect x="2.5" y="6" width="19" height="14" rx="2.5" stroke="currentColor" stroke-width="2"/><circle cx="12" cy="13" r="3.4" stroke="currentColor" stroke-width="2"/><path d="M8.5 6l1.2-2h4.6L15.5 6" stroke="currentColor" stroke-width="2" stroke-linejoin="round"/></svg><span>The install snippet and widget configuration live in the same settings screen, alongside a live preview.</span></figcaption></figure>
<p>See <a href="/features/live-chat-widget">Live chat widget</a> for installation and branding.</p>
</section>
<section id="limits"><h2>Limits and versioning</h2>
<p>Two things you want to know before building against any API: how hard you can push it, and whether it will change under you.</p>
<ul><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>Rate limits per token, with remaining quota returned in response headers</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>429 responses include a retry-after value</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>Breaking changes ship behind a version, and existing versions remain supported</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>Additive changes — new fields and new event types — can arrive without a version bump, so parse defensively</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>Webhook payloads are versioned alongside the API</span></li></ul>
<p>API access is included on the Scale plan. See <a href="{{ url('/#pricing') }}">pricing</a>.</p>
</section>
