{{-- Article body for /features/knowledge-base.
     Copy is final, from the design handoff. Structure is the shared
     article template in features/show.blade.php; edit copy here. --}}
<section id="why"><h2>Why a single source matters</h2>
<p>Every support team has an unwritten knowledge base: the answers live in the heads of the two people who have been there longest. It works until one of them is on holiday, or a new agent joins, or two agents give a customer different versions of the return policy in the same week.</p>
<p>Writing it down is not the hard part. Keeping one version of it is. The failure mode is not an empty knowledge base — it is three of them: a document for onboarding, a set of snippets in someone's notes, and whatever the AI was configured with six months ago.</p>
<p>In wavadesk there is one store, and it feeds three consumers: <strong>the AI agent</strong>, which answers from it; <strong>saved replies</strong>, which your agents insert; and eventually self-serve content, so customers can find answers without messaging at all. Update the source and all three change.</p>
<div class="cards"><div class="fc"><div class="ic"><svg width="19" height="19" viewBox="0 0 24 24" fill="none"><path d="M13 2 4 14h6l-1 8 9-12h-6l1-8z" fill="#0f7e7a"/></svg></div><div class="h">Feeds the AI</div><p>The agent answers only from this material, in your wording, and escalates when it is not covered.</p></div><div class="fc"><div class="ic"><svg width="19" height="19" viewBox="0 0 24 24" fill="none"><path d="M4 4h16v12l-4 4H4z" stroke="#0f7e7a" stroke-width="2" stroke-linejoin="round"/><path d="M8 9h8M8 13h5" stroke="#0f7e7a" stroke-width="2" stroke-linecap="round"/></svg></div><div class="h">Feeds saved replies</div><p>Agents insert the canonical answer instead of retyping an approximation.</p></div><div class="fc"><div class="ic"><svg width="19" height="19" viewBox="0 0 24 24" fill="none"><circle cx="11" cy="11" r="7" stroke="#0f7e7a" stroke-width="2"/><path d="M20 20l-3.5-3.5" stroke="#0f7e7a" stroke-width="2" stroke-linecap="round"/></svg></div><div class="h">Searchable by agents</div><p>When someone needs the exact policy wording mid-conversation, it is one search away.</p></div><div class="fc"><div class="ic"><svg width="19" height="19" viewBox="0 0 24 24" fill="none"><path d="M12 2l8 4v6c0 5-3.4 8.8-8 10-4.6-1.2-8-5-8-10V6l8-4z" stroke="#0f7e7a" stroke-width="2" stroke-linejoin="round"/></svg></div><div class="h">Auditable</div><p>One version, with a history of what changed and when — which matters when a policy is disputed.</p></div></div>
</section>
<section id="structure"><h2>How to structure it</h2>
<p>The instinct is to write long articles. Resist it. The AI matches on questions, and agents insert answers — both work better with short, single-topic entries than with a comprehensive policy document.</p>
<h3>One question, one entry</h3>
<p>An entry should answer exactly one thing. "What are your delivery times" and "Do you deliver on Sundays" are two entries even though both are about delivery, because a customer asks them separately and the answers differ.</p>
<h3>Write the answer as you would send it</h3>
<p>The AI uses your text as the basis for its reply, so the tone of your knowledge base becomes the tone of your automated support. Write entries as messages to a customer, not as internal documentation.</p>
<div class="tw"><table><thead><tr><th>Do</th><th>Do not</th></tr></thead><tbody><tr><td>"Standard delivery is 3 to 5 business days. Express arrives within 24 hours."</td><td>"DELIVERY POLICY: Refer to logistics SLA section 4.2."</td></tr><tr><td>One entry per question</td><td>One entry covering all shipping topics</td></tr><tr><td>Plain language a customer reads</td><td>Internal jargon and system names</td></tr><tr><td>State the exception in the same entry</td><td>Leave the edge case for the agent to remember</td></tr></tbody></table></div>
<h3>Cover the exceptions explicitly</h3>
<p>Most escalations are not unusual questions, they are the exception to a common question. If Sunday delivery is unavailable except in two cities, write that in the entry. An entry that is right 90% of the time trains your team to distrust the whole base.</p>
</section>
<section id="ai"><h2>How the AI uses it</h2>
<p>When a message arrives, the agent matches it against your entries and drafts a reply grounded in the ones that fit. It is not answering from general world knowledge, which is why it cannot invent a refund window you do not offer.</p>
<p>When nothing matches confidently, the agent escalates rather than improvising. That makes your knowledge base the direct lever on automation rate: every gap you close converts a category of escalation into an automated answer.</p>
<div class="note"><svg width="17" height="17" viewBox="0 0 24 24" fill="none"><circle cx="12" cy="12" r="9" stroke="#0f7e7a" stroke-width="2"/><path d="M12 11v5" stroke="#0f7e7a" stroke-width="2" stroke-linecap="round"/><circle cx="12" cy="7.8" r="1.1" fill="#0f7e7a"/></svg><div class="m"><div class="h">Suggest mode is a gap-finding tool</div><p>Run the AI in suggest mode for a week and read what it drafts. Where the drafts are weak, your knowledge base is thin — this is far cheaper than discovering it through a customer.</p></div></div>
<figure><div class="shot"><img src="/img/features/ai-performance.png" alt="AI performance panel showing deflection rate and escalation counts" loading="lazy" decoding="async" width="2552" height="438"></div><figcaption><svg width="13" height="13" viewBox="0 0 24 24" fill="none"><rect x="2.5" y="6" width="19" height="14" rx="2.5" stroke="currentColor" stroke-width="2"/><circle cx="12" cy="13" r="3.4" stroke="currentColor" stroke-width="2"/><path d="M8.5 6l1.2-2h4.6L15.5 6" stroke="currentColor" stroke-width="2" stroke-linejoin="round"/></svg><span>Deflection rate is the practical measure of knowledge base coverage. It rises as gaps close.</span></figcaption></figure>
</section>
<section id="saved"><h2>Saved replies for agents</h2>
<p>Even with AI handling the common path, agents type a lot of near-identical messages: asking for an order number, explaining a returns process, confirming an address change. Saved replies make those one insertion instead of one composition.</p>
<ul><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>Insert a canonical answer into the composer with a keyboard shortcut</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>Edit before sending, because the surrounding conversation always needs a sentence of its own</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>Placeholders for customer name and order reference, filled from the conversation</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>Organised by team, so billing snippets do not clutter the sales queue</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>Same source as the AI, so an agent and the bot never contradict each other</span></li></ul>
<p>The discipline that matters: when an agent finds themselves editing the same saved reply the same way repeatedly, that edit belongs in the source. Otherwise you have re-created the scattered-knowledge problem inside the tool.</p>
</section>
<section id="maintain"><h2>Keeping it current</h2>
<p>A knowledge base decays. Prices change, policies change, a product is discontinued and the entry describing it quietly becomes wrong. Nothing in the tool prevents that — only a review habit does.</p>
<div class="steps"><div class="step"><span class="n">1</span><div class="m"><div class="h">Review escalations weekly</div><p>Escalations are your gap list. A recurring escalation on the same topic is a missing or wrong entry.</p></div></div><div class="step"><span class="n">2</span><div class="m"><div class="h">Watch which saved replies get edited</div><p>Consistent edits mean the canonical wording is out of date.</p></div></div><div class="step"><span class="n">3</span><div class="m"><div class="h">Update at the source of change</div><p>When a policy changes, the knowledge base entry is part of shipping that change, not a follow-up task.</p></div></div><div class="step"><span class="n">4</span><div class="m"><div class="h">Prune what is dead</div><p>A wrong entry is worse than a missing one, because the AI will confidently use it.</p></div></div></div>
<div class="note amber"><svg width="17" height="17" viewBox="0 0 24 24" fill="none"><path d="M12 8v5" stroke="#92400e" stroke-width="2.2" stroke-linecap="round"/><circle cx="12" cy="16.5" r="1.2" fill="#92400e"/><circle cx="12" cy="12" r="9" stroke="#92400e" stroke-width="2"/></svg><div class="m"><div class="h">One owner, not everyone</div><p>Knowledge bases rot fastest when nobody owns them and everyone can edit. Give one person final say on wording, with the team feeding suggestions.</p></div></div>
</section>
