{{-- Article body for /features/live-chat-widget.
     Copy is final, from the design handoff. Structure is the shared
     article template in features/show.blade.php; edit copy here. --}}
<section id="why"><h2>Why one inbox for both channels</h2>
<p>Adding live chat to a website is easy. Adding it without fragmenting your support operation is the hard part. The usual outcome is two tools, two queues and two sets of history, with agents alt-tabbing between them and nobody able to report on the whole.</p>
<p>wavadesk treats channel as an attribute of a conversation, not as a separate product. A website chat and a WhatsApp thread appear in the same list, are claimed the same way, and are answered from the same composer. The only difference is a badge telling the agent where it came from.</p>
<figure><div class="shot"><img src="/img/features/inbox-full.png" alt="Shared inbox showing both WhatsApp and Live Chat conversations in one list with channel badges" loading="lazy" decoding="async" width="3186" height="1766"></div><figcaption><svg width="13" height="13" viewBox="0 0 24 24" fill="none"><rect x="2.5" y="6" width="19" height="14" rx="2.5" stroke="currentColor" stroke-width="2"/><circle cx="12" cy="13" r="3.4" stroke="currentColor" stroke-width="2"/><path d="M8.5 6l1.2-2h4.6L15.5 6" stroke="currentColor" stroke-width="2" stroke-linejoin="round"/></svg><span>WhatsApp and website conversations in one queue. The badge on each avatar is the only thing distinguishing them.</span></figcaption></figure>
<div class="cards"><div class="fc"><div class="ic"><svg width="19" height="19" viewBox="0 0 24 24" fill="none"><path d="M21 11.5a8.4 8.4 0 01-9 8.4 8.9 8.9 0 01-3.9-.9L3 20.5l1.5-4.6A8.4 8.4 0 013.6 11.5a8.4 8.4 0 018.4-8.4 8.4 8.4 0 019 8.4z" stroke="#0f7e7a" stroke-width="2" stroke-linejoin="round"/></svg></div><div class="h">One queue</div><p>Filter by channel when you want to, but nothing is hidden in a second tool.</p></div><div class="fc"><div class="ic"><svg width="19" height="19" viewBox="0 0 24 24" fill="none"><path d="M16 20v-2a4 4 0 00-4-4H6a4 4 0 00-4 4v2" stroke="#0f7e7a" stroke-width="2" stroke-linecap="round"/><circle cx="9" cy="7" r="3.4" stroke="#0f7e7a" stroke-width="2"/><path d="M22 20v-2a4 4 0 00-3-3.9" stroke="#0f7e7a" stroke-width="2" stroke-linecap="round"/></svg></div><div class="h">One customer</div><p>A visitor who later messages on WhatsApp keeps the same history, not a fresh start.</p></div><div class="fc"><div class="ic"><svg width="19" height="19" viewBox="0 0 24 24" fill="none"><path d="M13 2 4 14h6l-1 8 9-12h-6l1-8z" fill="#0f7e7a"/></svg></div><div class="h">One AI agent</div><p>The same knowledge base answers on both channels, so answers cannot diverge.</p></div><div class="fc"><div class="ic"><svg width="19" height="19" viewBox="0 0 24 24" fill="none"><path d="M4 20V10M10 20V4M16 20v-7M22 20H2" stroke="#0f7e7a" stroke-width="2" stroke-linecap="round"/></svg></div><div class="h">One set of numbers</div><p>Response time and volume reported across channels and per channel.</p></div></div>
</section>
<section id="install"><h2>Installing the widget</h2>
<p>Installation is a single script tag before the closing body tag of your site. There is no build step and no framework requirement — it works on a static site, WordPress, Shopify, a Laravel app or anything else that serves HTML.</p>
<div class="steps"><div class="step"><span class="n">1</span><div class="m"><div class="h">Copy the snippet</div><p>Your workspace generates a snippet containing your unique widget key.</p></div></div><div class="step"><span class="n">2</span><div class="m"><div class="h">Paste it into your site</div><p>Before the closing body tag, on every page you want chat available. Most teams add it to a shared layout or footer template.</p></div></div><div class="step"><span class="n">3</span><div class="m"><div class="h">Confirm it connects</div><p>Open your site, send a test message and watch it appear in the shared inbox.</p></div></div><div class="step"><span class="n">4</span><div class="m"><div class="h">Set your behaviour</div><p>Choose greeting, position, hours and whether AI answers first.</p></div></div></div>
<figure><div class="shot"><img src="/img/features/livechat-settings.png" alt="Live chat settings screen with widget configuration and a live preview panel" loading="lazy" decoding="async" width="3186" height="1766"></div><figcaption><svg width="13" height="13" viewBox="0 0 24 24" fill="none"><rect x="2.5" y="6" width="19" height="14" rx="2.5" stroke="currentColor" stroke-width="2"/><circle cx="12" cy="13" r="3.4" stroke="currentColor" stroke-width="2"/><path d="M8.5 6l1.2-2h4.6L15.5 6" stroke="currentColor" stroke-width="2" stroke-linejoin="round"/></svg><span>The settings screen carries a live preview, so you see the effect of every change before publishing it.</span></figcaption></figure>
<div class="note"><svg width="17" height="17" viewBox="0 0 24 24" fill="none"><circle cx="12" cy="12" r="9" stroke="#0f7e7a" stroke-width="2"/><path d="M12 11v5" stroke="#0f7e7a" stroke-width="2" stroke-linecap="round"/><circle cx="12" cy="7.8" r="1.1" fill="#0f7e7a"/></svg><div class="m"><div class="h">No customer install required</div><p>Website visitors need nothing. The widget loads on your page and the conversation starts there.</p></div></div>
</section>
<section id="customise"><h2>Branding and behaviour</h2>
<p>The widget should look like it belongs to your site, not to a support vendor. Everything visitor-facing is configurable, with a live preview beside the controls.</p>
<h3>What you can change</h3>
<ul><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>Accent colour, so the launcher matches your brand</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>Launcher position, left or right, with an offset for other floating elements</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>Greeting text and a short intro line, per language</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>Availability hours, and what the widget says outside them</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>Whether the AI agent answers first or the conversation waits for a person</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>Pre-chat fields, if you want a name or email before the conversation starts</span></li></ul>
<h3>Multi-language</h3>
<p>Widget copy can be set per language, so a French visitor sees French and an Arabic visitor sees Arabic. The AI agent answers in the language the visitor writes in, drawing on the same knowledge base.</p>
</section>
<section id="context"><h2>Visitor context your agents can use</h2>
<p>A website visitor is anonymous by default, which sounds like a disadvantage until you notice how much the session itself tells you. Someone on your pricing page for four minutes is asking a different question from someone who just landed on the homepage.</p>
<p>The context panel shows the session rather than a contact record: the page they are on, how they arrived, browser and device, how long they have been on the site and which pages they visited on the way.</p>
<ul><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>Current page, so the agent knows what the visitor is looking at</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>Page journey, which usually reveals intent better than the first message</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>Browser, device and operating system, for troubleshooting</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>Referrer, so you know whether they came from an ad or a search</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>Time on site and session start</span></li></ul>
<p>If the visitor identifies themselves — through a pre-chat field, or by giving an email in conversation — the session is linked to a contact and their history from other channels appears.</p>
</section>
<section id="ai"><h2>AI on the widget</h2>
<p>Website chat has a different expectation from WhatsApp. A visitor sitting on your pricing page expects an answer in seconds, and will close the tab rather than wait. This is where autonomous AI earns the most.</p>
<p>The same AI agent, the same knowledge base and the same escalation rules apply. You can, however, set a different mode per channel: many teams run autonomous on the widget for instant answers and suggest-only on WhatsApp, where a slightly slower human reply is acceptable.</p>
<div class="note"><svg width="17" height="17" viewBox="0 0 24 24" fill="none"><circle cx="12" cy="12" r="9" stroke="#0f7e7a" stroke-width="2"/><path d="M12 11v5" stroke="#0f7e7a" stroke-width="2" stroke-linecap="round"/><circle cx="12" cy="7.8" r="1.1" fill="#0f7e7a"/></svg><div class="m"><div class="h">Escalation still applies</div><p>A visitor asking about a refund or using a trigger word is handed to a human on the widget exactly as they would be on WhatsApp.</p></div></div>
<p>More detail in <a href="/features/ai-agent">AI agent for support</a>.</p>
</section>
<section id="perf"><h2>Performance and privacy</h2>
<p>A chat widget is on every page of your site, so its weight is your weight. The wavadesk widget loads asynchronously and does not block rendering — the launcher appears after your page is interactive, not before.</p>
<ul><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>Asynchronous load, no render blocking</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>No third-party advertising or tracking pixels bundled in</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>Session data limited to what the context panel shows</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>Conversations stored in your workspace, not shared across tenants</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>Widget respects your availability hours instead of implying someone is there</span></li></ul>
</section>
