{{-- Article body for /features/otp-service.
     Copy is final, from the design handoff. Structure is the shared
     article template in features/show.blade.php; edit copy here. --}}
<section id="what"><h2>What the OTP service does</h2>
<p>One-time passcodes are the workhorse of account security: sign-up confirmation, login verification, password reset, confirming a high-value transaction, verifying a phone number before delivery. Almost every product needs them, and almost every product sends them over SMS by default.</p>
<p>The wavadesk OTP module sends those codes over WhatsApp instead. You call an endpoint with a phone number, we deliver a passcode message, and you verify the code the customer types back through a second call. Delivery, expiry and attempt limits are handled for you.</p>
<div class="cards"><div class="fc"><div class="ic"><svg width="19" height="19" viewBox="0 0 24 24" fill="none"><circle cx="8" cy="12" r="4.2" stroke="#0f7e7a" stroke-width="2"/><path d="M12 12h9M17 12v4" stroke="#0f7e7a" stroke-width="2" stroke-linecap="round"/></svg></div><div class="h">Generate and send</div><p>One request creates a code, stores it hashed and delivers it to the customer's WhatsApp.</p></div><div class="fc"><div class="ic"><svg width="19" height="19" viewBox="0 0 24 24" fill="none"><path d="M12 2l8 4v6c0 5-3.4 8.8-8 10-4.6-1.2-8-5-8-10V6l8-4z" stroke="#0f7e7a" stroke-width="2" stroke-linejoin="round"/></svg></div><div class="h">Verify</div><p>A second request checks the code the customer entered, with attempt limits and expiry enforced.</p></div><div class="fc"><div class="ic"><svg width="19" height="19" viewBox="0 0 24 24" fill="none"><circle cx="12" cy="12" r="9" stroke="#0f7e7a" stroke-width="2"/><path d="M12 7v5.4l3.4 2" stroke="#0f7e7a" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/></svg></div><div class="h">Expiry handling</div><p>Codes expire on a window you set. Expired codes fail closed rather than lingering.</p></div><div class="fc"><div class="ic"><svg width="19" height="19" viewBox="0 0 24 24" fill="none"><path d="M4 20V10M10 20V4M16 20v-7M22 20H2" stroke="#0f7e7a" stroke-width="2" stroke-linecap="round"/></svg></div><div class="h">Delivery reporting</div><p>Sent, delivered and verified counts, so you can see funnel drop-off rather than guess at it.</p></div></div>
</section>
<section id="why"><h2>Why WhatsApp beats SMS for verification</h2>
<p>This is not a preference argument. There are four concrete operational differences.</p>
<h3>Delivery you can actually confirm</h3>
<p>SMS gives you a submission receipt from an aggregator, not proof a human saw it. WhatsApp gives delivery and read status, so when a customer says the code never arrived you can check rather than speculate.</p>
<h3>Cost per verification</h3>
<p>SMS is priced per message per country, and international verification costs add up quickly. WhatsApp conversations on wavadesk are unlimited on every plan, so the marginal cost of an additional verification is zero.</p>
<h3>It arrives where the conversation already is</h3>
<p>If your customer already messages you on WhatsApp, the code appears in a thread they recognise, from a sender they have talked to before. That materially reduces the phishing suspicion that unknown SMS shortcodes create.</p>
<h3>No shortcode or sender-ID approvals</h3>
<p>SMS sender registration varies by country and can take weeks. Your WhatsApp number is already connected and already yours.</p>
<div class="tw"><table><thead><tr><th></th><th>SMS</th><th>WhatsApp via wavadesk</th></tr></thead><tbody><tr><td>Cost per message</td><td>Per message, per country</td><td>Included — unlimited conversations</td></tr><tr><td>Delivery confirmation</td><td>Submission receipt only</td><td>Delivered and read status</td></tr><tr><td>Sender recognition</td><td>Unknown shortcode</td><td>Your existing business number</td></tr><tr><td>Setup</td><td>Sender ID / shortcode approval</td><td>Already connected by QR</td></tr><tr><td>Rich content</td><td>160 characters, plain</td><td>Formatting and branding available</td></tr></tbody></table></div>
<div class="note amber"><svg width="17" height="17" viewBox="0 0 24 24" fill="none"><path d="M12 8v5" stroke="#92400e" stroke-width="2.2" stroke-linecap="round"/><circle cx="12" cy="16.5" r="1.2" fill="#92400e"/><circle cx="12" cy="12" r="9" stroke="#92400e" stroke-width="2"/></svg><div class="m"><div class="h">Keep an SMS fallback for coverage</div><p>A small share of customers will not have WhatsApp. Most teams send over WhatsApp first and fall back to SMS on non-delivery — the module reports non-delivery so you can trigger that.</p></div></div>
</section>
<section id="how"><h2>How it works in practice</h2>
<p>Two endpoints, and no state for you to keep. The code itself is generated, hashed and stored on our side; you never hold it.</p>
<div class="steps"><div class="step"><span class="n">1</span><div class="m"><div class="h">Request a code</div><p>Your backend calls the send endpoint with the customer's phone number and an optional purpose label such as login or signup.</p></div></div><div class="step"><span class="n">2</span><div class="m"><div class="h">Customer receives it on WhatsApp</div><p>The message arrives from your connected business number, in the language you specify.</p></div></div><div class="step"><span class="n">3</span><div class="m"><div class="h">Customer enters the code</div><p>In your app, site or checkout — wherever the verification is happening.</p></div></div><div class="step"><span class="n">4</span><div class="m"><div class="h">Your backend verifies</div><p>Call the verify endpoint with the number and the code. You get a pass or fail, with the reason on failure: wrong, expired, or too many attempts.</p></div></div></div>
<div class="note"><svg width="17" height="17" viewBox="0 0 24 24" fill="none"><circle cx="12" cy="12" r="9" stroke="#0f7e7a" stroke-width="2"/><path d="M12 11v5" stroke="#0f7e7a" stroke-width="2" stroke-linecap="round"/><circle cx="12" cy="7.8" r="1.1" fill="#0f7e7a"/></svg><div class="m"><div class="h">Codes are never returned to you</div><p>The send call does not hand back the passcode. Verification happens through the verify endpoint, so a leak in your logs cannot expose live codes.</p></div></div>
<p>Full request and response shapes are in <a href="/features/api-integrations">API and integrations</a>.</p>
</section>
<section id="security"><h2>Security controls</h2>
<p>An OTP system is a security control, so its own defaults matter. These are enforced rather than optional.</p>
<ul><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>Codes stored hashed, never in plain text, and never returned by the send endpoint</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>Configurable expiry window, defaulting to a short lifetime</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>Attempt limits per code, after which the code is burned and a new one must be requested</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>Rate limiting per phone number, so an attacker cannot use your endpoint to spam a victim</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>Rate limiting per API key, to contain a leaked credential</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>Single-use codes — a verified code cannot be replayed</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>Full audit record of every send and verify attempt with timestamps</span></li></ul>
<h3>Abuse you should think about</h3>
<p>The main risk with any OTP endpoint is not code guessing, it is being used as a free messaging cannon against someone else's phone. Per-number rate limits are the defence, and they are on by default. If you expose a public sign-up form, keep a captcha or equivalent in front of the send call as well.</p>
</section>
<section id="reporting"><h2>Delivery and conversion reporting</h2>
<p>Verification is a funnel, and funnels leak. The reporting surface shows sends, deliveries and successful verifications so you can see where.</p>
<figure><div class="shot"><img src="/img/features/kpis.png" alt="Dashboard metric cards with sparklines and period-over-period deltas" loading="lazy" decoding="async" width="2552" height="370"></div><figcaption><svg width="13" height="13" viewBox="0 0 24 24" fill="none"><rect x="2.5" y="6" width="19" height="14" rx="2.5" stroke="currentColor" stroke-width="2"/><circle cx="12" cy="13" r="3.4" stroke="currentColor" stroke-width="2"/><path d="M8.5 6l1.2-2h4.6L15.5 6" stroke="currentColor" stroke-width="2" stroke-linejoin="round"/></svg><span>OTP delivery and verification counts appear as metrics with trend lines in the same reporting surface as conversation volume.</span></figcaption></figure>
<p>The gap between delivered and verified is the number worth watching. A wide gap usually means one of three things: your code entry screen is confusing, your expiry window is too short for real users, or you are verifying at a point in the journey where people abandon anyway.</p>
<div class="stats"><div class="sc"><b>Sent</b><span>codes requested by your backend</span></div><div class="sc"><b>Delivered</b><span>confirmed as arrived on the handset</span></div><div class="sc"><b>Verified</b><span>codes correctly entered by the customer</span></div></div>
</section>
<section id="cases"><h2>Where teams use it</h2>
<div class="cards"><div class="fc"><div class="ic"><svg width="19" height="19" viewBox="0 0 24 24" fill="none"><path d="M12 2l8 4v6c0 5-3.4 8.8-8 10-4.6-1.2-8-5-8-10V6l8-4z" stroke="#0f7e7a" stroke-width="2" stroke-linejoin="round"/></svg></div><div class="h">Login and sign-up</div><p>Confirming a phone number at account creation, and step-up verification at login.</p></div><div class="fc"><div class="ic"><svg width="19" height="19" viewBox="0 0 24 24" fill="none"><circle cx="8" cy="12" r="4.2" stroke="#0f7e7a" stroke-width="2"/><path d="M12 12h9M17 12v4" stroke="#0f7e7a" stroke-width="2" stroke-linecap="round"/></svg></div><div class="h">Password reset</div><p>A code to a verified number, without relying on email deliverability.</p></div><div class="fc"><div class="ic"><svg width="19" height="19" viewBox="0 0 24 24" fill="none"><rect x="3" y="5" width="18" height="16" rx="2.6" stroke="#0f7e7a" stroke-width="2"/><path d="M3 10h18M8 3v4M16 3v4" stroke="#0f7e7a" stroke-width="2" stroke-linecap="round"/></svg></div><div class="h">Booking confirmation</div><p>Verifying the number before a reservation is held, which cuts fake bookings.</p></div><div class="fc"><div class="ic"><svg width="19" height="19" viewBox="0 0 24 24" fill="none"><rect x="6" y="2.5" width="12" height="19" rx="2.6" stroke="#0f7e7a" stroke-width="2"/><path d="M11 18.5h2" stroke="#0f7e7a" stroke-width="2" stroke-linecap="round"/></svg></div><div class="h">Delivery confirmation</div><p>Confirming the recipient's number before dispatch, reducing failed deliveries.</p></div></div>
<p>The OTP module is included on the Scale plan and available as an add-on to others. See <a href="{{ url('/#pricing') }}">pricing</a>.</p>
</section>
