{{-- Article body for /features/reports-analytics.
     Copy is final, from the design handoff. Structure is the shared
     article template in features/show.blade.php; edit copy here. --}}
<section id="why"><h2>Why a shared phone gives you nothing</h2>
<p>A shared handset produces no data. You cannot see how long people waited, how many conversations you handled last Tuesday, which agent carried the load, or whether last month was better than the one before. You have the impression of whoever was closest to the phone.</p>
<p>This matters beyond curiosity. Without figures you cannot answer three operational questions: are we fast enough, are we staffed correctly, and is the thing we changed last month working. Every improvement becomes an argument about anecdotes.</p>
<figure><div class="shot"><img src="/img/features/dashboard-overview.png" alt="The full wavadesk dashboard showing trial status, usage, KPI cards, conversation volume, channel split, response time, agent workload, busiest hours and AI performance" loading="lazy" decoding="async" width="2570" height="3320"></div><figcaption><svg width="13" height="13" viewBox="0 0 24 24" fill="none"><rect x="2.5" y="6" width="19" height="14" rx="2.5" stroke="currentColor" stroke-width="2"/><circle cx="12" cy="13" r="3.4" stroke="currentColor" stroke-width="2"/><path d="M8.5 6l1.2-2h4.6L15.5 6" stroke="currentColor" stroke-width="2" stroke-linejoin="round"/></svg><span>The dashboard in wavadesk. Everything on one screen is derived from the conversation record, so no separate tracking is required.</span></figcaption></figure>
</section>
<section id="kpis"><h2>The four figures that matter most</h2>
<p>Reporting fails when it offers forty metrics and no priority. These four cover the operational picture, and the rest is diagnosis.</p>
<figure><div class="shot"><img src="/img/features/kpis.png" alt="Four KPI cards with sparklines and period-over-period change: conversations, median first reply, resolved by AI and waiting in pool" loading="lazy" decoding="async" width="2552" height="370"></div><figcaption><svg width="13" height="13" viewBox="0 0 24 24" fill="none"><rect x="2.5" y="6" width="19" height="14" rx="2.5" stroke="currentColor" stroke-width="2"/><circle cx="12" cy="13" r="3.4" stroke="currentColor" stroke-width="2"/><path d="M8.5 6l1.2-2h4.6L15.5 6" stroke="currentColor" stroke-width="2" stroke-linejoin="round"/></svg><span>Each metric carries a trend line and a period-over-period delta, because a number without a direction is not actionable.</span></figcaption></figure>
<h3>Median first reply</h3>
<p>How long a customer waits for a human answer. Median rather than mean, because a handful of overnight conversations will drag an average into meaninglessness. This is the number customers actually experience.</p>
<h3>Conversation volume</h3>
<p>How much is arriving, split by channel. Its value is comparative — this week against last, this month against last — and it is the input for every staffing decision.</p>
<h3>Resolved by AI</h3>
<p>The share of conversations closed without a human. This is the automation dividend, and the honest measure of whether your knowledge base is doing work.</p>
<h3>Waiting in pool</h3>
<p>How many conversations are unclaimed right now, and how long the oldest has waited. The only real-time number in the set, and the one to watch during a shift.</p>
<div class="note"><svg width="17" height="17" viewBox="0 0 24 24" fill="none"><circle cx="12" cy="12" r="9" stroke="#0f7e7a" stroke-width="2"/><path d="M12 11v5" stroke="#0f7e7a" stroke-width="2" stroke-linecap="round"/><circle cx="12" cy="7.8" r="1.1" fill="#0f7e7a"/></svg><div class="m"><div class="h">Watch direction, not absolute values</div><p>A median first reply of four minutes is excellent for some businesses and poor for others. What matters is whether it is moving the way you intended.</p></div></div>
</section>
<section id="volume"><h2>Volume and channel mix</h2>
<p>Volume by day and channel answers the staffing question, and channel mix tells you where your customers are actually choosing to reach you — which is frequently not where you assumed.</p>
<figure><div class="shot"><img src="/img/features/volume-channels.png" alt="Stacked daily conversation volume by channel alongside a channel split donut with repeat-customer rate" loading="lazy" decoding="async" width="2552" height="602"></div><figcaption><svg width="13" height="13" viewBox="0 0 24 24" fill="none"><rect x="2.5" y="6" width="19" height="14" rx="2.5" stroke="currentColor" stroke-width="2"/><circle cx="12" cy="13" r="3.4" stroke="currentColor" stroke-width="2"/><path d="M8.5 6l1.2-2h4.6L15.5 6" stroke="currentColor" stroke-width="2" stroke-linejoin="round"/></svg><span>Daily volume stacked by channel, with the overall split and repeat-customer rate beside it.</span></figcaption></figure>
<p>Two patterns worth acting on. If website chat volume is high relative to WhatsApp, your pre-sales traffic is bigger than your support traffic and autonomous AI on the widget will pay off quickly. If repeat-customer rate is high, your knowledge base is the highest-leverage thing you can improve, because the same people are asking the same things.</p>
</section>
<section id="response"><h2>Response and resolution time</h2>
<p>First reply and resolution are different problems with different fixes. Confusing them leads teams to hire when they should be automating, or vice versa.</p>
<div class="tw"><table><thead><tr><th>Symptom</th><th>Usual cause</th><th>What to change</th></tr></thead><tbody><tr><td>Slow first reply, fast resolution</td><td>Nobody is watching the queue at that hour</td><td>Shift coverage, or autonomous AI for first response</td></tr><tr><td>Fast first reply, slow resolution</td><td>Agents acknowledge then get stuck</td><td>Knowledge gaps, or escalation paths that dead-end</td></tr><tr><td>Both slow</td><td>Understaffed for the volume</td><td>Headcount, or deflect more with AI</td></tr><tr><td>Weekend spike in both</td><td>No weekend cover</td><td>Autonomous AI out of hours, or a monitored queue</td></tr></tbody></table></div>
<p>The response-time chart plots the median by day, so a weekend or a shift gap shows up as a shape rather than a suspicion.</p>
</section>
<section id="workload"><h2>Agent workload and busiest hours</h2>
<p>Two questions here: is work distributed fairly, and does your coverage match when volume actually arrives.</p>
<figure><div class="shot"><img src="/img/features/agents-heatmap.png" alt="Response-time line chart, per-agent workload with capacity bars, and a seven-by-twelve busiest-hours heatmap" loading="lazy" decoding="async" width="2552" height="702"></div><figcaption><svg width="13" height="13" viewBox="0 0 24 24" fill="none"><rect x="2.5" y="6" width="19" height="14" rx="2.5" stroke="currentColor" stroke-width="2"/><circle cx="12" cy="13" r="3.4" stroke="currentColor" stroke-width="2"/><path d="M8.5 6l1.2-2h4.6L15.5 6" stroke="currentColor" stroke-width="2" stroke-linejoin="round"/></svg><span>Per-agent open conversations against capacity, and a heatmap of when volume arrives across the week.</span></figcaption></figure>
<p>The workload panel shows open conversations per agent against a capacity figure, with the bar turning amber past 80%. Persistent imbalance is usually a routing problem rather than an effort problem — one queue is absorbing more than its share.</p>
<p>The heatmap is the more actionable of the two, because it is the one people get wrong from intuition. Teams routinely staff evenly across the day when volume is concentrated in a three-hour window. Comparing the heatmap against your rota is often the single cheapest response-time improvement available.</p>
</section>
<section id="ai"><h2>AI performance</h2>
<p>AI reporting should answer one question: how much work is it taking off your team, and is it handing over the right things?</p>
<figure><div class="shot"><img src="/img/features/ai-performance.png" alt="AI performance panel with deflection rate, median AI reply time, escalation count and a stacked proportion bar" loading="lazy" decoding="async" width="2552" height="438"></div><figcaption><svg width="13" height="13" viewBox="0 0 24 24" fill="none"><rect x="2.5" y="6" width="19" height="14" rx="2.5" stroke="currentColor" stroke-width="2"/><circle cx="12" cy="13" r="3.4" stroke="currentColor" stroke-width="2"/><path d="M8.5 6l1.2-2h4.6L15.5 6" stroke="currentColor" stroke-width="2" stroke-linejoin="round"/></svg><span>AI resolved, AI assisted and escalated as proportions of total conversations, rather than a raw message count.</span></figcaption></figure>
<p>Deflection rate is the headline. The stacked bar below it separates conversations the AI closed entirely, ones where it drafted and an agent sent, and ones it escalated. Escalations are a healthy category — a deflection rate of 100% would mean the AI is answering things it should be handing over.</p>
<div class="stats"><div class="sc"><b>68%</b><span>resolved end to end by AI</span></div><div class="sc"><b>21%</b><span>AI-assisted, agent sent</span></div><div class="sc"><b>11%</b><span>deliberately escalated</span></div></div>
</section>
<section id="use"><h2>Using this in a weekly review</h2>
<p>Reporting only changes behaviour if somebody looks at it on a schedule. A fifteen-minute weekly review covers it.</p>
<ol class="numbered"><li><span>Median first reply against last week. If it moved, find the day it moved on.</span></li><li><span>Volume against last week, and whether any change was staffing or demand.</span></li><li><span>The busiest-hours heatmap against your actual rota.</span></li><li><span>Deflection rate, and the top three recurring escalation topics — these are your next knowledge base entries.</span></li><li><span>Agent load balance, and whether any imbalance is routing rather than effort.</span></li></ol>
<p>The escalation topics are the most valuable item on that list, because they convert directly into automation. Every gap closed is a category of question that stops reaching a human.</p>
</section>
