{{-- Article body for /features/reservations.
     Copy is final, from the design handoff. Structure is the shared
     article template in features/show.blade.php; edit copy here. --}}
<section id="why"><h2>Why booking on WhatsApp works</h2>
<p>For clinics, salons, garages, restaurants and professional services, the booking request almost always starts as a message. Somebody asks whether you have anything on Thursday. What happens next decides whether you get the booking.</p>
<p>The usual answer is a link to a booking page, which introduces a step the customer did not ask for. A meaningful share of them never arrive, not because they changed their mind but because the friction landed at exactly the wrong moment. Keeping the booking inside the conversation removes that drop-off.</p>
<div class="cards"><div class="fc"><div class="ic"><svg width="19" height="19" viewBox="0 0 24 24" fill="none"><rect x="3" y="5" width="18" height="16" rx="2.6" stroke="#0f7e7a" stroke-width="2"/><path d="M3 10h18M8 3v4M16 3v4" stroke="#0f7e7a" stroke-width="2" stroke-linecap="round"/></svg></div><div class="h">No context switch</div><p>The customer never leaves the thread they started, so nobody is lost to a redirect.</p></div><div class="fc"><div class="ic"><svg width="19" height="19" viewBox="0 0 24 24" fill="none"><path d="M18 8.5a6 6 0 10-12 0c0 6-2.5 7.5-2.5 7.5h17S18 14.5 18 8.5z" stroke="#0f7e7a" stroke-width="2" stroke-linejoin="round"/><path d="M13.7 20a2 2 0 01-3.4 0" stroke="#0f7e7a" stroke-width="2" stroke-linecap="round"/></svg></div><div class="h">Reminders that get read</div><p>A WhatsApp reminder in an existing thread is opened far more reliably than an SMS or an email.</p></div><div class="fc"><div class="ic"><svg width="19" height="19" viewBox="0 0 24 24" fill="none"><path d="M16 20v-2a4 4 0 00-4-4H6a4 4 0 00-4 4v2" stroke="#0f7e7a" stroke-width="2" stroke-linecap="round"/><circle cx="9" cy="7" r="3.4" stroke="#0f7e7a" stroke-width="2"/><path d="M22 20v-2a4 4 0 00-3-3.9" stroke="#0f7e7a" stroke-width="2" stroke-linecap="round"/></svg></div><div class="h">One place to look</div><p>Bookings and the conversation that produced them sit together, so staff see both.</p></div><div class="fc"><div class="ic"><svg width="19" height="19" viewBox="0 0 24 24" fill="none"><circle cx="12" cy="12" r="9" stroke="#0f7e7a" stroke-width="2"/><path d="M12 7v5.4l3.4 2" stroke="#0f7e7a" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/></svg></div><div class="h">Reschedules stay simple</div><p>Changing a time is a reply, not a form. That means people actually do it rather than no-showing.</p></div></div>
</section>
<section id="flow"><h2>The booking flow</h2>
<p>The flow is deliberately short, and the AI agent can handle most of it before a human is involved.</p>
<div class="steps"><div class="step"><span class="n">1</span><div class="m"><div class="h">Customer asks about availability</div><p>Either in open language or by picking from options the AI offers.</p></div></div><div class="step"><span class="n">2</span><div class="m"><div class="h">Availability is offered</div><p>Drawn from your configured hours, service durations and existing bookings, so nothing double-books.</p></div></div><div class="step"><span class="n">3</span><div class="m"><div class="h">The customer picks a slot</div><p>Confirmed in the conversation. The slot is held immediately.</p></div></div><div class="step"><span class="n">4</span><div class="m"><div class="h">Confirmation and reminder are scheduled</div><p>An immediate confirmation, then a reminder on the schedule you set — typically 24 hours and again two hours before.</p></div></div></div>
<div class="note"><svg width="17" height="17" viewBox="0 0 24 24" fill="none"><circle cx="12" cy="12" r="9" stroke="#0f7e7a" stroke-width="2"/><path d="M12 11v5" stroke="#0f7e7a" stroke-width="2" stroke-linecap="round"/><circle cx="12" cy="7.8" r="1.1" fill="#0f7e7a"/></svg><div class="m"><div class="h">Staff can always take over</div><p>If a customer needs something the automation cannot handle — a specific practitioner, a double slot, a special case — an agent claims the conversation and books it manually. The reminder schedule still applies.</p></div></div>
</section>
<section id="noshows"><h2>Reducing no-shows</h2>
<p>No-shows are the single largest cost in appointment businesses, and they are mostly a memory problem rather than a commitment problem. The fix is a reminder that is actually seen, with a frictionless way to change the time.</p>
<p>A reminder that only says "you have an appointment tomorrow" is a half measure. The reminder should make it as easy to reschedule as to ignore, because a rescheduled slot can be refilled and a no-show cannot.</p>
<h3>What an effective reminder does</h3>
<ul><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>Arrives in the existing WhatsApp thread, not from an unknown sender</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>States the service, time, date and location without the customer having to look anything up</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>Offers confirm and reschedule as a direct reply</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>Goes out on a schedule you control, typically 24 hours and 2 hours before</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>Records the response against the booking, so staff know who has confirmed</span></li></ul>
<div class="note amber"><svg width="17" height="17" viewBox="0 0 24 24" fill="none"><path d="M12 8v5" stroke="#92400e" stroke-width="2.2" stroke-linecap="round"/><circle cx="12" cy="16.5" r="1.2" fill="#92400e"/><circle cx="12" cy="12" r="9" stroke="#92400e" stroke-width="2"/></svg><div class="m"><div class="h">Two reminders is usually the ceiling</div><p>A day before and a couple of hours before covers the realistic forgetting window. More than that reads as nagging and gets muted, which costs you the channel.</p></div></div>
</section>
<section id="calendar"><h2>Calendar and capacity</h2>
<p>Availability is only trustworthy if it reflects reality. The module works from your configured capacity rather than a free-text guess by whoever is answering.</p>
<ul><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>Opening hours per day, including split shifts and closures</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>Service durations, so a 20-minute and a 90-minute appointment consume different capacity</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>Multiple resources — practitioners, chairs, bays, tables — each with their own schedule</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>Buffer time between appointments, where turnaround is needed</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>Blackout dates for holidays and maintenance</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>Maximum concurrent bookings per slot</span></li></ul>
<p>Because capacity is defined once, an AI-offered slot and a staff-offered slot cannot contradict each other. Double-booking becomes a configuration question rather than a human error.</p>
</section>
<section id="verify"><h2>Verifying the booking is real</h2>
<p>Businesses that hold scarce capacity — restaurants at peak, clinics with limited slots — lose money to bookings made with a wrong or fake number. Pairing reservations with the OTP module closes that.</p>
<p>When you require verification, the customer confirms their number with a one-time code before the slot is held. It adds one step for the customer and removes an entire category of loss for you.</p>
<p>See <a href="/features/otp-service">WhatsApp OTP and verification</a>.</p>
</section>
<section id="who"><h2>Who uses reservations</h2>
<div class="cards"><div class="fc"><div class="ic"><svg width="19" height="19" viewBox="0 0 24 24" fill="none"><path d="M16 20v-2a4 4 0 00-4-4H6a4 4 0 00-4 4v2" stroke="#0f7e7a" stroke-width="2" stroke-linecap="round"/><circle cx="9" cy="7" r="3.4" stroke="#0f7e7a" stroke-width="2"/><path d="M22 20v-2a4 4 0 00-3-3.9" stroke="#0f7e7a" stroke-width="2" stroke-linecap="round"/></svg></div><div class="h">Clinics and dental practices</div><p>Appointment requests, reschedules and recall reminders, where a missed message is a missed booking.</p></div><div class="fc"><div class="ic"><svg width="19" height="19" viewBox="0 0 24 24" fill="none"><rect x="3" y="5" width="18" height="16" rx="2.6" stroke="#0f7e7a" stroke-width="2"/><path d="M3 10h18M8 3v4M16 3v4" stroke="#0f7e7a" stroke-width="2" stroke-linecap="round"/></svg></div><div class="h">Salons and barbers</div><p>High volume of short appointments, heavy reschedule traffic and real no-show cost.</p></div><div class="fc"><div class="ic"><svg width="19" height="19" viewBox="0 0 24 24" fill="none"><rect x="6" y="2.5" width="12" height="19" rx="2.6" stroke="#0f7e7a" stroke-width="2"/><path d="M11 18.5h2" stroke="#0f7e7a" stroke-width="2" stroke-linecap="round"/></svg></div><div class="h">Garages and workshops</div><p>Bay capacity with long service durations, where double-booking is expensive.</p></div><div class="fc"><div class="ic"><svg width="19" height="19" viewBox="0 0 24 24" fill="none"><circle cx="12" cy="12" r="9" stroke="#0f7e7a" stroke-width="2"/><path d="M3 12h18M12 3c2.5 2.6 2.5 15.4 0 18M12 3c-2.5 2.6-2.5 15.4 0 18" stroke="#0f7e7a" stroke-width="2"/></svg></div><div class="h">Restaurants</div><p>Peak-time tables where verified bookings matter more than volume.</p></div></div>
<p>The reservations module is included on the Scale plan and available as an add-on to others.</p>
</section>
