{{-- Article body for /features/teams-routing.
     Copy is final, from the design handoff. Structure is the shared
     article template in features/show.blade.php; edit copy here. --}}
<section id="why"><h2>When one queue stops working</h2>
<p>A shared pool is the right default. Everyone sees everything, anyone can pick up anything, and the overhead of configuration is zero. That holds up to roughly five or six agents handling broadly similar questions.</p>
<p>Past that, two things break. Agents spend real time filtering visually — reading and skipping conversations that belong to another function. And specialisation becomes impossible: if the person who handles billing disputes sees the same undifferentiated list as everyone else, their expertise is not being pointed at the right work.</p>
<p>Routing is the fix, and its purpose is subtractive. It is not about giving people more information. It is about <strong>giving each agent less to look at</strong>, so what remains is theirs.</p>
</section>
<section id="teams"><h2>Setting up teams</h2>
<p>A team is a group of agents and a queue. Most organisations map them to the functions that already exist rather than inventing new ones.</p>
<div class="cards"><div class="fc"><div class="ic"><svg width="19" height="19" viewBox="0 0 24 24" fill="none"><path d="M16 20v-2a4 4 0 00-4-4H6a4 4 0 00-4 4v2" stroke="#0f7e7a" stroke-width="2" stroke-linecap="round"/><circle cx="9" cy="7" r="3.4" stroke="#0f7e7a" stroke-width="2"/><path d="M22 20v-2a4 4 0 00-3-3.9" stroke="#0f7e7a" stroke-width="2" stroke-linecap="round"/></svg></div><div class="h">By function</div><p>Sales, support, billing, returns. The most common split, because the skills genuinely differ.</p></div><div class="fc"><div class="ic"><svg width="19" height="19" viewBox="0 0 24 24" fill="none"><circle cx="12" cy="12" r="9" stroke="#0f7e7a" stroke-width="2"/><path d="M3 12h18M12 3c2.5 2.6 2.5 15.4 0 18M12 3c-2.5 2.6-2.5 15.4 0 18" stroke="#0f7e7a" stroke-width="2"/></svg></div><div class="h">By language</div><p>Where you serve multiple languages and not every agent speaks all of them.</p></div><div class="fc"><div class="ic"><svg width="19" height="19" viewBox="0 0 24 24" fill="none"><circle cx="12" cy="12" r="9" stroke="#0f7e7a" stroke-width="2"/><path d="M12 7v5.4l3.4 2" stroke="#0f7e7a" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/></svg></div><div class="h">By shift</div><p>Morning and evening teams, so out-of-hours conversations land with whoever is actually on.</p></div><div class="fc"><div class="ic"><svg width="19" height="19" viewBox="0 0 24 24" fill="none"><path d="M12 2H4a2 2 0 00-2 2v8l10 10 10-10L12 2z" stroke="#0f7e7a" stroke-width="2" stroke-linejoin="round"/><circle cx="7.5" cy="7.5" r="1.4" fill="#0f7e7a"/></svg></div><div class="h">By product line</div><p>Where products are different enough that knowledge does not transfer.</p></div></div>
<p>An agent can belong to more than one team. A small operation often has everyone in every team initially, then narrows as it grows — which is the right order, because you learn the real boundaries from the traffic.</p>
</section>
<section id="rules"><h2>Routing rules</h2>
<p>Rules are evaluated in order, and the first match wins. Keeping the list short is a feature, not a limitation — long rule chains become impossible to reason about when something goes to the wrong place.</p>
<h3>Route by keyword</h3>
<p>The message itself often names the department. "Refund", "invoice" and "chargeback" mean billing; "quote" and "pricing" mean sales. Keyword routing catches the clear cases and leaves the ambiguous ones in the general pool.</p>
<h3>Route by channel</h3>
<p>Website widget conversations are frequently pre-sales — someone reading your pricing page — while WhatsApp skews toward existing customers. Routing by channel is a crude but effective proxy for intent.</p>
<h3>Route by hours</h3>
<p>Outside business hours, conversations should land where someone is watching, or in a queue that is explicitly monitored the next morning, rather than in a general pool nobody owns overnight.</p>
<h3>Route by contact</h3>
<p>Named accounts, VIP customers or specific numbers can be routed directly to a named team or agent, so your most important relationships do not queue behind general traffic.</p>
<div class="note"><svg width="17" height="17" viewBox="0 0 24 24" fill="none"><circle cx="12" cy="12" r="9" stroke="#0f7e7a" stroke-width="2"/><path d="M12 11v5" stroke="#0f7e7a" stroke-width="2" stroke-linecap="round"/><circle cx="12" cy="7.8" r="1.1" fill="#0f7e7a"/></svg><div class="m"><div class="h">Leave a default</div><p>Every routing setup needs a fallback queue for conversations that match nothing. Without one, edge cases disappear.</p></div></div>
</section>
<section id="assignment"><h2>Assignment and claiming</h2>
<p>Routing decides which queue a conversation enters. Assignment decides who owns it. These are separate, and conflating them is the most common configuration mistake.</p>
<ul><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>Routed to a team, unassigned — agents in that team claim from the queue</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>Auto-assigned round-robin — distributed evenly across available agents in the team</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>Assigned to a named agent — for named accounts or continuing an earlier conversation</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>Reassigned by a lead — recorded, so handovers stay visible in the audit trail</span></li></ul>
<p>Most teams should start with routed-but-unassigned and claiming. Round-robin sounds fairer but distributes work to people who may be mid-conversation on something complex, and it removes the agent's ability to pick up what they are best placed to answer.</p>
<div class="note amber"><svg width="17" height="17" viewBox="0 0 24 24" fill="none"><path d="M12 8v5" stroke="#92400e" stroke-width="2.2" stroke-linecap="round"/><circle cx="12" cy="16.5" r="1.2" fill="#92400e"/><circle cx="12" cy="12" r="9" stroke="#92400e" stroke-width="2"/></svg><div class="m"><div class="h">Auto-assignment needs presence to work</div><p>Assigning conversations to an agent who is offline creates a silent queue behind one person. Only enable it where you can rely on availability status being accurate.</p></div></div>
</section>
<section id="escalation"><h2>Escalation and ageing</h2>
<p>Every routing setup eventually strands a conversation: it is in the right queue, and nobody has claimed it. Escalation rules catch that automatically rather than relying on someone noticing.</p>
<div class="steps"><div class="step"><span class="n">1</span><div class="m"><div class="h">Set an age threshold</div><p>For example, 15 minutes unclaimed during business hours.</p></div></div><div class="step"><span class="n">2</span><div class="m"><div class="h">Escalate on breach</div><p>Move the conversation to a lead's queue, or flag it at the top of the team queue.</p></div></div><div class="step"><span class="n">3</span><div class="m"><div class="h">Watch the oldest-waiting figure</div><p>The queue surfaces the longest-waiting conversation, so a growing number is visible before customers complain.</p></div></div><div class="step"><span class="n">4</span><div class="m"><div class="h">Adjust the threshold to reality</div><p>A threshold nobody can meet is noise. Set it where breaches are genuinely exceptional.</p></div></div></div>
<figure><div class="shot"><img src="/img/features/agents-heatmap.png" alt="Agent workload panel with capacity bars and a busiest-hours heatmap" loading="lazy" decoding="async" width="2552" height="702"></div><figcaption><svg width="13" height="13" viewBox="0 0 24 24" fill="none"><rect x="2.5" y="6" width="19" height="14" rx="2.5" stroke="currentColor" stroke-width="2"/><circle cx="12" cy="13" r="3.4" stroke="currentColor" stroke-width="2"/><path d="M8.5 6l1.2-2h4.6L15.5 6" stroke="currentColor" stroke-width="2" stroke-linejoin="round"/></svg><span>Per-agent load with capacity bars, and the hours when volume actually arrives — the two inputs for setting realistic thresholds and shift coverage.</span></figcaption></figure>
</section>
<section id="measure"><h2>Checking your routing is right</h2>
<p>Routing is a hypothesis about how work should be divided. The reporting tells you whether the hypothesis holds.</p>
<ul><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>Reassignment rate — high reassignment means rules are sending work to the wrong team</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>Per-team response time — one slow queue usually means understaffing, not laziness</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>Agent load balance — persistently uneven load means routing is concentrating work</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>Escalation frequency — rising escalations mean thresholds or staffing need attention</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>Volume by hour against shift coverage — the heatmap against your rota</span></li></ul>
<p>More in <a href="/features/reports-analytics">Support reports and analytics</a>.</p>
</section>
