{{-- Article body for /features/whatsapp-shared-inbox.
     Copy is final, from the design handoff. Structure is the shared
     article template in features/show.blade.php; edit copy here. --}}
<section id="problem"><h2>The problem with one phone</h2>
<p>Almost every team that supports customers on WhatsApp begins the same way: one handset, or one login to WhatsApp Web, shared between whoever is on shift. It works for a while. Then volume grows and the cracks turn out to be structural rather than occasional.</p>
<p>There is no queue, so nobody can see what is waiting. There is no ownership, so two agents open the same chat and send two different answers. There is no record, so when someone leaves the team, every promise they made to a customer leaves with them. And there is no way to answer the simplest management question there is: how long are people waiting?</p>
<ul><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>A message read by one agent looks read to everyone, so it gets skipped</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>Two agents replying to the same customer with conflicting answers</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>No idea who promised a refund, a discount or a delivery date</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>History tied to a device instead of the business</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>No response-time or volume figures to manage against</span></li></ul>
<p>A shared inbox fixes these by changing the unit of work. Instead of a stream of messages on a device, you get <strong>conversations with an owner, a status and a history</strong>.</p>
</section>
<section id="how"><h2>How the shared inbox works</h2>
<p>Every incoming message on your connected WhatsApp number becomes a conversation in one list the whole team can see. Nothing is assigned automatically unless you set up routing rules — by default it sits in a shared pool, waiting for someone to pick it up.</p>
<figure><div class="shot"><img src="/img/features/inbox-full.png" alt="wavadesk shared inbox showing the conversation list, an open thread and the customer context panel" loading="lazy" decoding="async" width="3186" height="1766"></div><figcaption><svg width="13" height="13" viewBox="0 0 24 24" fill="none"><rect x="2.5" y="6" width="19" height="14" rx="2.5" stroke="currentColor" stroke-width="2"/><circle cx="12" cy="13" r="3.4" stroke="currentColor" stroke-width="2"/><path d="M8.5 6l1.2-2h4.6L15.5 6" stroke="currentColor" stroke-width="2" stroke-linejoin="round"/></svg><span>The shared inbox in wavadesk. The list on the left is the pool every agent sees; the panel on the right carries the customer context for whichever conversation is open.</span></figcaption></figure>
<p>The three panes map onto the three questions an agent has at any moment: what is waiting, what am I replying to, and who am I talking to. Channel badges on each avatar tell you whether a conversation arrived over WhatsApp or the website widget, so one queue can carry both without confusion.</p>
<div class="cards"><div class="fc"><div class="ic"><svg width="19" height="19" viewBox="0 0 24 24" fill="none"><path d="M21 11.5a8.4 8.4 0 01-9 8.4 8.9 8.9 0 01-3.9-.9L3 20.5l1.5-4.6A8.4 8.4 0 013.6 11.5a8.4 8.4 0 018.4-8.4 8.4 8.4 0 019 8.4z" stroke="#0f7e7a" stroke-width="2" stroke-linejoin="round"/></svg></div><div class="h">One pool, not many mailboxes</div><p>Every conversation from every connected channel lands in the same list, filterable by channel, status and assignee.</p></div><div class="fc"><div class="ic"><svg width="19" height="19" viewBox="0 0 24 24" fill="none"><rect x="4.5" y="10.5" width="15" height="10" rx="2.2" stroke="#0f7e7a" stroke-width="2"/><path d="M8 10.5V7a4 4 0 018 0v3.5" stroke="#0f7e7a" stroke-width="2" stroke-linecap="round"/></svg></div><div class="h">Claim to work it</div><p>An agent claims a conversation and it locks to them. The claim is enforced at the database level, not just in the interface.</p></div><div class="fc"><div class="ic"><svg width="19" height="19" viewBox="0 0 24 24" fill="none"><path d="M4 4h16v12l-4 4H4z" stroke="#0f7e7a" stroke-width="2" stroke-linejoin="round"/><path d="M8 9h8M8 13h5" stroke="#0f7e7a" stroke-width="2" stroke-linecap="round"/></svg></div><div class="h">Internal notes</div><p>Notes are visible to your team and never sent to the customer, so context travels with the conversation.</p></div><div class="fc"><div class="ic"><svg width="19" height="19" viewBox="0 0 24 24" fill="none"><circle cx="12" cy="12" r="9" stroke="#0f7e7a" stroke-width="2"/><path d="M12 7v5.4l3.4 2" stroke="#0f7e7a" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/></svg></div><div class="h">Status and history</div><p>Open, claimed, resolved, reopened. Every state change is timestamped with a name against it.</p></div></div>
</section>
<section id="claim"><h2>Claim locking, and why it matters</h2>
<p>The single worst moment in shared support is two people answering the same customer. It is worse than a slow reply, because the customer now has two answers and no idea which is true — and your team has to unpick it in front of them.</p>
<p>wavadesk prevents it structurally rather than socially. When an agent claims a conversation, the claim is written as a lock. A second agent opening the same conversation sees it as claimed and cannot take it or send into it. There is no race condition to lose, and no convention for a busy team to forget under pressure.</p>
<div class="note"><svg width="17" height="17" viewBox="0 0 24 24" fill="none"><circle cx="12" cy="12" r="9" stroke="#0f7e7a" stroke-width="2"/><path d="M12 11v5" stroke="#0f7e7a" stroke-width="2" stroke-linecap="round"/><circle cx="12" cy="7.8" r="1.1" fill="#0f7e7a"/></svg><div class="m"><div class="h">Claims are reversible</div><p>An agent can release a conversation back to the pool, and a lead can reassign it. Locking prevents accidental collisions, not deliberate handovers.</p></div></div>
<p>When a claim is released or reassigned, that too is recorded. Over a week you can see not only who answered what, but where work moved between people — which is usually where delays hide.</p>
</section>
<section id="context"><h2>One customer, one history</h2>
<p>A conversation is only useful with the history behind it. When a customer messages for the fourth time this month, the agent should not be asking them to explain their situation again.</p>
<p>Every conversation opens with the customer's full past thread attached, regardless of which agent handled those earlier exchanges or which channel they arrived on. If someone asked a question through your website widget in August and messages on WhatsApp in September, it is one history, not two.</p>
<h3>What travels with the customer</h3>
<ul><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>Every previous conversation on any connected channel</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>Tags you have applied, for segmenting and filtering</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>Internal notes your team left on past conversations</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>Assignment history and resolution status</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>Order or booking references, where you have connected them</span></li></ul>
</section>
<section id="audit"><h2>Every action is attributable</h2>
<p>Support disputes are almost never about what a customer said. They are about what your team said. An audit trail turns that from an argument into a lookup.</p>
<p>wavadesk records who claimed a conversation, who replied, what was sent, when statuses changed, which notes were added, and where the AI acted on its own. Nothing is anonymous and nothing is silently editable.</p>
<p>This matters in three practical situations: a customer insists they were promised something, a new agent needs to understand how a case was handled, and a manager needs to see whether a process is actually being followed rather than nominally in place.</p>
</section>
<section id="setup"><h2>Getting connected</h2>
<p>Setup is deliberately short, because a support tool that takes a week to install never gets installed.</p>
<div class="steps"><div class="step"><span class="n">1</span><div class="m"><div class="h">Scan a QR code</div><p>Connect your existing WhatsApp Business number the same way you connect WhatsApp Web. No number migration, and nothing changes for your customers.</p></div></div><div class="step"><span class="n">2</span><div class="m"><div class="h">Invite your agents</div><p>Add the people who will answer, and put them into teams if you want routing by department.</p></div></div><div class="step"><span class="n">3</span><div class="m"><div class="h">Paste your FAQ</div><p>Give the AI agent something to answer from. This is optional at the start and can be added later.</p></div></div><div class="step"><span class="n">4</span><div class="m"><div class="h">Start claiming</div><p>Conversations begin landing in the shared pool immediately. Your team claims and replies from the browser.</p></div></div></div>
<div class="note"><svg width="17" height="17" viewBox="0 0 24 24" fill="none"><circle cx="12" cy="12" r="9" stroke="#0f7e7a" stroke-width="2"/><path d="M12 11v5" stroke="#0f7e7a" stroke-width="2" stroke-linecap="round"/><circle cx="12" cy="7.8" r="1.1" fill="#0f7e7a"/></svg><div class="m"><div class="h">Your customers notice nothing</div><p>They keep messaging the number they already know. The change is entirely on your side of the conversation.</p></div></div>
</section>
<section id="who"><h2>Who a shared inbox is for</h2>
<p>The pattern is consistent: a shared inbox pays off the moment more than one person is expected to answer the same number. Below that, a phone works fine. Above it, the phone is the bottleneck.</p>
<div class="cards"><div class="fc"><div class="ic"><svg width="19" height="19" viewBox="0 0 24 24" fill="none"><path d="M16 20v-2a4 4 0 00-4-4H6a4 4 0 00-4 4v2" stroke="#0f7e7a" stroke-width="2" stroke-linecap="round"/><circle cx="9" cy="7" r="3.4" stroke="#0f7e7a" stroke-width="2"/><path d="M22 20v-2a4 4 0 00-3-3.9" stroke="#0f7e7a" stroke-width="2" stroke-linecap="round"/></svg></div><div class="h">E-commerce and retail</div><p>Order status, delivery windows, returns and exchanges — high volume, mostly repetitive, easy to lose track of.</p></div><div class="fc"><div class="ic"><svg width="19" height="19" viewBox="0 0 24 24" fill="none"><rect x="3" y="5" width="18" height="16" rx="2.6" stroke="#0f7e7a" stroke-width="2"/><path d="M3 10h18M8 3v4M16 3v4" stroke="#0f7e7a" stroke-width="2" stroke-linecap="round"/></svg></div><div class="h">Clinics and services</div><p>Appointment requests, reschedules and reminders, where a missed message is a missed booking.</p></div><div class="fc"><div class="ic"><svg width="19" height="19" viewBox="0 0 24 24" fill="none"><rect x="6" y="2.5" width="12" height="19" rx="2.6" stroke="#0f7e7a" stroke-width="2"/><path d="M11 18.5h2" stroke="#0f7e7a" stroke-width="2" stroke-linecap="round"/></svg></div><div class="h">Businesses with staff shifts</div><p>Handover between shifts is where shared phones fail hardest and where a queue with history helps most.</p></div><div class="fc"><div class="ic"><svg width="19" height="19" viewBox="0 0 24 24" fill="none"><path d="M4 20V10M10 20V4M16 20v-7M22 20H2" stroke="#0f7e7a" stroke-width="2" stroke-linecap="round"/></svg></div><div class="h">Teams that need reporting</div><p>Any operation where somebody has to answer for response times rather than guess at them.</p></div></div>
</section>
