{{-- Article body for /features/whatsapp-multi-agent.
     Copy is final, from the design handoff. Structure is the shared
     article template in features/show.blade.php; edit copy here. --}}
<section id="why"><h2>Why WhatsApp alone cannot do this</h2>
<p>WhatsApp Business is an excellent single-operator tool. It was designed around one account, one device and one person's sense of what has been dealt with. The linked-devices feature extends that to a handful of screens, but it does not change the model: everyone looks at the same undifferentiated stream, with no concept of who owns what.</p>
<p>That distinction is the whole problem. Multiple people <em>seeing</em> messages is not the same as multiple people <em>working</em> messages. Without ownership, a shared view actively creates failure modes that a single operator never has.</p>
<div class="tw"><table><thead><tr><th>What a team needs</th><th>Shared phone or linked devices</th><th>With wavadesk</th></tr></thead><tbody><tr><td>See what is waiting</td><td>A stream, oldest scrolled away</td><td>A queue with wait times and the oldest surfaced</td></tr><tr><td>Know who is handling it</td><td>Nothing — you ask out loud</td><td>Claim locks the conversation to one agent</td></tr><tr><td>Stop duplicate replies</td><td>Convention and luck</td><td>Enforced in the database</td></tr><tr><td>Keep history when staff change</td><td>Tied to the device</td><td>Tied to the workspace</td></tr><tr><td>Split by department</td><td>Not possible</td><td>Routing to team queues</td></tr><tr><td>Report on response time</td><td>No data</td><td>Median first reply, resolution, per-agent load</td></tr></tbody></table></div>
<p>The practical consequence is that shared access without ownership tends to be worse than one dedicated person, because responsibility becomes diffuse. Everyone assumes somebody else replied.</p>
</section>
<section id="model"><h2>What real multi-agent access looks like</h2>
<p>Multi-agent support needs four things beyond a shared view. Each exists to answer a question that a single operator never has to ask.</p>
<div class="cards"><div class="fc"><div class="ic"><svg width="19" height="19" viewBox="0 0 24 24" fill="none"><path d="M21 11.5a8.4 8.4 0 01-9 8.4 8.9 8.9 0 01-3.9-.9L3 20.5l1.5-4.6A8.4 8.4 0 013.6 11.5a8.4 8.4 0 018.4-8.4 8.4 8.4 0 019 8.4z" stroke="#0f7e7a" stroke-width="2" stroke-linejoin="round"/></svg></div><div class="h">A queue</div><p>What is waiting, and how long has it been waiting? A stream cannot answer this; a queue with timestamps can.</p></div><div class="fc"><div class="ic"><svg width="19" height="19" viewBox="0 0 24 24" fill="none"><rect x="4.5" y="10.5" width="15" height="10" rx="2.2" stroke="#0f7e7a" stroke-width="2"/><path d="M8 10.5V7a4 4 0 018 0v3.5" stroke="#0f7e7a" stroke-width="2" stroke-linecap="round"/></svg></div><div class="h">Ownership</div><p>Who is dealing with this one right now, and can anyone else send into it? This is claiming, and it must be enforced rather than agreed.</p></div><div class="fc"><div class="ic"><svg width="19" height="19" viewBox="0 0 24 24" fill="none"><path d="M12 3v6M12 15v6M3 12h6M15 12h6" stroke="#0f7e7a" stroke-width="2" stroke-linecap="round"/><circle cx="12" cy="12" r="2.6" stroke="#0f7e7a" stroke-width="2"/></svg></div><div class="h">Routing</div><p>Which team should see this at all? Billing questions do not belong in the sales queue.</p></div><div class="fc"><div class="ic"><svg width="19" height="19" viewBox="0 0 24 24" fill="none"><path d="M4 20V10M10 20V4M16 20v-7M22 20H2" stroke="#0f7e7a" stroke-width="2" stroke-linecap="round"/></svg></div><div class="h">Attribution</div><p>Who did what, when? Both for accountability and for knowing where time actually goes.</p></div></div>
<figure><div class="shot"><img src="/img/features/inbox-full.png" alt="The wavadesk inbox with a shared conversation pool, open thread and customer panel" loading="lazy" decoding="async" width="3186" height="1766"></div><figcaption><svg width="13" height="13" viewBox="0 0 24 24" fill="none"><rect x="2.5" y="6" width="19" height="14" rx="2.5" stroke="currentColor" stroke-width="2"/><circle cx="12" cy="13" r="3.4" stroke="currentColor" stroke-width="2"/><path d="M8.5 6l1.2-2h4.6L15.5 6" stroke="currentColor" stroke-width="2" stroke-linejoin="round"/></svg><span>Ownership is visible in the queue itself: unclaimed conversations, conversations locked to a named agent, and conversations the AI is handling.</span></figcaption></figure>
</section>
<section id="claiming"><h2>Claiming: ownership you cannot fumble</h2>
<p>In wavadesk, agents work from a shared pool and claim a conversation to take it. Claiming does two things at once: it tells the team this one is handled, and it locks the conversation so nobody else can reply into it.</p>
<p>The lock is enforced at the database level. If two agents click claim in the same second, one wins and the other is told the conversation is taken. There is no window in which both believe they own it — and that window is exactly where duplicate replies are born.</p>
<div class="note"><svg width="17" height="17" viewBox="0 0 24 24" fill="none"><circle cx="12" cy="12" r="9" stroke="#0f7e7a" stroke-width="2"/><path d="M12 11v5" stroke="#0f7e7a" stroke-width="2" stroke-linecap="round"/><circle cx="12" cy="7.8" r="1.1" fill="#0f7e7a"/></svg><div class="m"><div class="h">Release and reassign</div><p>Claims are not permanent. An agent can release a conversation back to the pool and a lead can reassign it — both recorded, so handovers stay visible.</p></div></div>
</section>
<section id="routing"><h2>Routing so people see less, not more</h2>
<p>A single pool is right for a team of three. At fifteen it becomes noise: every agent scrolls past thirty conversations that are not theirs to find the ones that are.</p>
<p>Routing puts conversations in front of the right team by rules you set, so each agent's queue is the subset they can actually act on. The rest still exists and is still auditable, it is just not in their way.</p>
<ul><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>Route by team, so returns, billing and sales each have their own queue</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>Route by keyword, for cases where the message itself identifies the department</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>Route by hours, so out-of-hours conversations land where someone is watching</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>Escalate to a lead when a conversation ages past a threshold</span></li></ul>
<p>Read more in <a href="/features/teams-routing">Teams, routing and assignment</a>.</p>
</section>
<section id="seats"><h2>How seats and capacity work</h2>
<p>Each person who answers customers needs their own login, so that claiming and the audit trail mean something. Shared logins defeat both.</p>
<p>Plans include a base number of seats, and you can add more without changing plan when the team grows mid-cycle. Capacity is visible in the billing screen rather than something you discover by hitting a wall.</p>
<figure><div class="shot"><img src="/img/features/usage-meters.png" alt="Usage meters showing users and AI messages consumed against the plan allowance" loading="lazy" decoding="async" width="1760" height="322"></div><figcaption><svg width="13" height="13" viewBox="0 0 24 24" fill="none"><rect x="2.5" y="6" width="19" height="14" rx="2.5" stroke="currentColor" stroke-width="2"/><circle cx="12" cy="13" r="3.4" stroke="currentColor" stroke-width="2"/><path d="M8.5 6l1.2-2h4.6L15.5 6" stroke="currentColor" stroke-width="2" stroke-linejoin="round"/></svg><span>Seat and AI-message usage against your plan allowance, with the option to add capacity without changing plan.</span></figcaption></figure>
<p>See <a href="{{ url('/#pricing') }}">pricing</a> for what each plan includes.</p>
</section>
<section id="migrate"><h2>Moving a team off a shared phone</h2>
<p>The switch is usually less disruptive than teams expect, because the customer-facing side does not change at all.</p>
<div class="steps"><div class="step"><span class="n">1</span><div class="m"><div class="h">Connect the existing number</div><p>Scan the QR with the phone that holds your WhatsApp Business account. Conversations start arriving in the shared pool.</p></div></div><div class="step"><span class="n">2</span><div class="m"><div class="h">Add the people already answering</div><p>Give each of them a seat. Start with the same group who currently share the handset.</p></div></div><div class="step"><span class="n">3</span><div class="m"><div class="h">Agree one rule: claim before you reply</div><p>This is the only behavioural change, and the interface enforces it anyway.</p></div></div><div class="step"><span class="n">4</span><div class="m"><div class="h">Stop replying from the handset</div><p>This is the step teams skip, and the one that matters. Replies sent from the phone bypass the queue and the audit trail.</p></div></div></div>
<div class="note amber"><svg width="17" height="17" viewBox="0 0 24 24" fill="none"><path d="M12 8v5" stroke="#92400e" stroke-width="2.2" stroke-linecap="round"/><circle cx="12" cy="16.5" r="1.2" fill="#92400e"/><circle cx="12" cy="12" r="9" stroke="#92400e" stroke-width="2"/></svg><div class="m"><div class="h">Do not run both in parallel for long</div><p>A week of overlap is fine while people adjust. Longer than that and you have two sources of truth, which is the problem you were trying to solve.</p></div></div>
</section>
