{{-- Corps d'article français pour /features/ai-agent.
     Structure identique à la version anglaise : seul le texte change, afin
     que les ancres de sommaire de config/seo_pages.php restent valides. --}}
<section id="what"><h2>Ce que fait réellement l'agent IA</h2>
<p>Le volume de support est rarement fait de questions difficiles. Il est fait des mêmes quarante questions formulées différemment : où est ma commande, livrez-vous le dimanche, puis-je changer d'adresse, quels sont vos horaires, comment renvoyer un article.</p>
<p>L'agent IA lit un message entrant, le confronte aux connaissances que vous lui avez fournies et produit une réponse dans vos termes. Selon le mode choisi, il transmet ce brouillon à un agent ou l'envoie directement. Tout ce qu'il fait arrive dans la même boîte partagée que les réponses humaines, étiqueté pour que vous puissiez toujours les distinguer.</p>
<div class="note"><svg width="17" height="17" viewBox="0 0 24 24" fill="none"><circle cx="12" cy="12" r="9" stroke="#0f7e7a" stroke-width="2"/><path d="M12 11v5" stroke="#0f7e7a" stroke-width="2" stroke-linecap="round"/><circle cx="12" cy="7.8" r="1.1" fill="#0f7e7a"/></svg><div class="m"><div class="h">Il est ancré, il ne devine pas</div><p>L'agent répond à partir de votre base de connaissances. Si la réponse ne s'y trouve pas, il n'en invente pas — il escalade. Voir <a href="/features/knowledge-base">Base de connaissances</a> pour savoir comment l'alimenter.</p></div></div>
</section>
<section id="modes"><h2>Trois modes, et quand utiliser chacun</h2>
<p>La crainte la plus répandue à propos du support par IA est de perdre le contrôle de ce qui est dit aux clients. wavadesk y répond par des modes plutôt que par des promesses : vous choisissez le degré d'autonomie de l'agent, et vous pouvez le changer à tout moment.</p>
<div class="cards"><div class="fc"><div class="ic"><svg width="19" height="19" viewBox="0 0 24 24" fill="none"><path d="M4 4h16v12l-4 4H4z" stroke="#0f7e7a" stroke-width="2" stroke-linejoin="round"/><path d="M8 9h8M8 13h5" stroke="#0f7e7a" stroke-width="2" stroke-linecap="round"/></svg></div><div class="h">Suggestion</div><p>L'IA rédige, votre agent lit, corrige si nécessaire et envoie. Rien n'atteint un client sans qu'un humain appuie sur envoyer. Commencez ici.</p></div><div class="fc"><div class="ic"><svg width="19" height="19" viewBox="0 0 24 24" fill="none"><path d="M4 13h6l-1 8 9-12h-6l1-8z" stroke="#0f7e7a" stroke-width="2" stroke-linejoin="round"/></svg></div><div class="h">Autonome</div><p>L'IA répond directement, sans attendre un agent. À privilégier une fois que vous faites confiance à ses réponses sur un ensemble de sujets défini.</p></div><div class="fc"><div class="ic"><svg width="19" height="19" viewBox="0 0 24 24" fill="none"><path d="M12 3v6M12 15v6M3 12h6M15 12h6" stroke="#0f7e7a" stroke-width="2" stroke-linecap="round"/><circle cx="12" cy="12" r="2.6" stroke="#0f7e7a" stroke-width="2"/></svg></div><div class="h">Hybride</div><p>Autonome sur les questions que vous avez validées, suggestion seule pour tout le reste. C'est là que la plupart des équipes se stabilisent.</p></div><div class="fc"><div class="ic"><svg width="19" height="19" viewBox="0 0 24 24" fill="none"><path d="M12 2l8 4v6c0 5-3.4 8.8-8 10-4.6-1.2-8-5-8-10V6l8-4z" stroke="#0f7e7a" stroke-width="2" stroke-linejoin="round"/></svg></div><div class="h">Désactivé</div><p>Aucune intervention de l'IA. La base de connaissances alimente toujours les réponses enregistrées côté agent.</p></div></div>
<h3>Un déploiement raisonnable</h3>
<ol class="numbered"><li><span>Fonctionnez en mode suggestion pendant une semaine et observez ses brouillons. Vous repérerez vite les trous de votre FAQ.</span></li><li><span>Comblez ces trous. Les brouillons s'améliorent immédiatement parce que la source s'est améliorée.</span></li><li><span>Passez en autonome les questions qu'il traite systématiquement bien, et laissez le reste en suggestion.</span></li><li><span>Revoyez les chiffres de déflexion chaque mois et élargissez le périmètre autonome à mesure que la confiance grandit.</span></li></ol>
<div class="note amber"><svg width="17" height="17" viewBox="0 0 24 24" fill="none"><path d="M12 8v5" stroke="#92400e" stroke-width="2.2" stroke-linecap="round"/><circle cx="12" cy="16.5" r="1.2" fill="#92400e"/><circle cx="12" cy="12" r="9" stroke="#92400e" stroke-width="2"/></svg><div class="m"><div class="h">Ne commencez pas en mode autonome</div><p>Le mode suggestion n'est pas une version d'essai : c'est ainsi que vous découvrez ce qui manque à votre base de connaissances, sans qu'un client soit celui qui le découvre.</p></div></div>
</section>
<section id="grounding"><h2>Comment il reste exact</h2>
<p>Un agent de support IA ne vaut que ce qu'on l'autorise à dire. Deux mécanismes maintiennent l'agent wavadesk dans le cadre.</p>
<h3>Il ne répond qu'à partir de votre base de connaissances</h3>
<p>La source de vérité de l'agent est ce que vous importez : votre FAQ, vos politiques, vos conditions de livraison, vos horaires, vos règles de retour. Il ne répond pas à partir de connaissances générales, ce qui signifie qu'il ne peut pas inventer avec assurance une politique de remboursement que vous n'avez pas.</p>
<h3>Il escalade quand il ne sait pas</h3>
<p>Quand un message sort du périmètre de vos connaissances, ou correspond à un mot-clé d'escalade, l'agent s'arrête et confie la conversation à un humain plutôt que de produire quelque chose de plausible. Ne pas répondre est traité comme le bon résultat, pas comme un échec.</p>
<ul><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>Des réponses tirées de votre FAQ et de vos politiques importées</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>Des réponses formulées dans votre ton, car votre texte source le détermine</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>Aucune réponse inventée quand la connaissance manque</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>Les mots-clés d'escalade imposent un transfert immédiat</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>Chaque réponse automatique journalisée et attribuable dans le journal d'audit</span></li></ul>
</section>
<section id="escalation"><h2>Escalade et transfert</h2>
<p>Le moment où l'IA s'arrête compte plus que celui où elle démarre. Un litige de remboursement, une réclamation, une menace juridique ou un client en détresse doivent atteindre une personne immédiatement, et ne jamais tourner en boucle avec un robot.</p>
<p>Vous définissez des mots-clés d'escalade — des mots et expressions qui signifient qu'un humain est requis. Dès que l'un apparaît, l'IA se retire, la conversation passe dans la file de l'équipe concernée et un agent la prend en charge normalement. Le client n'est pas informé du transfert ; la conversation se poursuit simplement.</p>
<h3>Déclencheurs d'escalade typiques</h3>
<ul><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>Vocabulaire de réclamation et de litige : remboursement, rétrofacturation, plainte, avocat</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>Signaux de ton : messages répétés en rafale, majuscules, insultes</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>Comptes stratégiques nommés que vous voulez toujours confier à une personne</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>Sujets que vous avez délibérément exclus de l'automatisation</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>Toute question pour laquelle la base de connaissances ne renvoie rien de fiable</span></li></ul>
<div class="note"><svg width="17" height="17" viewBox="0 0 24 24" fill="none"><circle cx="12" cy="12" r="9" stroke="#0f7e7a" stroke-width="2"/><path d="M12 11v5" stroke="#0f7e7a" stroke-width="2" stroke-linecap="round"/><circle cx="12" cy="7.8" r="1.1" fill="#0f7e7a"/></svg><div class="m"><div class="h">L'escalade est immédiate, pas coincée derrière le robot</div><p>L'IA ne tente pas une réponse de plus avant de transmettre. Dès qu'un déclencheur s'active, elle s'arrête.</p></div></div>
</section>
<section id="measure"><h2>Mesurer si cela fonctionne</h2>
<p>Le chiffre qui compte n'est pas le nombre de messages envoyés par l'IA. C'est le nombre de conversations qu'elle a closes sans humain, et si celles qu'elle a escaladées étaient les bonnes.</p>
<figure><div class="shot"><img src="/img/features/ai-performance.png" alt="Panneau de performance de l'IA montrant le taux de déflexion, le temps de réponse médian et le nombre d'escalades sous forme de barre empilée" loading="lazy" decoding="async" width="2552" height="438"></div><figcaption><svg width="13" height="13" viewBox="0 0 24 24" fill="none"><rect x="2.5" y="6" width="19" height="14" rx="2.5" stroke="currentColor" stroke-width="2"/><circle cx="12" cy="13" r="3.4" stroke="currentColor" stroke-width="2"/><path d="M8.5 6l1.2-2h4.6L15.5 6" stroke="currentColor" stroke-width="2" stroke-linejoin="round"/></svg><span>La performance de l'IA sur le tableau de bord : résolu sans agent, assisté par l'IA, et escaladé — en proportion plutôt qu'en nombre brut de messages.</span></figcaption></figure>
<p>Trois chiffres vous disent presque tout. Le taux de déflexion est la part des conversations que l'IA a résolues de bout en bout. La médiane du temps de réponse de l'IA montre l'avantage de vitesse sur une file humaine. Le nombre d'escalades est votre soupape de sécurité — s'il tombe à zéro, l'agent répond probablement à des choses qu'il devrait transmettre.</p>
<div class="stats"><div class="sc"><b>68 %</b><span>résolues sans agent dans l'espace de travail de référence</span></div><div class="sc"><b>2,4 s</b><span>temps de réponse médian de l'IA</span></div><div class="sc"><b>31</b><span>escaladées vers un humain, délibérément</span></div></div>
<p>Le reporting complet est traité dans <a href="/features/reports-analytics">Rapports et statistiques du support</a>.</p>
</section>
<section id="cost"><h2>Comment l'usage de l'IA est facturé</h2>
<p>Les réponses de l'IA sont comptées comme des messages IA. Chaque offre inclut un quota mensuel, et vous pouvez ajouter des packs sans changer d'offre si un mois chargé se prolonge.</p>
<div class="tw"><table><thead><tr><th>Offre</th><th>Messages IA inclus</th><th>S'il vous en faut plus</th></tr></thead><tbody><tr><td>Starter</td><td>1 000 / mois</td><td>Ajouter des packs de 2 500 messages</td></tr><tr><td>Growth</td><td>5 000 / mois</td><td>Ajouter des packs de 2 500 messages</td></tr><tr><td>Scale</td><td>Illimité</td><td>Aucun plafond, aucun pack nécessaire</td></tr></tbody></table></div>
<figure><div class="shot"><img src="/img/features/usage-meters.png" alt="Jauges d'utilisation montrant les messages IA consommés par rapport au quota mensuel" loading="lazy" decoding="async" width="1760" height="322"></div><figcaption><svg width="13" height="13" viewBox="0 0 24 24" fill="none"><rect x="2.5" y="6" width="19" height="14" rx="2.5" stroke="currentColor" stroke-width="2"/><circle cx="12" cy="13" r="3.4" stroke="currentColor" stroke-width="2"/><path d="M8.5 6l1.2-2h4.6L15.5 6" stroke="currentColor" stroke-width="2" stroke-linejoin="round"/></svg><span>La consommation est visible dans la facturation avant d'atteindre le plafond, avec la possibilité d'ajouter un pack en cours de cycle.</span></figcaption></figure>
<p>Les conversations WhatsApp elles-mêmes sont toujours illimitées sur toutes les offres — il n'y a ni frais par message ni frais de conversation Meta. Seules les réponses de l'IA sont comptées.</p>
</section>
