{{-- Corps d'article français pour /features/api-integrations.
     Structure identique à la version anglaise : seul le texte change, afin
     que les ancres de sommaire de config/seo_pages.php restent valides. --}}
<section id="why"><h2>À quoi sert l'intégration</h2>
<p>La valeur d'un outil de support se multiplie quand il sait ce que votre entreprise sait déjà. Un agent qui répond à « où est ma commande » ne devrait pas chercher un numéro de commande dans un second système — cette information devrait déjà être à l'écran.</p>
<p>L'intégration fonctionne dans les deux sens. Vous injectez du contexte, pour que les agents et l'IA s'en servent. Et vous récupérez des événements, pour que vos propres systèmes réagissent quand quelque chose se passe au support.</p>
<div class="cards"><div class="fc"><div class="ic"><svg width="19" height="19" viewBox="0 0 24 24" fill="none"><path d="M8 6l-5 6 5 6M16 6l5 6-5 6" stroke="#0f7e7a" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/></svg></div><div class="h">API REST</div><p>Lisez et écrivez conversations, contacts, étiquettes et messages depuis votre propre backend.</p></div><div class="fc"><div class="ic"><svg width="19" height="19" viewBox="0 0 24 24" fill="none"><path d="M4 13h6l-1 8 9-12h-6l1-8z" stroke="#0f7e7a" stroke-width="2" stroke-linejoin="round"/></svg></div><div class="h">Webhooks</div><p>Recevez un événement quand une conversation est créée, prise en charge, répondue, résolue ou escaladée.</p></div><div class="fc"><div class="ic"><svg width="19" height="19" viewBox="0 0 24 24" fill="none"><circle cx="8" cy="12" r="4.2" stroke="#0f7e7a" stroke-width="2"/><path d="M12 12h9M17 12v4" stroke="#0f7e7a" stroke-width="2" stroke-linecap="round"/></svg></div><div class="h">API OTP</div><p>Envoyez et vérifiez des codes à usage unique par WhatsApp depuis votre application.</p></div><div class="fc"><div class="ic"><svg width="19" height="19" viewBox="0 0 24 24" fill="none"><path d="M4 20V10M10 20V4M16 20v-7M22 20H2" stroke="#0f7e7a" stroke-width="2" stroke-linecap="round"/></svg></div><div class="h">Export des rapports</div><p>Récupérez les indicateurs derrière le tableau de bord pour votre BI ou votre entrepôt de données.</p></div></div>
</section>
<section id="auth"><h2>Authentification</h2>
<p>L'accès à l'API utilise un jeton porteur limité à un espace de travail, créé dans les réglages et révocable à tout moment. Les jetons sont cantonnés à un espace de travail : un jeton d'un client ne peut pas lire celui d'un autre.</p>
<p>Les requêtes se font en HTTPS vers le point de terminaison de votre espace de travail, avec le jeton dans un en-tête Authorization. Il n'y a pas d'étape de signature séparée pour les appels REST ; les livraisons de webhooks, elles, sont signées pour que vous puissiez vérifier qu'elles viennent bien de nous.</p>
<ul><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>Un jeton porteur par espace de travail, créé et révoqué dans les réglages</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>Cantonné, de sorte qu'un jeton ne peut rien lire hors de son espace de travail</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>Des charges utiles de webhook signées avec un secret partagé pour vérification</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>Une limitation de débit par jeton, les limites étant renvoyées dans les en-têtes de réponse</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>Chaque action d'API enregistrée dans le même journal d'audit que les actions humaines</span></li></ul>
<div class="note amber"><svg width="17" height="17" viewBox="0 0 24 24" fill="none"><path d="M12 8v5" stroke="#92400e" stroke-width="2.2" stroke-linecap="round"/><circle cx="12" cy="16.5" r="1.2" fill="#92400e"/><circle cx="12" cy="12" r="9" stroke="#92400e" stroke-width="2"/></svg><div class="m"><div class="h">Traitez les jetons comme des identifiants</div><p>Un jeton d'espace de travail peut lire votre historique de conversations. Gardez-le côté serveur — jamais dans du code front-end ni dans le binaire d'une application mobile.</p></div></div>
</section>
<section id="rest"><h2>Ce que couvre l'API REST</h2>
<p>L'API est organisée autour des mêmes objets que l'interface : ce que vous voyez, vous pouvez généralement le lire et l'écrire.</p>
<div class="tw"><table><thead><tr><th>Ressource</th><th>Ce que vous pouvez faire</th></tr></thead><tbody><tr><td>Conversations</td><td>Lister, filtrer par canal ou statut, lire les messages, créer, prendre en charge, affecter, résoudre</td></tr><tr><td>Messages</td><td>Envoyer dans une conversation, lire l'historique, joindre des notes internes</td></tr><tr><td>Contacts</td><td>Créer, mettre à jour, rechercher par téléphone ou e-mail, fusionner, ajouter des champs personnalisés</td></tr><tr><td>Étiquettes</td><td>Appliquer et retirer, lister par conversation ou par contact</td></tr><tr><td>Équipes et agents</td><td>Lister, lire la disponibilité, lire l'affectation</td></tr><tr><td>Rapports</td><td>Récupérer les indicateurs derrière le tableau de bord sur une période</td></tr><tr><td>OTP</td><td>Envoyer un code, vérifier un code</td></tr></tbody></table></div>
<h3>La première intégration la plus courante</h3>
<p>Pousser le contexte client sur la fiche contact. Si votre système connaît l'historique de commandes, l'offre ou le statut de compte d'un client, l'écrire en champs personnalisés sur le contact permet à l'agent de le voir dans le panneau de contexte sans quitter la conversation.</p>
</section>
<section id="webhooks"><h2>Webhooks et événements</h2>
<p>Les webhooks permettent à vos systèmes de réagir à l'activité du support au lieu de l'interroger en boucle. Vous enregistrez un point de terminaison, choisissez les événements qui vous intéressent, et nous envoyons une charge utile signée en POST quand ils surviennent.</p>
<h3>Événements auxquels vous pouvez vous abonner</h3>
<ul><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>conversation.created — une nouvelle conversation est arrivée sur un canal</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>conversation.claimed — un agent en a pris possession</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>conversation.resolved — marquée résolue, avec l'agent qui l'a résolue</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>conversation.escalated — l'IA a transmis la main, avec le déclencheur</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>message.received — un message entrant d'un client</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>message.sent — une réponse sortante, humaine ou IA</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>contact.created et contact.updated</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>otp.verified — un code a été vérifié avec succès</span></li></ul>
<h3>Usages concrets</h3>
<p>Trois intégrations couvrent l'essentiel de ce que construisent les équipes. Créer une activité CRM sur <code>conversation.resolved</code>, pour que l'historique de support apparaisse sur le compte. Alerter un canal Slack sur <code>conversation.escalated</code> pour les comptes nommés. Débloquer une fonctionnalité de votre produit sur <code>otp.verified</code>.</p>
<div class="note"><svg width="17" height="17" viewBox="0 0 24 24" fill="none"><circle cx="12" cy="12" r="9" stroke="#0f7e7a" stroke-width="2"/><path d="M12 11v5" stroke="#0f7e7a" stroke-width="2" stroke-linecap="round"/><circle cx="12" cy="7.8" r="1.1" fill="#0f7e7a"/></svg><div class="m"><div class="h">Les livraisons sont réessayées</div><p>Un webhook en échec est réessayé avec un délai croissant. Répondez rapidement en 2xx et faites le travail de façon asynchrone — un traitement long à l'intérieur de la requête déclenchera l'expiration et provoquera des livraisons en double.</p></div></div>
</section>
<section id="otp"><h2>Les points de terminaison OTP</h2>
<p>Deux appels, et aucun état à conserver de votre côté. Le code est généré, haché et stocké chez nous, et ne vous est jamais renvoyé.</p>
<div class="steps"><div class="step"><span class="n">1</span><div class="m"><div class="h">POST pour envoyer</div><p>Avec le numéro de téléphone et une étiquette d'objet facultative comme connexion ou inscription. Renvoie un identifiant de requête, pas le code.</p></div></div><div class="step"><span class="n">2</span><div class="m"><div class="h">Le client le reçoit sur WhatsApp</div><p>Depuis votre numéro professionnel connecté.</p></div></div><div class="step"><span class="n">3</span><div class="m"><div class="h">POST pour vérifier</div><p>Avec le numéro et le code saisi par le client. Renvoie un succès ou un échec.</p></div></div><div class="step"><span class="n">4</span><div class="m"><div class="h">Traitez le motif d'échec</div><p>Les échecs reviennent différenciés : incorrect, expiré ou limite de tentatives dépassée — pour que vous affichiez le bon message.</p></div></div></div>
<p>L'expiration, les limites de tentatives et la limitation de débit par numéro sont appliquées côté serveur. Détail complet dans <a href="/features/otp-service">OTP et vérification WhatsApp</a>.</p>
</section>
<section id="widget"><h2>Intégration et widget</h2>
<p>Le widget de chat est lui-même un point d'intégration. Au-delà du snippet d'installation, vous pouvez identifier le visiteur depuis votre propre application afin que la conversation soit reliée à un contact connu plutôt qu'à une session anonyme.</p>
<p>Appeler la méthode d'identification avec les informations de votre utilisateur au chargement de la page permet à l'agent de voir un client identifié avec tout son historique multicanal au lieu d'un visiteur anonyme.</p>
<figure><div class="shot"><img src="/img/features/livechat-settings.png" alt="Écran de réglages du chat en direct avec le snippet d'installation et les options de configuration" loading="lazy" decoding="async" width="3186" height="1766"></div><figcaption><svg width="13" height="13" viewBox="0 0 24 24" fill="none"><rect x="2.5" y="6" width="19" height="14" rx="2.5" stroke="currentColor" stroke-width="2"/><circle cx="12" cy="13" r="3.4" stroke="currentColor" stroke-width="2"/><path d="M8.5 6l1.2-2h4.6L15.5 6" stroke="currentColor" stroke-width="2" stroke-linejoin="round"/></svg><span>Le snippet d'installation et la configuration du widget se trouvent dans le même écran de réglages, à côté d'un aperçu en direct.</span></figcaption></figure>
<p>Voir <a href="/features/live-chat-widget">Widget de chat en direct</a> pour l'installation et l'identité visuelle.</p>
</section>
<section id="limits"><h2>Limites et versions</h2>
<p>Deux choses à savoir avant de développer sur une API : jusqu'où vous pouvez la solliciter, et si elle va changer sous vos pieds.</p>
<ul><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>Des limites de débit par jeton, le quota restant étant renvoyé dans les en-têtes de réponse</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>Les réponses 429 incluent une valeur retry-after</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>Les changements cassants sont livrés derrière une version, et les versions existantes restent prises en charge</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>Les ajouts — nouveaux champs et nouveaux types d'événements — peuvent arriver sans changement de version : analysez de façon défensive</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>Les charges utiles de webhook sont versionnées en même temps que l'API</span></li></ul>
<p>L'accès à l'API est inclus dans l'offre Scale. Consultez <a href="{{ url('/#pricing') }}">les tarifs</a>.</p>
</section>
