{{-- Corps d'article français pour /features/knowledge-base.
     Structure identique à la version anglaise : seul le texte change, afin
     que les ancres de sommaire de config/seo_pages.php restent valides. --}}
<section id="why"><h2>Pourquoi une source unique compte</h2>
<p>Chaque équipe de support possède une base de connaissances non écrite : les réponses vivent dans la tête des deux personnes présentes depuis le plus longtemps. Cela fonctionne jusqu'à ce que l'une soit en congé, qu'un nouvel agent arrive, ou que deux agents donnent au client deux versions de la politique de retour dans la même semaine.</p>
<p>L'écrire n'est pas le plus difficile. En garder une seule version, si. Le mode de défaillance n'est pas une base vide — ce sont trois bases : un document d'intégration, des bouts de texte dans les notes de quelqu'un, et ce avec quoi l'IA a été configurée il y a six mois.</p>
<p>Dans wavadesk il y a un seul référentiel, et il alimente trois usages : <strong>l'agent IA</strong>, qui y puise ses réponses ; <strong>les réponses enregistrées</strong>, que vos agents insèrent ; et à terme du contenu en libre-service, pour que les clients trouvent leurs réponses sans écrire. Mettez la source à jour et les trois changent.</p>
<div class="cards"><div class="fc"><div class="ic"><svg width="19" height="19" viewBox="0 0 24 24" fill="none"><path d="M13 2 4 14h6l-1 8 9-12h-6l1-8z" fill="#0f7e7a"/></svg></div><div class="h">Alimente l'IA</div><p>L'agent ne répond qu'à partir de ce contenu, dans vos termes, et escalade quand le sujet n'est pas couvert.</p></div><div class="fc"><div class="ic"><svg width="19" height="19" viewBox="0 0 24 24" fill="none"><path d="M4 4h16v12l-4 4H4z" stroke="#0f7e7a" stroke-width="2" stroke-linejoin="round"/><path d="M8 9h8M8 13h5" stroke="#0f7e7a" stroke-width="2" stroke-linecap="round"/></svg></div><div class="h">Alimente les réponses enregistrées</div><p>Les agents insèrent la réponse de référence au lieu de retaper une approximation.</p></div><div class="fc"><div class="ic"><svg width="19" height="19" viewBox="0 0 24 24" fill="none"><circle cx="11" cy="11" r="7" stroke="#0f7e7a" stroke-width="2"/><path d="M20 20l-3.5-3.5" stroke="#0f7e7a" stroke-width="2" stroke-linecap="round"/></svg></div><div class="h">Consultable par les agents</div><p>Quand quelqu'un a besoin de la formulation exacte d'une politique en pleine conversation, elle est à une recherche de distance.</p></div><div class="fc"><div class="ic"><svg width="19" height="19" viewBox="0 0 24 24" fill="none"><path d="M12 2l8 4v6c0 5-3.4 8.8-8 10-4.6-1.2-8-5-8-10V6l8-4z" stroke="#0f7e7a" stroke-width="2" stroke-linejoin="round"/></svg></div><div class="h">Auditable</div><p>Une seule version, avec l'historique de ce qui a changé et quand — ce qui compte quand une politique est contestée.</p></div></div>
</section>
<section id="structure"><h2>Comment la structurer</h2>
<p>L'instinct pousse à écrire de longs articles. Résistez-y. L'IA fait correspondre des questions et les agents insèrent des réponses — les deux fonctionnent mieux avec des entrées courtes et mono-sujet qu'avec un document de politique exhaustif.</p>
<h3>Une question, une entrée</h3>
<p>Une entrée doit répondre à exactement une chose. « Quels sont vos délais de livraison » et « Livrez-vous le dimanche » sont deux entrées même si les deux portent sur la livraison, car le client les pose séparément et les réponses diffèrent.</p>
<h3>Écrivez la réponse comme vous l'enverriez</h3>
<p>L'IA s'appuie sur votre texte pour formuler sa réponse : le ton de votre base de connaissances devient donc le ton de votre support automatisé. Rédigez les entrées comme des messages à un client, pas comme de la documentation interne.</p>
<div class="tw"><table><thead><tr><th>À faire</th><th>À éviter</th></tr></thead><tbody><tr><td>« La livraison standard prend 3 à 5 jours ouvrés. L'express arrive sous 24 heures. »</td><td>« POLITIQUE DE LIVRAISON : se référer au SLA logistique, section 4.2. »</td></tr><tr><td>Une entrée par question</td><td>Une entrée couvrant tous les sujets d'expédition</td></tr><tr><td>Un langage simple que le client lit</td><td>Du jargon interne et des noms de systèmes</td></tr><tr><td>Indiquer l'exception dans la même entrée</td><td>Laisser l'agent se souvenir du cas particulier</td></tr></tbody></table></div>
<h3>Traitez les exceptions explicitement</h3>
<p>La plupart des escalades ne sont pas des questions inhabituelles, ce sont les exceptions à une question courante. Si la livraison du dimanche n'existe que dans deux villes, écrivez-le dans l'entrée. Une entrée juste 90 % du temps apprend à votre équipe à se méfier de toute la base.</p>
</section>
<section id="ai"><h2>Comment l'IA l'utilise</h2>
<p>Quand un message arrive, l'agent le confronte à vos entrées et rédige une réponse ancrée dans celles qui correspondent. Il ne répond pas à partir de connaissances générales, et c'est pourquoi il ne peut pas inventer un délai de remboursement que vous ne proposez pas.</p>
<p>Quand rien ne correspond avec certitude, l'agent escalade plutôt que d'improviser. Votre base de connaissances devient ainsi le levier direct du taux d'automatisation : chaque trou comblé transforme une catégorie d'escalade en réponse automatique.</p>
<div class="note"><svg width="17" height="17" viewBox="0 0 24 24" fill="none"><circle cx="12" cy="12" r="9" stroke="#0f7e7a" stroke-width="2"/><path d="M12 11v5" stroke="#0f7e7a" stroke-width="2" stroke-linecap="round"/><circle cx="12" cy="7.8" r="1.1" fill="#0f7e7a"/></svg><div class="m"><div class="h">Le mode suggestion est un détecteur de lacunes</div><p>Faites tourner l'IA en mode suggestion pendant une semaine et lisez ses brouillons. Là où les brouillons sont faibles, votre base est mince — et c'est bien moins coûteux que de le découvrir via un client.</p></div></div>
<figure><div class="shot"><img src="/img/features/ai-performance.png" alt="Panneau de performance de l'IA montrant le taux de déflexion et le nombre d'escalades" loading="lazy" decoding="async" width="2552" height="438"></div><figcaption><svg width="13" height="13" viewBox="0 0 24 24" fill="none"><rect x="2.5" y="6" width="19" height="14" rx="2.5" stroke="currentColor" stroke-width="2"/><circle cx="12" cy="13" r="3.4" stroke="currentColor" stroke-width="2"/><path d="M8.5 6l1.2-2h4.6L15.5 6" stroke="currentColor" stroke-width="2" stroke-linejoin="round"/></svg><span>Le taux de déflexion est la mesure concrète de la couverture de la base de connaissances. Il monte à mesure que les trous se comblent.</span></figcaption></figure>
</section>
<section id="saved"><h2>Réponses enregistrées pour les agents</h2>
<p>Même avec une IA qui traite le cas courant, les agents tapent beaucoup de messages quasi identiques : demander un numéro de commande, expliquer une procédure de retour, confirmer un changement d'adresse. Les réponses enregistrées en font une insertion plutôt qu'une rédaction.</p>
<ul><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>Insérer une réponse de référence dans l'éditeur via un raccourci clavier</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>Modifier avant d'envoyer, car la conversation autour appelle toujours une phrase propre</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>Des variables pour le nom du client et la référence de commande, remplies depuis la conversation</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>Organisées par équipe, pour que les textes de facturation n'encombrent pas la file commerciale</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>Même source que l'IA, pour qu'un agent et le robot ne se contredisent jamais</span></li></ul>
<p>La discipline qui compte : quand un agent modifie sans cesse la même réponse enregistrée de la même façon, cette modification a sa place dans la source. Sinon vous avez recréé le problème de la connaissance éparpillée à l'intérieur de l'outil.</p>
</section>
<section id="maintain"><h2>La maintenir à jour</h2>
<p>Une base de connaissances se dégrade. Les prix changent, les politiques changent, un produit est arrêté et l'entrée qui le décrit devient discrètement fausse. Rien dans l'outil n'empêche cela — seule une habitude de relecture le fait.</p>
<div class="steps"><div class="step"><span class="n">1</span><div class="m"><div class="h">Passez les escalades en revue chaque semaine</div><p>Les escalades sont votre liste de lacunes. Une escalade récurrente sur le même sujet signale une entrée manquante ou fausse.</p></div></div><div class="step"><span class="n">2</span><div class="m"><div class="h">Observez quelles réponses enregistrées sont modifiées</div><p>Des modifications systématiques signifient que la formulation de référence est périmée.</p></div></div><div class="step"><span class="n">3</span><div class="m"><div class="h">Mettez à jour à la source du changement</div><p>Quand une politique change, l'entrée de la base fait partie de la mise en œuvre du changement, pas d'une tâche à faire plus tard.</p></div></div><div class="step"><span class="n">4</span><div class="m"><div class="h">Élaguez ce qui est mort</div><p>Une entrée fausse est pire qu'une entrée manquante, car l'IA l'utilisera avec assurance.</p></div></div></div>
<div class="note amber"><svg width="17" height="17" viewBox="0 0 24 24" fill="none"><path d="M12 8v5" stroke="#92400e" stroke-width="2.2" stroke-linecap="round"/><circle cx="12" cy="16.5" r="1.2" fill="#92400e"/><circle cx="12" cy="12" r="9" stroke="#92400e" stroke-width="2"/></svg><div class="m"><div class="h">Un responsable, pas tout le monde</div><p>Les bases de connaissances pourrissent le plus vite quand personne n'en est responsable et que tout le monde peut les modifier. Donnez le dernier mot sur la formulation à une seule personne, l'équipe alimentant les suggestions.</p></div></div>
</section>
