{{-- Corps d'article français pour /features/live-chat-widget.
     Structure identique à la version anglaise : seul le texte change, afin
     que les ancres de sommaire de config/seo_pages.php restent valides. --}}
<section id="why"><h2>Pourquoi une seule boîte pour les deux canaux</h2>
<p>Ajouter un chat en direct à un site est facile. L'ajouter sans fragmenter votre organisation de support, voilà le difficile. Le résultat habituel : deux outils, deux files et deux historiques, des agents qui basculent de l'un à l'autre et personne capable de rendre compte de l'ensemble.</p>
<p>wavadesk traite le canal comme un attribut de la conversation, pas comme un produit distinct. Un chat de site et un fil WhatsApp apparaissent dans la même liste, se prennent en charge de la même façon et se répondent depuis le même éditeur. La seule différence est un badge indiquant à l'agent d'où vient la conversation.</p>
<figure><div class="shot"><img src="/img/features/inbox-full.png" alt="Boîte de réception partagée affichant les conversations WhatsApp et chat en direct dans une seule liste avec des badges de canal" loading="lazy" decoding="async" width="3186" height="1766"></div><figcaption><svg width="13" height="13" viewBox="0 0 24 24" fill="none"><rect x="2.5" y="6" width="19" height="14" rx="2.5" stroke="currentColor" stroke-width="2"/><circle cx="12" cy="13" r="3.4" stroke="currentColor" stroke-width="2"/><path d="M8.5 6l1.2-2h4.6L15.5 6" stroke="currentColor" stroke-width="2" stroke-linejoin="round"/></svg><span>Les conversations WhatsApp et celles du site dans une seule file. Le badge sur chaque avatar est la seule chose qui les distingue.</span></figcaption></figure>
<div class="cards"><div class="fc"><div class="ic"><svg width="19" height="19" viewBox="0 0 24 24" fill="none"><path d="M21 11.5a8.4 8.4 0 01-9 8.4 8.9 8.9 0 01-3.9-.9L3 20.5l1.5-4.6A8.4 8.4 0 013.6 11.5a8.4 8.4 0 018.4-8.4 8.4 8.4 0 019 8.4z" stroke="#0f7e7a" stroke-width="2" stroke-linejoin="round"/></svg></div><div class="h">Une seule file</div><p>Filtrez par canal quand vous le souhaitez, mais rien n'est caché dans un second outil.</p></div><div class="fc"><div class="ic"><svg width="19" height="19" viewBox="0 0 24 24" fill="none"><path d="M16 20v-2a4 4 0 00-4-4H6a4 4 0 00-4 4v2" stroke="#0f7e7a" stroke-width="2" stroke-linecap="round"/><circle cx="9" cy="7" r="3.4" stroke="#0f7e7a" stroke-width="2"/><path d="M22 20v-2a4 4 0 00-3-3.9" stroke="#0f7e7a" stroke-width="2" stroke-linecap="round"/></svg></div><div class="h">Un seul client</div><p>Un visiteur qui écrit ensuite sur WhatsApp conserve le même historique, et ne repart pas de zéro.</p></div><div class="fc"><div class="ic"><svg width="19" height="19" viewBox="0 0 24 24" fill="none"><path d="M13 2 4 14h6l-1 8 9-12h-6l1-8z" fill="#0f7e7a"/></svg></div><div class="h">Un seul agent IA</div><p>La même base de connaissances répond sur les deux canaux, les réponses ne peuvent donc pas diverger.</p></div><div class="fc"><div class="ic"><svg width="19" height="19" viewBox="0 0 24 24" fill="none"><path d="M4 20V10M10 20V4M16 20v-7M22 20H2" stroke="#0f7e7a" stroke-width="2" stroke-linecap="round"/></svg></div><div class="h">Un seul jeu de chiffres</div><p>Temps de réponse et volume mesurés tous canaux confondus et par canal.</p></div></div>
</section>
<section id="install"><h2>Installer le widget</h2>
<p>L'installation tient en une seule balise script placée avant la balise de fermeture body de votre site. Il n'y a ni étape de compilation ni exigence de framework — cela fonctionne sur un site statique, WordPress, Shopify, une application Laravel ou tout autre support servant du HTML.</p>
<div class="steps"><div class="step"><span class="n">1</span><div class="m"><div class="h">Copiez le snippet</div><p>Votre espace de travail génère un snippet contenant votre clé de widget unique.</p></div></div><div class="step"><span class="n">2</span><div class="m"><div class="h">Collez-le dans votre site</div><p>Avant la balise de fermeture body, sur chaque page où vous voulez le chat. La plupart des équipes l'ajoutent à un gabarit commun ou au pied de page.</p></div></div><div class="step"><span class="n">3</span><div class="m"><div class="h">Vérifiez la connexion</div><p>Ouvrez votre site, envoyez un message de test et regardez-le apparaître dans la boîte partagée.</p></div></div><div class="step"><span class="n">4</span><div class="m"><div class="h">Réglez le comportement</div><p>Choisissez le message d'accueil, la position, les horaires et si l'IA répond en premier.</p></div></div></div>
<figure><div class="shot"><img src="/img/features/livechat-settings.png" alt="Écran de réglages du chat en direct avec la configuration du widget et un panneau d'aperçu en direct" loading="lazy" decoding="async" width="3186" height="1766"></div><figcaption><svg width="13" height="13" viewBox="0 0 24 24" fill="none"><rect x="2.5" y="6" width="19" height="14" rx="2.5" stroke="currentColor" stroke-width="2"/><circle cx="12" cy="13" r="3.4" stroke="currentColor" stroke-width="2"/><path d="M8.5 6l1.2-2h4.6L15.5 6" stroke="currentColor" stroke-width="2" stroke-linejoin="round"/></svg><span>L'écran de réglages comporte un aperçu en direct : vous voyez l'effet de chaque changement avant de le publier.</span></figcaption></figure>
<div class="note"><svg width="17" height="17" viewBox="0 0 24 24" fill="none"><circle cx="12" cy="12" r="9" stroke="#0f7e7a" stroke-width="2"/><path d="M12 11v5" stroke="#0f7e7a" stroke-width="2" stroke-linecap="round"/><circle cx="12" cy="7.8" r="1.1" fill="#0f7e7a"/></svg><div class="m"><div class="h">Aucune installation côté client</div><p>Les visiteurs n'ont besoin de rien. Le widget se charge sur votre page et la conversation y commence.</p></div></div>
</section>
<section id="customise"><h2>Identité visuelle et comportement</h2>
<p>Le widget doit sembler appartenir à votre site, pas à un prestataire de support. Tout ce que voit le visiteur est configurable, avec un aperçu en direct à côté des réglages.</p>
<h3>Ce que vous pouvez modifier</h3>
<ul><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>La couleur d'accent, pour que le lanceur corresponde à votre marque</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>La position du lanceur, à gauche ou à droite, avec un décalage pour d'autres éléments flottants</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>Le message d'accueil et une courte phrase d'introduction, par langue</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>Les horaires de disponibilité, et ce que le widget affiche en dehors</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>Si l'agent IA répond en premier ou si la conversation attend une personne</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>Des champs de pré-chat, si vous voulez un nom ou un e-mail avant le début de la conversation</span></li></ul>
<h3>Multilingue</h3>
<p>Les textes du widget se définissent par langue : un visiteur francophone voit du français et un visiteur arabophone voit de l'arabe. L'agent IA répond dans la langue dans laquelle le visiteur écrit, en s'appuyant sur la même base de connaissances.</p>
</section>
<section id="context"><h2>Un contexte visiteur exploitable par vos agents</h2>
<p>Un visiteur de site est anonyme par défaut, ce qui semble un inconvénient jusqu'à ce qu'on remarque tout ce que la session révèle. Quelqu'un qui reste quatre minutes sur votre page tarifs ne pose pas la même question que quelqu'un qui vient d'arriver sur l'accueil.</p>
<p>Le panneau de contexte montre la session plutôt qu'une fiche contact : la page consultée, la manière d'arriver, le navigateur et l'appareil, le temps passé sur le site et les pages visitées en chemin.</p>
<ul><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>La page en cours, pour que l'agent sache ce que le visiteur regarde</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>Le parcours de navigation, qui révèle souvent mieux l'intention que le premier message</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>Le navigateur, l'appareil et le système d'exploitation, pour le dépannage</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>Le référent, pour savoir s'ils viennent d'une publicité ou d'une recherche</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>Le temps passé sur le site et le début de session</span></li></ul>
<p>Si le visiteur s'identifie — par un champ de pré-chat ou en donnant un e-mail dans la conversation — la session est reliée à un contact et son historique sur les autres canaux apparaît.</p>
</section>
<section id="ai"><h2>L'IA sur le widget</h2>
<p>Le chat de site n'a pas les mêmes attentes que WhatsApp. Un visiteur sur votre page tarifs attend une réponse en quelques secondes, et fermera l'onglet plutôt que d'attendre. C'est là que l'IA autonome rapporte le plus.</p>
<p>Le même agent IA, la même base de connaissances et les mêmes règles d'escalade s'appliquent. Vous pouvez toutefois définir un mode différent par canal : beaucoup d'équipes utilisent le mode autonome sur le widget pour des réponses instantanées, et la suggestion seule sur WhatsApp, où une réponse humaine légèrement plus lente est acceptable.</p>
<div class="note"><svg width="17" height="17" viewBox="0 0 24 24" fill="none"><circle cx="12" cy="12" r="9" stroke="#0f7e7a" stroke-width="2"/><path d="M12 11v5" stroke="#0f7e7a" stroke-width="2" stroke-linecap="round"/><circle cx="12" cy="7.8" r="1.1" fill="#0f7e7a"/></svg><div class="m"><div class="h">L'escalade s'applique toujours</div><p>Un visiteur qui pose une question de remboursement ou emploie un mot déclencheur est confié à un humain sur le widget exactement comme il le serait sur WhatsApp.</p></div></div>
<p>Plus de détails dans <a href="/features/ai-agent">Agent IA pour le support</a>.</p>
</section>
<section id="perf"><h2>Performance et confidentialité</h2>
<p>Un widget de chat est présent sur chaque page de votre site : son poids devient le vôtre. Le widget wavadesk se charge de façon asynchrone et ne bloque pas le rendu — le lanceur apparaît une fois votre page interactive, pas avant.</p>
<ul><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>Chargement asynchrone, sans blocage du rendu</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>Aucun pixel publicitaire ou de suivi tiers embarqué</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>Des données de session limitées à ce qu'affiche le panneau de contexte</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>Des conversations stockées dans votre espace de travail, non partagées entre clients</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>Le widget respecte vos horaires de disponibilité au lieu de laisser croire que quelqu'un est présent</span></li></ul>
</section>
