{{-- Corps d'article français pour /features/otp-service.
     Structure identique à la version anglaise : seul le texte change, afin
     que les ancres de sommaire de config/seo_pages.php restent valides. --}}
<section id="what"><h2>Ce que fait le service OTP</h2>
<p>Les codes à usage unique sont le cheval de bataille de la sécurité des comptes : confirmation d'inscription, vérification à la connexion, réinitialisation de mot de passe, validation d'une transaction importante, vérification d'un numéro avant livraison. Presque tous les produits en ont besoin, et presque tous les envoient par SMS par défaut.</p>
<p>Le module OTP de wavadesk envoie ces codes par WhatsApp à la place. Vous appelez un point de terminaison avec un numéro, nous livrons un message contenant le code, et vous vérifiez le code saisi par le client via un second appel. La livraison, l'expiration et les limites de tentatives sont gérées pour vous.</p>
<div class="cards"><div class="fc"><div class="ic"><svg width="19" height="19" viewBox="0 0 24 24" fill="none"><circle cx="8" cy="12" r="4.2" stroke="#0f7e7a" stroke-width="2"/><path d="M12 12h9M17 12v4" stroke="#0f7e7a" stroke-width="2" stroke-linecap="round"/></svg></div><div class="h">Générer et envoyer</div><p>Une requête crée un code, le stocke haché et le délivre sur le WhatsApp du client.</p></div><div class="fc"><div class="ic"><svg width="19" height="19" viewBox="0 0 24 24" fill="none"><path d="M12 2l8 4v6c0 5-3.4 8.8-8 10-4.6-1.2-8-5-8-10V6l8-4z" stroke="#0f7e7a" stroke-width="2" stroke-linejoin="round"/></svg></div><div class="h">Vérifier</div><p>Une seconde requête contrôle le code saisi par le client, avec application des limites de tentatives et de l'expiration.</p></div><div class="fc"><div class="ic"><svg width="19" height="19" viewBox="0 0 24 24" fill="none"><circle cx="12" cy="12" r="9" stroke="#0f7e7a" stroke-width="2"/><path d="M12 7v5.4l3.4 2" stroke="#0f7e7a" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/></svg></div><div class="h">Gestion de l'expiration</div><p>Les codes expirent selon une fenêtre que vous définissez. Un code expiré est refusé plutôt que de traîner.</p></div><div class="fc"><div class="ic"><svg width="19" height="19" viewBox="0 0 24 24" fill="none"><path d="M4 20V10M10 20V4M16 20v-7M22 20H2" stroke="#0f7e7a" stroke-width="2" stroke-linecap="round"/></svg></div><div class="h">Rapports de livraison</div><p>Nombres d'envois, de livraisons et de vérifications, pour voir les abandons dans l'entonnoir plutôt que de les deviner.</p></div></div>
</section>
<section id="why"><h2>Pourquoi WhatsApp surpasse le SMS pour la vérification</h2>
<p>Ce n'est pas une question de préférence. Il existe quatre différences opérationnelles concrètes.</p>
<h3>Une livraison réellement vérifiable</h3>
<p>Le SMS vous donne un accusé de soumission d'un agrégateur, pas la preuve qu'un humain l'a vu. WhatsApp fournit les statuts de livraison et de lecture : quand un client dit que le code n'est jamais arrivé, vous pouvez vérifier au lieu de spéculer.</p>
<h3>Coût par vérification</h3>
<p>Le SMS est facturé par message et par pays, et les coûts de vérification à l'international grimpent vite. Les conversations WhatsApp sur wavadesk sont illimitées sur toutes les offres : le coût marginal d'une vérification supplémentaire est nul.</p>
<h3>Il arrive là où la conversation existe déjà</h3>
<p>Si votre client vous écrit déjà sur WhatsApp, le code apparaît dans un fil qu'il reconnaît, envoyé par un expéditeur avec qui il a déjà échangé. Cela réduit nettement le soupçon d'hameçonnage que créent les numéros courts SMS inconnus.</p>
<h3>Aucune validation de numéro court ou d'identifiant d'expéditeur</h3>
<p>L'enregistrement d'un expéditeur SMS varie selon les pays et peut prendre des semaines. Votre numéro WhatsApp est déjà connecté et déjà le vôtre.</p>
<div class="tw"><table><thead><tr><th></th><th>SMS</th><th>WhatsApp via wavadesk</th></tr></thead><tbody><tr><td>Coût par message</td><td>Par message et par pays</td><td>Inclus — conversations illimitées</td></tr><tr><td>Confirmation de réception</td><td>Accusé de soumission uniquement</td><td>Statuts livré et lu</td></tr><tr><td>Reconnaissance de l'expéditeur</td><td>Numéro court inconnu</td><td>Votre numéro professionnel existant</td></tr><tr><td>Mise en place</td><td>Validation d'identifiant d'expéditeur / numéro court</td><td>Déjà connecté par QR code</td></tr><tr><td>Contenu enrichi</td><td>160 caractères, sans mise en forme</td><td>Mise en forme et identité visuelle possibles</td></tr></tbody></table></div>
<div class="note amber"><svg width="17" height="17" viewBox="0 0 24 24" fill="none"><path d="M12 8v5" stroke="#92400e" stroke-width="2.2" stroke-linecap="round"/><circle cx="12" cy="16.5" r="1.2" fill="#92400e"/><circle cx="12" cy="12" r="9" stroke="#92400e" stroke-width="2"/></svg><div class="m"><div class="h">Gardez un repli SMS pour la couverture</div><p>Une petite part de clients n'aura pas WhatsApp. La plupart des équipes envoient d'abord par WhatsApp et basculent vers le SMS en cas de non-livraison — le module signale la non-livraison pour que vous puissiez déclencher ce repli.</p></div></div>
</section>
<section id="how"><h2>Comment cela fonctionne en pratique</h2>
<p>Deux points de terminaison, et aucun état à conserver de votre côté. Le code lui-même est généré, haché et stocké chez nous ; vous ne le détenez jamais.</p>
<div class="steps"><div class="step"><span class="n">1</span><div class="m"><div class="h">Demandez un code</div><p>Votre backend appelle le point d'envoi avec le numéro du client et une étiquette d'objet facultative, par exemple connexion ou inscription.</p></div></div><div class="step"><span class="n">2</span><div class="m"><div class="h">Le client le reçoit sur WhatsApp</div><p>Le message arrive depuis votre numéro professionnel connecté, dans la langue que vous indiquez.</p></div></div><div class="step"><span class="n">3</span><div class="m"><div class="h">Le client saisit le code</div><p>Dans votre application, votre site ou votre tunnel d'achat — là où se déroule la vérification.</p></div></div><div class="step"><span class="n">4</span><div class="m"><div class="h">Votre backend vérifie</div><p>Appelez le point de vérification avec le numéro et le code. Vous obtenez un succès ou un échec, avec le motif en cas d'échec : incorrect, expiré ou trop de tentatives.</p></div></div></div>
<div class="note"><svg width="17" height="17" viewBox="0 0 24 24" fill="none"><circle cx="12" cy="12" r="9" stroke="#0f7e7a" stroke-width="2"/><path d="M12 11v5" stroke="#0f7e7a" stroke-width="2" stroke-linecap="round"/><circle cx="12" cy="7.8" r="1.1" fill="#0f7e7a"/></svg><div class="m"><div class="h">Les codes ne vous sont jamais renvoyés</div><p>L'appel d'envoi ne retourne pas le code. La vérification passe par le point de vérification : une fuite dans vos journaux ne peut donc pas exposer de codes actifs.</p></div></div>
<p>Le détail des requêtes et des réponses se trouve dans <a href="/features/api-integrations">API et intégrations</a>.</p>
</section>
<section id="security"><h2>Contrôles de sécurité</h2>
<p>Un système d'OTP est lui-même un contrôle de sécurité : ses réglages par défaut comptent. Ceux-ci sont imposés, pas optionnels.</p>
<ul><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>Codes stockés hachés, jamais en clair, et jamais renvoyés par le point d'envoi</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>Fenêtre d'expiration configurable, avec une durée de vie courte par défaut</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>Limite de tentatives par code, au-delà de laquelle le code est brûlé et un nouveau doit être demandé</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>Limitation de débit par numéro, pour qu'un attaquant ne puisse pas se servir de votre point de terminaison pour harceler une victime</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>Limitation de débit par clé d'API, pour contenir un identifiant divulgué</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>Codes à usage unique — un code vérifié ne peut pas être rejoué</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>Journal d'audit complet de chaque envoi et de chaque tentative de vérification, horodaté</span></li></ul>
<h3>L'abus auquel il faut penser</h3>
<p>Le principal risque d'un point de terminaison OTP n'est pas la devinette de code, c'est d'être utilisé comme un canon à messages gratuit contre le téléphone d'un tiers. Les limites de débit par numéro sont la parade, et elles sont actives par défaut. Si vous exposez un formulaire d'inscription public, placez également un captcha ou équivalent devant l'appel d'envoi.</p>
</section>
<section id="reporting"><h2>Rapports de livraison et de conversion</h2>
<p>La vérification est un entonnoir, et les entonnoirs fuient. Les rapports montrent les envois, les livraisons et les vérifications réussies pour que vous voyiez où.</p>
<figure><div class="shot"><img src="/img/features/kpis.png" alt="Cartes d'indicateurs du tableau de bord avec mini-graphiques et écarts d'une période à l'autre" loading="lazy" decoding="async" width="2552" height="370"></div><figcaption><svg width="13" height="13" viewBox="0 0 24 24" fill="none"><rect x="2.5" y="6" width="19" height="14" rx="2.5" stroke="currentColor" stroke-width="2"/><circle cx="12" cy="13" r="3.4" stroke="currentColor" stroke-width="2"/><path d="M8.5 6l1.2-2h4.6L15.5 6" stroke="currentColor" stroke-width="2" stroke-linejoin="round"/></svg><span>Les volumes de livraison et de vérification des OTP apparaissent comme des indicateurs avec courbes de tendance, dans le même espace de reporting que le volume de conversations.</span></figcaption></figure>
<p>L'écart entre livré et vérifié est le chiffre à surveiller. Un écart important signifie généralement l'une de trois choses : votre écran de saisie du code est confus, votre fenêtre d'expiration est trop courte pour de vrais utilisateurs, ou vous vérifiez à un moment du parcours où les gens abandonnent de toute façon.</p>
<div class="stats"><div class="sc"><b>Envoyés</b><span>codes demandés par votre backend</span></div><div class="sc"><b>Livrés</b><span>confirmés comme arrivés sur le téléphone</span></div><div class="sc"><b>Vérifiés</b><span>codes correctement saisis par le client</span></div></div>
</section>
<section id="cases"><h2>Où les équipes l'utilisent</h2>
<div class="cards"><div class="fc"><div class="ic"><svg width="19" height="19" viewBox="0 0 24 24" fill="none"><path d="M12 2l8 4v6c0 5-3.4 8.8-8 10-4.6-1.2-8-5-8-10V6l8-4z" stroke="#0f7e7a" stroke-width="2" stroke-linejoin="round"/></svg></div><div class="h">Connexion et inscription</div><p>Confirmer un numéro à la création du compte, et renforcer la vérification à la connexion.</p></div><div class="fc"><div class="ic"><svg width="19" height="19" viewBox="0 0 24 24" fill="none"><circle cx="8" cy="12" r="4.2" stroke="#0f7e7a" stroke-width="2"/><path d="M12 12h9M17 12v4" stroke="#0f7e7a" stroke-width="2" stroke-linecap="round"/></svg></div><div class="h">Réinitialisation de mot de passe</div><p>Un code vers un numéro vérifié, sans dépendre de la délivrabilité des e-mails.</p></div><div class="fc"><div class="ic"><svg width="19" height="19" viewBox="0 0 24 24" fill="none"><rect x="3" y="5" width="18" height="16" rx="2.6" stroke="#0f7e7a" stroke-width="2"/><path d="M3 10h18M8 3v4M16 3v4" stroke="#0f7e7a" stroke-width="2" stroke-linecap="round"/></svg></div><div class="h">Confirmation de réservation</div><p>Vérifier le numéro avant de bloquer une réservation, ce qui réduit les réservations fictives.</p></div><div class="fc"><div class="ic"><svg width="19" height="19" viewBox="0 0 24 24" fill="none"><rect x="6" y="2.5" width="12" height="19" rx="2.6" stroke="#0f7e7a" stroke-width="2"/><path d="M11 18.5h2" stroke="#0f7e7a" stroke-width="2" stroke-linecap="round"/></svg></div><div class="h">Confirmation de réception</div><p>Confirmer le numéro du destinataire avant l'expédition, ce qui réduit les livraisons échouées.</p></div></div>
<p>Le module OTP est inclus dans l'offre Scale et disponible en option sur les autres. Consultez <a href="{{ url('/#pricing') }}">les tarifs</a>.</p>
</section>
