{{-- Corps d'article français pour /features/reports-analytics.
     Structure identique à la version anglaise : seul le texte change, afin
     que les ancres de sommaire de config/seo_pages.php restent valides. --}}
<section id="why"><h2>Pourquoi un téléphone partagé ne vous donne rien</h2>
<p>Un combiné partagé ne produit aucune donnée. Vous ne pouvez pas savoir combien de temps les gens ont attendu, combien de conversations vous avez traitées mardi dernier, quel agent a porté la charge, ni si le mois dernier valait mieux que le précédent. Vous avez l'impression de celui qui était le plus près du téléphone.</p>
<p>Cela dépasse la simple curiosité. Sans chiffres, vous ne pouvez pas répondre à trois questions opérationnelles : sommes-nous assez rapides, sommes-nous correctement dimensionnés, et ce que nous avons changé le mois dernier fonctionne-t-il. Chaque amélioration devient une dispute d'anecdotes.</p>
<figure><div class="shot"><img src="/img/features/dashboard-overview.png" alt="Le tableau de bord wavadesk complet montrant le statut d'essai, l'utilisation, les cartes d'indicateurs, le volume de conversations, la répartition par canal, le temps de réponse, la charge des agents, les heures de pointe et la performance de l'IA" loading="lazy" decoding="async" width="2570" height="3320"></div><figcaption><svg width="13" height="13" viewBox="0 0 24 24" fill="none"><rect x="2.5" y="6" width="19" height="14" rx="2.5" stroke="currentColor" stroke-width="2"/><circle cx="12" cy="13" r="3.4" stroke="currentColor" stroke-width="2"/><path d="M8.5 6l1.2-2h4.6L15.5 6" stroke="currentColor" stroke-width="2" stroke-linejoin="round"/></svg><span>Le tableau de bord wavadesk. Tout ce qui est à l'écran découle de l'enregistrement des conversations : aucun suivi séparé n'est nécessaire.</span></figcaption></figure>
</section>
<section id="kpis"><h2>Les quatre chiffres qui comptent le plus</h2>
<p>Le reporting échoue quand il propose quarante indicateurs sans priorité. Ces quatre-là couvrent le tableau opérationnel ; le reste relève du diagnostic.</p>
<figure><div class="shot"><img src="/img/features/kpis.png" alt="Quatre cartes d'indicateurs avec mini-graphiques et évolution d'une période à l'autre : conversations, médiane de première réponse, résolues par l'IA et en attente dans le pool" loading="lazy" decoding="async" width="2552" height="370"></div><figcaption><svg width="13" height="13" viewBox="0 0 24 24" fill="none"><rect x="2.5" y="6" width="19" height="14" rx="2.5" stroke="currentColor" stroke-width="2"/><circle cx="12" cy="13" r="3.4" stroke="currentColor" stroke-width="2"/><path d="M8.5 6l1.2-2h4.6L15.5 6" stroke="currentColor" stroke-width="2" stroke-linejoin="round"/></svg><span>Chaque indicateur porte une courbe de tendance et un écart d'une période à l'autre, car un chiffre sans direction n'est pas exploitable.</span></figcaption></figure>
<h3>Médiane de première réponse</h3>
<p>Le temps qu'un client attend une réponse humaine. Médiane plutôt que moyenne, car quelques conversations nocturnes suffisent à vider une moyenne de son sens. C'est le chiffre que les clients vivent réellement.</p>
<h3>Volume de conversations</h3>
<p>Ce qui arrive, réparti par canal. Sa valeur est comparative — cette semaine contre la précédente, ce mois contre le précédent — et c'est la donnée d'entrée de toute décision d'effectif.</p>
<h3>Résolues par l'IA</h3>
<p>La part de conversations closes sans humain. C'est le dividende de l'automatisation, et la mesure honnête de l'utilité réelle de votre base de connaissances.</p>
<h3>En attente dans le pool</h3>
<p>Combien de conversations ne sont pas prises en charge à l'instant, et depuis combien de temps attend la plus ancienne. Le seul chiffre en temps réel du lot, et celui à surveiller pendant un créneau.</p>
<div class="note"><svg width="17" height="17" viewBox="0 0 24 24" fill="none"><circle cx="12" cy="12" r="9" stroke="#0f7e7a" stroke-width="2"/><path d="M12 11v5" stroke="#0f7e7a" stroke-width="2" stroke-linecap="round"/><circle cx="12" cy="7.8" r="1.1" fill="#0f7e7a"/></svg><div class="m"><div class="h">Regardez la direction, pas les valeurs absolues</div><p>Une médiane de première réponse de quatre minutes est excellente pour certaines activités et médiocre pour d'autres. Ce qui compte, c'est de savoir si elle évolue dans le sens voulu.</p></div></div>
</section>
<section id="volume"><h2>Volume et répartition par canal</h2>
<p>Le volume par jour et par canal répond à la question des effectifs, et la répartition par canal vous dit par où vos clients choisissent réellement de vous joindre — souvent pas là où vous le pensiez.</p>
<figure><div class="shot"><img src="/img/features/volume-channels.png" alt="Volume quotidien de conversations empilé par canal, à côté d'un anneau de répartition par canal avec le taux de clients récurrents" loading="lazy" decoding="async" width="2552" height="602"></div><figcaption><svg width="13" height="13" viewBox="0 0 24 24" fill="none"><rect x="2.5" y="6" width="19" height="14" rx="2.5" stroke="currentColor" stroke-width="2"/><circle cx="12" cy="13" r="3.4" stroke="currentColor" stroke-width="2"/><path d="M8.5 6l1.2-2h4.6L15.5 6" stroke="currentColor" stroke-width="2" stroke-linejoin="round"/></svg><span>Volume quotidien empilé par canal, avec la répartition globale et le taux de clients récurrents à côté.</span></figcaption></figure>
<p>Deux tendances méritent d'être suivies d'effet. Si le volume du chat du site est élevé par rapport à WhatsApp, votre trafic d'avant-vente dépasse votre trafic de support et une IA autonome sur le widget sera vite rentable. Si le taux de clients récurrents est élevé, votre base de connaissances est le levier le plus fort à votre disposition, car les mêmes personnes posent les mêmes questions.</p>
</section>
<section id="response"><h2>Temps de réponse et de résolution</h2>
<p>La première réponse et la résolution sont deux problèmes distincts avec des remèdes distincts. Les confondre conduit des équipes à recruter quand elles devraient automatiser, ou l'inverse.</p>
<div class="tw"><table><thead><tr><th>Symptôme</th><th>Cause habituelle</th><th>Que changer</th></tr></thead><tbody><tr><td>Première réponse lente, résolution rapide</td><td>Personne ne surveille la file à cette heure-là</td><td>La couverture horaire, ou une IA autonome pour la première réponse</td></tr><tr><td>Première réponse rapide, résolution lente</td><td>Les agents accusent réception puis bloquent</td><td>Des lacunes de connaissances, ou des chemins d'escalade sans issue</td></tr><tr><td>Les deux lents</td><td>Effectif insuffisant pour le volume</td><td>Les effectifs, ou davantage de déflexion par l'IA</td></tr><tr><td>Pic des deux le week-end</td><td>Aucune couverture le week-end</td><td>Une IA autonome hors horaires, ou une file surveillée</td></tr></tbody></table></div>
<p>Le graphique des temps de réponse trace la médiane par jour : un week-end ou un trou de couverture apparaît comme une forme plutôt que comme un soupçon.</p>
</section>
<section id="workload"><h2>Charge des agents et heures de pointe</h2>
<p>Deux questions ici : le travail est-il réparti équitablement, et votre couverture correspond-elle au moment où le volume arrive réellement.</p>
<figure><div class="shot"><img src="/img/features/agents-heatmap.png" alt="Courbe des temps de réponse, charge par agent avec barres de capacité, et carte de chaleur des heures de pointe en sept par douze" loading="lazy" decoding="async" width="2552" height="702"></div><figcaption><svg width="13" height="13" viewBox="0 0 24 24" fill="none"><rect x="2.5" y="6" width="19" height="14" rx="2.5" stroke="currentColor" stroke-width="2"/><circle cx="12" cy="13" r="3.4" stroke="currentColor" stroke-width="2"/><path d="M8.5 6l1.2-2h4.6L15.5 6" stroke="currentColor" stroke-width="2" stroke-linejoin="round"/></svg><span>Les conversations ouvertes par agent par rapport à sa capacité, et une carte de chaleur du moment où le volume arrive dans la semaine.</span></figcaption></figure>
<p>Le panneau de charge montre les conversations ouvertes par agent face à une capacité, la barre passant à l'ambre au-delà de 80 %. Un déséquilibre persistant relève généralement du routage plutôt que de l'implication — une file absorbe plus que sa part.</p>
<p>La carte de chaleur est la plus exploitable des deux, parce que c'est celle que l'intuition trompe. Les équipes répartissent couramment leurs effectifs uniformément sur la journée alors que le volume se concentre sur trois heures. Comparer la carte de chaleur à votre planning est souvent l'amélioration du temps de réponse la moins coûteuse qui soit.</p>
</section>
<section id="ai"><h2>Performance de l'IA</h2>
<p>Le reporting de l'IA doit répondre à une question : quelle charge retire-t-elle à votre équipe, et transmet-elle les bons sujets ?</p>
<figure><div class="shot"><img src="/img/features/ai-performance.png" alt="Panneau de performance de l'IA avec taux de déflexion, temps de réponse médian de l'IA, nombre d'escalades et barre de proportions empilée" loading="lazy" decoding="async" width="2552" height="438"></div><figcaption><svg width="13" height="13" viewBox="0 0 24 24" fill="none"><rect x="2.5" y="6" width="19" height="14" rx="2.5" stroke="currentColor" stroke-width="2"/><circle cx="12" cy="13" r="3.4" stroke="currentColor" stroke-width="2"/><path d="M8.5 6l1.2-2h4.6L15.5 6" stroke="currentColor" stroke-width="2" stroke-linejoin="round"/></svg><span>Résolues par l'IA, assistées par l'IA et escaladées, en proportion du total des conversations plutôt qu'en nombre brut de messages.</span></figcaption></figure>
<p>Le taux de déflexion est le chiffre principal. La barre empilée en dessous sépare les conversations que l'IA a closes entièrement, celles qu'elle a rédigées et qu'un agent a envoyées, et celles qu'elle a escaladées. Les escalades sont une catégorie saine — un taux de déflexion de 100 % signifierait que l'IA répond à des choses qu'elle devrait transmettre.</p>
<div class="stats"><div class="sc"><b>68 %</b><span>résolues de bout en bout par l'IA</span></div><div class="sc"><b>21 %</b><span>assistées par l'IA, envoyées par un agent</span></div><div class="sc"><b>11 %</b><span>escaladées délibérément</span></div></div>
</section>
<section id="use"><h2>S'en servir en revue hebdomadaire</h2>
<p>Le reporting ne change les comportements que si quelqu'un le regarde régulièrement. Une revue hebdomadaire de quinze minutes suffit.</p>
<ol class="numbered"><li><span>La médiane de première réponse face à la semaine précédente. Si elle a bougé, trouvez le jour où elle a bougé.</span></li><li><span>Le volume face à la semaine précédente, et si un écart vient des effectifs ou de la demande.</span></li><li><span>La carte de chaleur des heures de pointe face à votre planning réel.</span></li><li><span>Le taux de déflexion, et les trois principaux sujets d'escalade récurrents — ce sont vos prochaines entrées de base de connaissances.</span></li><li><span>L'équilibre de charge entre agents, et si un déséquilibre relève du routage plutôt que de l'implication.</span></li></ol>
<p>Les sujets d'escalade sont l'élément le plus précieux de cette liste, car ils se convertissent directement en automatisation. Chaque trou comblé est une catégorie de questions qui cesse d'atteindre un humain.</p>
</section>
