{{-- Corps d'article français pour /features/reservations.
     Structure identique à la version anglaise : seul le texte change, afin
     que les ancres de sommaire de config/seo_pages.php restent valides. --}}
<section id="why"><h2>Pourquoi réserver sur WhatsApp fonctionne</h2>
<p>Pour les cliniques, salons, garages, restaurants et services professionnels, la demande de rendez-vous commence presque toujours par un message. Quelqu'un demande si vous avez de la place jeudi. Ce qui se passe ensuite décide si vous obtenez la réservation.</p>
<p>La réponse habituelle est un lien vers une page de réservation, qui ajoute une étape que le client n'a pas demandée. Une part non négligeable n'y arrive jamais, non par changement d'avis mais parce que la friction est tombée exactement au mauvais moment. Garder la réservation dans la conversation supprime cet abandon.</p>
<div class="cards"><div class="fc"><div class="ic"><svg width="19" height="19" viewBox="0 0 24 24" fill="none"><rect x="3" y="5" width="18" height="16" rx="2.6" stroke="#0f7e7a" stroke-width="2"/><path d="M3 10h18M8 3v4M16 3v4" stroke="#0f7e7a" stroke-width="2" stroke-linecap="round"/></svg></div><div class="h">Aucun changement de contexte</div><p>Le client ne quitte jamais le fil qu'il a ouvert : personne n'est perdu à cause d'une redirection.</p></div><div class="fc"><div class="ic"><svg width="19" height="19" viewBox="0 0 24 24" fill="none"><path d="M18 8.5a6 6 0 10-12 0c0 6-2.5 7.5-2.5 7.5h17S18 14.5 18 8.5z" stroke="#0f7e7a" stroke-width="2" stroke-linejoin="round"/><path d="M13.7 20a2 2 0 01-3.4 0" stroke="#0f7e7a" stroke-width="2" stroke-linecap="round"/></svg></div><div class="h">Des rappels qui sont lus</div><p>Un rappel WhatsApp dans un fil existant est ouvert bien plus sûrement qu'un SMS ou un e-mail.</p></div><div class="fc"><div class="ic"><svg width="19" height="19" viewBox="0 0 24 24" fill="none"><path d="M16 20v-2a4 4 0 00-4-4H6a4 4 0 00-4 4v2" stroke="#0f7e7a" stroke-width="2" stroke-linecap="round"/><circle cx="9" cy="7" r="3.4" stroke="#0f7e7a" stroke-width="2"/><path d="M22 20v-2a4 4 0 00-3-3.9" stroke="#0f7e7a" stroke-width="2" stroke-linecap="round"/></svg></div><div class="h">Un seul endroit à consulter</div><p>Les réservations et la conversation qui les a produites sont au même endroit : le personnel voit les deux.</p></div><div class="fc"><div class="ic"><svg width="19" height="19" viewBox="0 0 24 24" fill="none"><circle cx="12" cy="12" r="9" stroke="#0f7e7a" stroke-width="2"/><path d="M12 7v5.4l3.4 2" stroke="#0f7e7a" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/></svg></div><div class="h">Les reports restent simples</div><p>Changer d'horaire tient en une réponse, pas en un formulaire. Les gens le font donc réellement plutôt que de ne pas venir.</p></div></div>
</section>
<section id="flow"><h2>Le parcours de réservation</h2>
<p>Le parcours est volontairement court, et l'agent IA peut en traiter l'essentiel avant qu'un humain n'intervienne.</p>
<div class="steps"><div class="step"><span class="n">1</span><div class="m"><div class="h">Le client demande les disponibilités</div><p>Soit en langage libre, soit en choisissant parmi les options proposées par l'IA.</p></div></div><div class="step"><span class="n">2</span><div class="m"><div class="h">Les disponibilités sont proposées</div><p>Issues de vos horaires configurés, de la durée des prestations et des réservations existantes, de sorte que rien ne se chevauche.</p></div></div><div class="step"><span class="n">3</span><div class="m"><div class="h">Le client choisit un créneau</div><p>Confirmé dans la conversation. Le créneau est bloqué immédiatement.</p></div></div><div class="step"><span class="n">4</span><div class="m"><div class="h">Confirmation et rappel sont programmés</div><p>Une confirmation immédiate, puis un rappel selon le calendrier que vous définissez — en général 24 heures avant, puis deux heures avant.</p></div></div></div>
<div class="note"><svg width="17" height="17" viewBox="0 0 24 24" fill="none"><circle cx="12" cy="12" r="9" stroke="#0f7e7a" stroke-width="2"/><path d="M12 11v5" stroke="#0f7e7a" stroke-width="2" stroke-linecap="round"/><circle cx="12" cy="7.8" r="1.1" fill="#0f7e7a"/></svg><div class="m"><div class="h">Le personnel peut toujours reprendre la main</div><p>Si un client a besoin de quelque chose que l'automatisation ne gère pas — un praticien précis, un créneau double, un cas particulier — un agent prend la conversation en charge et réserve manuellement. Le calendrier de rappels s'applique toujours.</p></div></div>
</section>
<section id="noshows"><h2>Réduire les absences</h2>
<p>Les absences sont le premier poste de coût des activités sur rendez-vous, et elles relèvent surtout d'un problème de mémoire plutôt que d'engagement. La solution est un rappel réellement vu, avec un moyen sans friction de changer l'horaire.</p>
<p>Un rappel qui dit seulement « vous avez un rendez-vous demain » est une demi-mesure. Le rappel doit rendre le report aussi facile que l'indifférence, car un créneau reporté peut être repris alors qu'une absence, non.</p>
<h3>Ce que fait un rappel efficace</h3>
<ul><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>Il arrive dans le fil WhatsApp existant, pas d'un expéditeur inconnu</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>Il indique la prestation, l'heure, la date et le lieu sans que le client ait à chercher quoi que ce soit</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>Il propose de confirmer ou de reporter en réponse directe</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>Il part selon un calendrier que vous maîtrisez, en général 24 heures et 2 heures avant</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>Il enregistre la réponse sur la réservation, pour que le personnel sache qui a confirmé</span></li></ul>
<div class="note amber"><svg width="17" height="17" viewBox="0 0 24 24" fill="none"><path d="M12 8v5" stroke="#92400e" stroke-width="2.2" stroke-linecap="round"/><circle cx="12" cy="16.5" r="1.2" fill="#92400e"/><circle cx="12" cy="12" r="9" stroke="#92400e" stroke-width="2"/></svg><div class="m"><div class="h">Deux rappels sont généralement un maximum</div><p>La veille et deux heures avant couvrent la fenêtre d'oubli réaliste. Au-delà, cela devient du harcèlement, le fil est mis en sourdine, et vous perdez le canal.</p></div></div>
</section>
<section id="calendar"><h2>Agenda et capacité</h2>
<p>Les disponibilités ne sont fiables que si elles reflètent la réalité. Le module s'appuie sur votre capacité configurée plutôt que sur une estimation improvisée par la personne qui répond.</p>
<ul><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>Les horaires d'ouverture par jour, y compris les coupures et les fermetures</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>La durée des prestations, pour qu'un rendez-vous de 20 minutes et un de 90 minutes ne consomment pas la même capacité</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>Plusieurs ressources — praticiens, fauteuils, postes, tables — chacune avec son planning</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>Un temps tampon entre les rendez-vous, là où une remise en état est nécessaire</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>Des dates bloquées pour les congés et la maintenance</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>Un nombre maximal de réservations simultanées par créneau</span></li></ul>
<p>Comme la capacité est définie une seule fois, un créneau proposé par l'IA et un créneau proposé par le personnel ne peuvent pas se contredire. La double réservation devient une question de configuration plutôt qu'une erreur humaine.</p>
</section>
<section id="verify"><h2>Vérifier que la réservation est réelle</h2>
<p>Les activités à capacité rare — restaurants aux heures de pointe, cliniques aux créneaux limités — perdent de l'argent à cause de réservations faites avec un numéro erroné ou fictif. Associer les réservations au module OTP referme cette brèche.</p>
<p>Quand vous exigez la vérification, le client confirme son numéro avec un code à usage unique avant que le créneau ne soit bloqué. Cela ajoute une étape pour le client et supprime toute une catégorie de pertes pour vous.</p>
<p>Voir <a href="/features/otp-service">OTP et vérification WhatsApp</a>.</p>
</section>
<section id="who"><h2>Qui utilise les réservations</h2>
<div class="cards"><div class="fc"><div class="ic"><svg width="19" height="19" viewBox="0 0 24 24" fill="none"><path d="M16 20v-2a4 4 0 00-4-4H6a4 4 0 00-4 4v2" stroke="#0f7e7a" stroke-width="2" stroke-linecap="round"/><circle cx="9" cy="7" r="3.4" stroke="#0f7e7a" stroke-width="2"/><path d="M22 20v-2a4 4 0 00-3-3.9" stroke="#0f7e7a" stroke-width="2" stroke-linecap="round"/></svg></div><div class="h">Cliniques et cabinets dentaires</div><p>Demandes de rendez-vous, reports et rappels de suivi, où un message manqué est une réservation perdue.</p></div><div class="fc"><div class="ic"><svg width="19" height="19" viewBox="0 0 24 24" fill="none"><rect x="3" y="5" width="18" height="16" rx="2.6" stroke="#0f7e7a" stroke-width="2"/><path d="M3 10h18M8 3v4M16 3v4" stroke="#0f7e7a" stroke-width="2" stroke-linecap="round"/></svg></div><div class="h">Salons de coiffure et barbiers</div><p>Fort volume de rendez-vous courts, nombreux reports et coût réel des absences.</p></div><div class="fc"><div class="ic"><svg width="19" height="19" viewBox="0 0 24 24" fill="none"><rect x="6" y="2.5" width="12" height="19" rx="2.6" stroke="#0f7e7a" stroke-width="2"/><path d="M11 18.5h2" stroke="#0f7e7a" stroke-width="2" stroke-linecap="round"/></svg></div><div class="h">Garages et ateliers</div><p>Capacité de postes avec des prestations longues, où la double réservation coûte cher.</p></div><div class="fc"><div class="ic"><svg width="19" height="19" viewBox="0 0 24 24" fill="none"><circle cx="12" cy="12" r="9" stroke="#0f7e7a" stroke-width="2"/><path d="M3 12h18M12 3c2.5 2.6 2.5 15.4 0 18M12 3c-2.5 2.6-2.5 15.4 0 18" stroke="#0f7e7a" stroke-width="2"/></svg></div><div class="h">Restaurants</div><p>Tables aux heures de pointe, où des réservations vérifiées comptent plus que le volume.</p></div></div>
<p>Le module de réservations est inclus dans l'offre Scale et disponible en option sur les autres.</p>
</section>
