{{-- Corps d'article français pour /features/teams-routing.
     Structure identique à la version anglaise : seul le texte change, afin
     que les ancres de sommaire de config/seo_pages.php restent valides. --}}
<section id="why"><h2>Quand une seule file ne suffit plus</h2>
<p>Un pool partagé est le bon réglage par défaut. Tout le monde voit tout, chacun peut prendre n'importe quoi, et le coût de configuration est nul. Cela tient jusqu'à environ cinq ou six agents traitant des questions globalement similaires.</p>
<p>Au-delà, deux choses cassent. Les agents passent un temps réel à filtrer visuellement — lire puis ignorer des conversations qui relèvent d'une autre fonction. Et la spécialisation devient impossible : si la personne qui traite les litiges de facturation voit la même liste indifférenciée que les autres, son expertise n'est pas dirigée vers le bon travail.</p>
<p>Le routage est la solution, et son objet est soustractif. Il ne s'agit pas de donner plus d'informations, mais de <strong>donner à chaque agent moins de choses à regarder</strong>, pour que ce qui reste soit le sien.</p>
</section>
<section id="teams"><h2>Constituer les équipes</h2>
<p>Une équipe est un groupe d'agents et une file. La plupart des organisations les calquent sur les fonctions existantes plutôt que d'en inventer de nouvelles.</p>
<div class="cards"><div class="fc"><div class="ic"><svg width="19" height="19" viewBox="0 0 24 24" fill="none"><path d="M16 20v-2a4 4 0 00-4-4H6a4 4 0 00-4 4v2" stroke="#0f7e7a" stroke-width="2" stroke-linecap="round"/><circle cx="9" cy="7" r="3.4" stroke="#0f7e7a" stroke-width="2"/><path d="M22 20v-2a4 4 0 00-3-3.9" stroke="#0f7e7a" stroke-width="2" stroke-linecap="round"/></svg></div><div class="h">Par fonction</div><p>Ventes, support, facturation, retours. La répartition la plus courante, car les compétences diffèrent réellement.</p></div><div class="fc"><div class="ic"><svg width="19" height="19" viewBox="0 0 24 24" fill="none"><circle cx="12" cy="12" r="9" stroke="#0f7e7a" stroke-width="2"/><path d="M3 12h18M12 3c2.5 2.6 2.5 15.4 0 18M12 3c-2.5 2.6-2.5 15.4 0 18" stroke="#0f7e7a" stroke-width="2"/></svg></div><div class="h">Par langue</div><p>Quand vous servez plusieurs langues et que tous les agents ne les parlent pas toutes.</p></div><div class="fc"><div class="ic"><svg width="19" height="19" viewBox="0 0 24 24" fill="none"><circle cx="12" cy="12" r="9" stroke="#0f7e7a" stroke-width="2"/><path d="M12 7v5.4l3.4 2" stroke="#0f7e7a" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/></svg></div><div class="h">Par créneau horaire</div><p>Équipes du matin et du soir, pour que les conversations hors horaires arrivent chez la personne réellement en poste.</p></div><div class="fc"><div class="ic"><svg width="19" height="19" viewBox="0 0 24 24" fill="none"><path d="M12 2H4a2 2 0 00-2 2v8l10 10 10-10L12 2z" stroke="#0f7e7a" stroke-width="2" stroke-linejoin="round"/><circle cx="7.5" cy="7.5" r="1.4" fill="#0f7e7a"/></svg></div><div class="h">Par gamme de produits</div><p>Quand les produits sont assez différents pour que les connaissances ne se transposent pas.</p></div></div>
<p>Un agent peut appartenir à plusieurs équipes. Une petite structure met souvent tout le monde dans toutes les équipes au départ, puis resserre en grandissant — c'est le bon ordre, car ce sont les échanges qui révèlent les vraies frontières.</p>
</section>
<section id="rules"><h2>Règles de routage</h2>
<p>Les règles sont évaluées dans l'ordre, et la première correspondance l'emporte. Garder la liste courte est une qualité, pas une limite — de longues chaînes de règles deviennent impossibles à analyser quand quelque chose part au mauvais endroit.</p>
<h3>Router par mot-clé</h3>
<p>Le message nomme souvent lui-même le service. « Remboursement », « facture » et « rétrofacturation » signifient facturation ; « devis » et « tarif » signifient ventes. Le routage par mot-clé attrape les cas évidents et laisse les cas ambigus dans le pool général.</p>
<h3>Router par canal</h3>
<p>Les conversations du widget sont fréquemment de l'avant-vente — quelqu'un qui lit votre page tarifs — tandis que WhatsApp penche vers les clients existants. Router par canal est un indicateur d'intention grossier mais efficace.</p>
<h3>Router par horaires</h3>
<p>En dehors des heures ouvrées, les conversations doivent arriver là où quelqu'un veille, ou dans une file explicitement surveillée le lendemain matin, plutôt que dans un pool général que personne ne possède la nuit.</p>
<h3>Router par contact</h3>
<p>Les comptes nommés, les clients VIP ou des numéros précis peuvent être routés directement vers une équipe ou un agent désigné, pour que vos relations les plus importantes ne fassent pas la queue derrière le trafic général.</p>
<div class="note"><svg width="17" height="17" viewBox="0 0 24 24" fill="none"><circle cx="12" cy="12" r="9" stroke="#0f7e7a" stroke-width="2"/><path d="M12 11v5" stroke="#0f7e7a" stroke-width="2" stroke-linecap="round"/><circle cx="12" cy="7.8" r="1.1" fill="#0f7e7a"/></svg><div class="m"><div class="h">Prévoyez un défaut</div><p>Toute configuration de routage a besoin d'une file de repli pour les conversations qui ne correspondent à rien. Sans elle, les cas limites disparaissent.</p></div></div>
</section>
<section id="assignment"><h2>Affectation et prise en charge</h2>
<p>Le routage décide dans quelle file entre une conversation. L'affectation décide qui la possède. Ce sont deux choses distinctes, et les confondre est l'erreur de configuration la plus courante.</p>
<ul><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>Routée vers une équipe, non affectée — les agents de l'équipe la prennent depuis la file</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>Affectation automatique en tourniquet — répartie également entre les agents disponibles de l'équipe</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>Affectée à un agent nommé — pour les comptes désignés ou la suite d'une conversation antérieure</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>Réaffectée par un responsable — enregistrée, pour que les passages de relais restent visibles dans le journal d'audit</span></li></ul>
<p>La plupart des équipes devraient commencer par « routée mais non affectée » avec prise en charge. Le tourniquet semble plus équitable mais distribue le travail à des personnes peut-être en pleine conversation complexe, et retire à l'agent la possibilité de prendre ce qu'il est le mieux placé pour traiter.</p>
<div class="note amber"><svg width="17" height="17" viewBox="0 0 24 24" fill="none"><path d="M12 8v5" stroke="#92400e" stroke-width="2.2" stroke-linecap="round"/><circle cx="12" cy="16.5" r="1.2" fill="#92400e"/><circle cx="12" cy="12" r="9" stroke="#92400e" stroke-width="2"/></svg><div class="m"><div class="h">L'affectation automatique exige une présence fiable</div><p>Affecter des conversations à un agent hors ligne crée une file silencieuse derrière une seule personne. Ne l'activez que là où le statut de disponibilité est fiable.</p></div></div>
</section>
<section id="escalation"><h2>Escalade et ancienneté</h2>
<p>Toute configuration de routage finit par laisser une conversation en rade : elle est dans la bonne file, et personne ne l'a prise. Les règles d'escalade rattrapent cela automatiquement plutôt que de compter sur l'attention de quelqu'un.</p>
<div class="steps"><div class="step"><span class="n">1</span><div class="m"><div class="h">Définissez un seuil d'ancienneté</div><p>Par exemple, 15 minutes sans prise en charge pendant les heures ouvrées.</p></div></div><div class="step"><span class="n">2</span><div class="m"><div class="h">Escaladez en cas de dépassement</div><p>Déplacez la conversation vers la file d'un responsable, ou signalez-la en tête de la file d'équipe.</p></div></div><div class="step"><span class="n">3</span><div class="m"><div class="h">Surveillez la plus longue attente</div><p>La file met en avant la conversation qui attend depuis le plus longtemps : un chiffre qui grimpe se voit avant que les clients ne se plaignent.</p></div></div><div class="step"><span class="n">4</span><div class="m"><div class="h">Ajustez le seuil au réel</div><p>Un seuil que personne ne peut tenir n'est que du bruit. Placez-le là où les dépassements sont réellement exceptionnels.</p></div></div></div>
<figure><div class="shot"><img src="/img/features/agents-heatmap.png" alt="Panneau de charge des agents avec barres de capacité et carte de chaleur des heures de pointe" loading="lazy" decoding="async" width="2552" height="702"></div><figcaption><svg width="13" height="13" viewBox="0 0 24 24" fill="none"><rect x="2.5" y="6" width="19" height="14" rx="2.5" stroke="currentColor" stroke-width="2"/><circle cx="12" cy="13" r="3.4" stroke="currentColor" stroke-width="2"/><path d="M8.5 6l1.2-2h4.6L15.5 6" stroke="currentColor" stroke-width="2" stroke-linejoin="round"/></svg><span>La charge par agent avec des barres de capacité, et les heures où le volume arrive réellement — les deux données pour fixer des seuils réalistes et couvrir les créneaux.</span></figcaption></figure>
</section>
<section id="measure"><h2>Vérifier que votre routage est juste</h2>
<p>Le routage est une hypothèse sur la façon de répartir le travail. Les rapports vous disent si l'hypothèse tient.</p>
<ul><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>Le taux de réaffectation — un taux élevé signifie que les règles envoient le travail à la mauvaise équipe</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>Le temps de réponse par équipe — une file lente signifie généralement un sous-effectif, pas de la paresse</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>L'équilibre de charge entre agents — un déséquilibre persistant signifie que le routage concentre le travail</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>La fréquence des escalades — des escalades en hausse appellent à revoir les seuils ou les effectifs</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>Le volume par heure face à la couverture — la carte de chaleur confrontée à votre planning</span></li></ul>
<p>Plus de détails dans <a href="/features/reports-analytics">Rapports et statistiques du support</a>.</p>
</section>
