{{-- Corps d'article français pour /features/whatsapp-shared-inbox.
     Structure identique à la version anglaise : seul le texte change, afin
     que les ancres de sommaire de config/seo_pages.php restent valides. --}}
<section id="problem"><h2>Le problème du téléphone unique</h2>
<p>Presque toutes les équipes qui assurent le support sur WhatsApp commencent de la même façon : un combiné, ou un accès à WhatsApp Web, partagé entre les personnes de garde. Cela fonctionne un temps. Puis le volume augmente et les fissures se révèlent structurelles plutôt qu'occasionnelles.</p>
<p>Il n'y a pas de file, donc personne ne voit ce qui attend. Il n'y a pas de propriétaire, donc deux agents ouvrent la même conversation et envoient deux réponses différentes. Il n'y a pas de trace, donc quand quelqu'un quitte l'équipe, chaque promesse faite à un client part avec lui. Et il n'y a aucun moyen de répondre à la question de gestion la plus simple qui soit : combien de temps les gens attendent-ils ?</p>
<ul><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>Un message lu par un agent paraît lu par tous, il est donc sauté</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>Deux agents répondent au même client avec des réponses contradictoires</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>Aucune idée de qui a promis un remboursement, une remise ou une date de livraison</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>Un historique lié à un appareil plutôt qu'à l'entreprise</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>Aucun chiffre de temps de réponse ou de volume sur lequel piloter</span></li></ul>
<p>Une boîte de réception partagée corrige tout cela en changeant l'unité de travail. Au lieu d'un flux de messages sur un appareil, vous obtenez <strong>des conversations avec un propriétaire, un statut et un historique</strong>.</p>
</section>
<section id="how"><h2>Comment fonctionne la boîte partagée</h2>
<p>Chaque message entrant sur votre numéro WhatsApp connecté devient une conversation dans une liste unique que toute l'équipe voit. Rien n'est attribué automatiquement tant que vous ne définissez pas de règles de routage : par défaut, la conversation reste dans un pool partagé, en attente que quelqu'un la prenne.</p>
<figure><div class="shot"><img src="/img/features/inbox-full.png" alt="La boîte de réception partagée wavadesk montrant la liste des conversations, un fil ouvert et le panneau de contexte client" loading="lazy" decoding="async" width="3186" height="1766"></div><figcaption><svg width="13" height="13" viewBox="0 0 24 24" fill="none"><rect x="2.5" y="6" width="19" height="14" rx="2.5" stroke="currentColor" stroke-width="2"/><circle cx="12" cy="13" r="3.4" stroke="currentColor" stroke-width="2"/><path d="M8.5 6l1.2-2h4.6L15.5 6" stroke="currentColor" stroke-width="2" stroke-linejoin="round"/></svg><span>La boîte partagée dans wavadesk. La liste de gauche est le pool que voit chaque agent ; le panneau de droite porte le contexte client de la conversation ouverte.</span></figcaption></figure>
<p>Les trois volets correspondent aux trois questions que se pose un agent à tout moment : qu'est-ce qui attend, à quoi suis-je en train de répondre, et à qui je parle. Un badge de canal sur chaque avatar indique si la conversation est arrivée par WhatsApp ou par le widget du site, de sorte qu'une seule file peut porter les deux sans confusion.</p>
<div class="cards"><div class="fc"><div class="ic"><svg width="19" height="19" viewBox="0 0 24 24" fill="none"><path d="M21 11.5a8.4 8.4 0 01-9 8.4 8.9 8.9 0 01-3.9-.9L3 20.5l1.5-4.6A8.4 8.4 0 013.6 11.5a8.4 8.4 0 018.4-8.4 8.4 8.4 0 019 8.4z" stroke="#0f7e7a" stroke-width="2" stroke-linejoin="round"/></svg></div><div class="h">Un seul pool, pas plusieurs boîtes</div><p>Chaque conversation de chaque canal connecté arrive dans la même liste, filtrable par canal, statut et personne assignée.</p></div><div class="fc"><div class="ic"><svg width="19" height="19" viewBox="0 0 24 24" fill="none"><rect x="4.5" y="10.5" width="15" height="10" rx="2.2" stroke="#0f7e7a" stroke-width="2"/><path d="M8 10.5V7a4 4 0 018 0v3.5" stroke="#0f7e7a" stroke-width="2" stroke-linecap="round"/></svg></div><div class="h">Prendre en charge pour traiter</div><p>Un agent prend une conversation en charge et celle-ci lui est verrouillée. Le verrou est appliqué au niveau de la base de données, pas seulement dans l'interface.</p></div><div class="fc"><div class="ic"><svg width="19" height="19" viewBox="0 0 24 24" fill="none"><path d="M4 4h16v12l-4 4H4z" stroke="#0f7e7a" stroke-width="2" stroke-linejoin="round"/><path d="M8 9h8M8 13h5" stroke="#0f7e7a" stroke-width="2" stroke-linecap="round"/></svg></div><div class="h">Notes internes</div><p>Les notes sont visibles par votre équipe et ne sont jamais envoyées au client : le contexte voyage donc avec la conversation.</p></div><div class="fc"><div class="ic"><svg width="19" height="19" viewBox="0 0 24 24" fill="none"><circle cx="12" cy="12" r="9" stroke="#0f7e7a" stroke-width="2"/><path d="M12 7v5.4l3.4 2" stroke="#0f7e7a" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/></svg></div><div class="h">Statut et historique</div><p>Ouverte, prise en charge, résolue, rouverte. Chaque changement d'état est horodaté et associé à un nom.</p></div></div>
</section>
<section id="claim"><h2>Le verrouillage, et pourquoi il compte</h2>
<p>Le pire moment du support partagé, c'est quand deux personnes répondent au même client. C'est pire qu'une réponse lente, car le client se retrouve avec deux réponses sans savoir laquelle est la bonne — et votre équipe doit démêler cela devant lui.</p>
<p>wavadesk l'empêche structurellement plutôt que socialement. Quand un agent prend une conversation en charge, cette prise en charge est écrite comme un verrou. Un second agent qui ouvre la même conversation la voit comme prise et ne peut ni la reprendre ni y écrire. Il n'y a pas de situation de concurrence à perdre, ni de convention qu'une équipe sous pression pourrait oublier.</p>
<div class="note"><svg width="17" height="17" viewBox="0 0 24 24" fill="none"><circle cx="12" cy="12" r="9" stroke="#0f7e7a" stroke-width="2"/><path d="M12 11v5" stroke="#0f7e7a" stroke-width="2" stroke-linecap="round"/><circle cx="12" cy="7.8" r="1.1" fill="#0f7e7a"/></svg><div class="m"><div class="h">La prise en charge est réversible</div><p>Un agent peut relâcher une conversation vers le pool, et un responsable peut la réaffecter. Le verrouillage empêche les collisions accidentelles, pas les passages de relais volontaires.</p></div></div>
<p>Quand une prise en charge est relâchée ou réaffectée, cela aussi est enregistré. Sur une semaine, vous voyez non seulement qui a répondu à quoi, mais où le travail a circulé entre les personnes — c'est généralement là que se cachent les retards.</p>
</section>
<section id="context"><h2>Un client, un historique</h2>
<p>Une conversation n'est utile qu'avec l'historique qui la précède. Quand un client écrit pour la quatrième fois ce mois-ci, l'agent ne devrait pas lui demander de réexpliquer sa situation.</p>
<p>Chaque conversation s'ouvre avec l'intégralité du fil passé du client, quel que soit l'agent qui a traité ces échanges ou le canal par lequel ils sont arrivés. Si quelqu'un a posé une question via le widget de votre site en août et écrit sur WhatsApp en septembre, c'est un seul historique, pas deux.</p>
<h3>Ce qui suit le client</h3>
<ul><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>Chaque conversation précédente sur tout canal connecté</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>Les étiquettes que vous avez posées, pour segmenter et filtrer</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>Les notes internes laissées par votre équipe sur les conversations passées</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>L'historique d'affectation et le statut de résolution</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>Les références de commande ou de réservation, lorsque vous les avez reliées</span></li></ul>
</section>
<section id="audit"><h2>Chaque action est attribuable</h2>
<p>Les litiges de support ne portent presque jamais sur ce qu'a dit le client. Ils portent sur ce qu'a dit votre équipe. Un journal d'audit transforme cela d'une discussion en une simple vérification.</p>
<p>wavadesk enregistre qui a pris une conversation en charge, qui a répondu, ce qui a été envoyé, quand les statuts ont changé, quelles notes ont été ajoutées et où l'IA a agi seule. Rien n'est anonyme et rien n'est modifiable en silence.</p>
<p>Cela compte dans trois situations concrètes : un client affirme qu'on lui a promis quelque chose, un nouvel agent doit comprendre comment un dossier a été traité, et un responsable doit vérifier qu'un processus est réellement suivi et pas seulement affiché.</p>
</section>
<section id="setup"><h2>Se connecter</h2>
<p>La mise en place est volontairement courte, car un outil de support qui demande une semaine d'installation n'est jamais installé.</p>
<div class="steps"><div class="step"><span class="n">1</span><div class="m"><div class="h">Scannez un QR code</div><p>Connectez votre numéro WhatsApp Business existant comme vous connectez WhatsApp Web. Aucune migration de numéro, et rien ne change pour vos clients.</p></div></div><div class="step"><span class="n">2</span><div class="m"><div class="h">Invitez vos agents</div><p>Ajoutez les personnes qui répondront, et placez-les dans des équipes si vous souhaitez un routage par service.</p></div></div><div class="step"><span class="n">3</span><div class="m"><div class="h">Collez votre FAQ</div><p>Donnez à l'agent IA une base pour répondre. C'est facultatif au départ et peut être ajouté plus tard.</p></div></div><div class="step"><span class="n">4</span><div class="m"><div class="h">Commencez à prendre en charge</div><p>Les conversations commencent à arriver immédiatement dans le pool partagé. Votre équipe les prend en charge et répond depuis le navigateur.</p></div></div></div>
<div class="note"><svg width="17" height="17" viewBox="0 0 24 24" fill="none"><circle cx="12" cy="12" r="9" stroke="#0f7e7a" stroke-width="2"/><path d="M12 11v5" stroke="#0f7e7a" stroke-width="2" stroke-linecap="round"/><circle cx="12" cy="7.8" r="1.1" fill="#0f7e7a"/></svg><div class="m"><div class="h">Vos clients ne remarquent rien</div><p>Ils continuent d'écrire au numéro qu'ils connaissent déjà. Le changement se situe entièrement de votre côté de la conversation.</p></div></div>
</section>
<section id="who"><h2>À qui s'adresse une boîte partagée</h2>
<p>Le constat est constant : une boîte partagée devient rentable dès que plus d'une personne doit répondre sur le même numéro. En deçà, un téléphone suffit. Au-delà, le téléphone devient le goulot d'étranglement.</p>
<div class="cards"><div class="fc"><div class="ic"><svg width="19" height="19" viewBox="0 0 24 24" fill="none"><path d="M16 20v-2a4 4 0 00-4-4H6a4 4 0 00-4 4v2" stroke="#0f7e7a" stroke-width="2" stroke-linecap="round"/><circle cx="9" cy="7" r="3.4" stroke="#0f7e7a" stroke-width="2"/><path d="M22 20v-2a4 4 0 00-3-3.9" stroke="#0f7e7a" stroke-width="2" stroke-linecap="round"/></svg></div><div class="h">E-commerce et commerce de détail</div><p>Statut des commandes, créneaux de livraison, retours et échanges — gros volume, très répétitif, facile à perdre de vue.</p></div><div class="fc"><div class="ic"><svg width="19" height="19" viewBox="0 0 24 24" fill="none"><rect x="3" y="5" width="18" height="16" rx="2.6" stroke="#0f7e7a" stroke-width="2"/><path d="M3 10h18M8 3v4M16 3v4" stroke="#0f7e7a" stroke-width="2" stroke-linecap="round"/></svg></div><div class="h">Cliniques et services</div><p>Demandes de rendez-vous, reports et rappels, où un message manqué est une réservation perdue.</p></div><div class="fc"><div class="ic"><svg width="19" height="19" viewBox="0 0 24 24" fill="none"><rect x="6" y="2.5" width="12" height="19" rx="2.6" stroke="#0f7e7a" stroke-width="2"/><path d="M11 18.5h2" stroke="#0f7e7a" stroke-width="2" stroke-linecap="round"/></svg></div><div class="h">Entreprises avec des équipes en rotation</div><p>Le passage de relais entre équipes est là où les téléphones partagés échouent le plus, et là où une file avec historique aide le plus.</p></div><div class="fc"><div class="ic"><svg width="19" height="19" viewBox="0 0 24 24" fill="none"><path d="M4 20V10M10 20V4M16 20v-7M22 20H2" stroke="#0f7e7a" stroke-width="2" stroke-linecap="round"/></svg></div><div class="h">Équipes qui ont besoin de reporting</div><p>Toute activité où quelqu'un doit rendre des comptes sur les temps de réponse plutôt que de les deviner.</p></div></div>
</section>
