{{-- Corps d'article français pour /features/whatsapp-multi-agent.
     Structure identique à la version anglaise : seul le texte change, afin
     que les ancres de sommaire de config/seo_pages.php restent valides. --}}
<section id="why"><h2>Pourquoi WhatsApp seul n'y arrive pas</h2>
<p>WhatsApp Business est un excellent outil pour un opérateur unique. Il a été conçu autour d'un compte, d'un appareil et de la mémoire d'une seule personne quant à ce qui a été traité. La fonction d'appareils liés étend cela à quelques écrans, mais ne change pas le modèle : tout le monde regarde le même flux indifférencié, sans aucune notion de qui possède quoi.</p>
<p>Toute la difficulté tient à cette distinction. Que plusieurs personnes <em>voient</em> les messages n'est pas la même chose que plusieurs personnes qui les <em>traitent</em> . Sans notion de propriétaire, une vue partagée crée activement des modes de défaillance qu'un opérateur seul ne connaît jamais.</p>
<div class="tw"><table><thead><tr><th>Ce dont une équipe a besoin</th><th>Téléphone partagé ou appareils liés</th><th>Avec wavadesk</th></tr></thead><tbody><tr><td>Voir ce qui attend</td><td>Un flux, les plus anciens hors de vue</td><td>Une file avec les temps d'attente et les plus anciennes mises en avant</td></tr><tr><td>Savoir qui s'en occupe</td><td>Rien — on demande à voix haute</td><td>La prise en charge verrouille la conversation sur un agent</td></tr><tr><td>Empêcher les réponses en double</td><td>La convention et la chance</td><td>Appliqué en base de données</td></tr><tr><td>Garder l'historique quand l'équipe change</td><td>Lié à l'appareil</td><td>Lié à l'espace de travail</td></tr><tr><td>Répartir par service</td><td>Impossible</td><td>Routage vers des files d'équipe</td></tr><tr><td>Mesurer le temps de réponse</td><td>Aucune donnée</td><td>Médiane de première réponse, résolution, charge par agent</td></tr></tbody></table></div>
<p>La conséquence pratique est qu'un accès partagé sans propriétaire est souvent pire qu'une seule personne dédiée, car la responsabilité se dilue. Chacun suppose que quelqu'un d'autre a répondu.</p>
</section>
<section id="model"><h2>À quoi ressemble un vrai accès multi-agents</h2>
<p>Le support multi-agents exige quatre choses au-delà d'une vue partagée. Chacune répond à une question qu'un opérateur seul n'a jamais à se poser.</p>
<div class="cards"><div class="fc"><div class="ic"><svg width="19" height="19" viewBox="0 0 24 24" fill="none"><path d="M21 11.5a8.4 8.4 0 01-9 8.4 8.9 8.9 0 01-3.9-.9L3 20.5l1.5-4.6A8.4 8.4 0 013.6 11.5a8.4 8.4 0 018.4-8.4 8.4 8.4 0 019 8.4z" stroke="#0f7e7a" stroke-width="2" stroke-linejoin="round"/></svg></div><div class="h">Une file</div><p>Qu'est-ce qui attend, et depuis combien de temps ? Un flux ne peut pas répondre ; une file horodatée le peut.</p></div><div class="fc"><div class="ic"><svg width="19" height="19" viewBox="0 0 24 24" fill="none"><rect x="4.5" y="10.5" width="15" height="10" rx="2.2" stroke="#0f7e7a" stroke-width="2"/><path d="M8 10.5V7a4 4 0 018 0v3.5" stroke="#0f7e7a" stroke-width="2" stroke-linecap="round"/></svg></div><div class="h">La propriété</div><p>Qui traite celle-ci en ce moment, et quelqu'un d'autre peut-il y écrire ? C'est la prise en charge, et elle doit être imposée plutôt que convenue.</p></div><div class="fc"><div class="ic"><svg width="19" height="19" viewBox="0 0 24 24" fill="none"><path d="M12 3v6M12 15v6M3 12h6M15 12h6" stroke="#0f7e7a" stroke-width="2" stroke-linecap="round"/><circle cx="12" cy="12" r="2.6" stroke="#0f7e7a" stroke-width="2"/></svg></div><div class="h">Le routage</div><p>Quelle équipe doit voir cette conversation ? Les questions de facturation n'ont pas leur place dans la file commerciale.</p></div><div class="fc"><div class="ic"><svg width="19" height="19" viewBox="0 0 24 24" fill="none"><path d="M4 20V10M10 20V4M16 20v-7M22 20H2" stroke="#0f7e7a" stroke-width="2" stroke-linecap="round"/></svg></div><div class="h">L'attribution</div><p>Qui a fait quoi, et quand ? À la fois pour la responsabilité et pour savoir où passe réellement le temps.</p></div></div>
<figure><div class="shot"><img src="/img/features/inbox-full.png" alt="La boîte de réception wavadesk avec un pool de conversations partagé, un fil ouvert et le panneau client" loading="lazy" decoding="async" width="3186" height="1766"></div><figcaption><svg width="13" height="13" viewBox="0 0 24 24" fill="none"><rect x="2.5" y="6" width="19" height="14" rx="2.5" stroke="currentColor" stroke-width="2"/><circle cx="12" cy="13" r="3.4" stroke="currentColor" stroke-width="2"/><path d="M8.5 6l1.2-2h4.6L15.5 6" stroke="currentColor" stroke-width="2" stroke-linejoin="round"/></svg><span>La propriété est visible dans la file elle-même : conversations non prises en charge, conversations verrouillées sur un agent nommé, et conversations traitées par l'IA.</span></figcaption></figure>
</section>
<section id="claiming"><h2>La prise en charge : une propriété qu'on ne peut pas rater</h2>
<p>Dans wavadesk, les agents travaillent depuis un pool partagé et prennent une conversation en charge pour s'en occuper. Cette action fait deux choses à la fois : elle signale à l'équipe que la conversation est traitée, et elle la verrouille pour que personne d'autre n'y réponde.</p>
<p>Le verrou est appliqué au niveau de la base de données. Si deux agents cliquent dans la même seconde, l'un gagne et l'autre est informé que la conversation est prise. Il n'existe aucune fenêtre pendant laquelle les deux se croient propriétaires — et c'est précisément dans cette fenêtre que naissent les réponses en double.</p>
<div class="note"><svg width="17" height="17" viewBox="0 0 24 24" fill="none"><circle cx="12" cy="12" r="9" stroke="#0f7e7a" stroke-width="2"/><path d="M12 11v5" stroke="#0f7e7a" stroke-width="2" stroke-linecap="round"/><circle cx="12" cy="7.8" r="1.1" fill="#0f7e7a"/></svg><div class="m"><div class="h">Relâcher et réaffecter</div><p>La prise en charge n'est pas définitive. Un agent peut relâcher une conversation vers le pool et un responsable peut la réaffecter — les deux sont enregistrés, pour que les passages de relais restent visibles.</p></div></div>
</section>
<section id="routing"><h2>Router pour que chacun voie moins, pas plus</h2>
<p>Un pool unique convient à une équipe de trois. À quinze, il devient du bruit : chaque agent fait défiler trente conversations qui ne le concernent pas pour trouver les siennes.</p>
<p>Le routage place les conversations devant la bonne équipe selon les règles que vous définissez, de sorte que la file de chaque agent ne contient que ce sur quoi il peut agir. Le reste existe toujours et reste auditable, il n'est simplement pas dans son chemin.</p>
<ul><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>Router par équipe, pour que les retours, la facturation et les ventes aient chacun leur file</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>Router par mot-clé, quand le message lui-même identifie le service</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>Router par horaires, pour que les conversations hors ouverture arrivent là où quelqu'un veille</span></li><li><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M20 6 9 17l-5-5" stroke="#0f7e7a" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg><span>Escalader vers un responsable quand une conversation dépasse un seuil d'ancienneté</span></li></ul>
<p>En savoir plus dans <a href="/features/teams-routing">Équipes, routage et affectation</a>.</p>
</section>
<section id="seats"><h2>Comment fonctionnent les sièges et la capacité</h2>
<p>Chaque personne qui répond aux clients a besoin de son propre identifiant, pour que la prise en charge et le journal d'audit aient un sens. Les identifiants partagés annulent les deux.</p>
<p>Les offres incluent un nombre de sièges de base, et vous pouvez en ajouter sans changer d'offre quand l'équipe s'agrandit en cours de cycle. La capacité est visible dans l'écran de facturation, plutôt que découverte en se heurtant à un mur.</p>
<figure><div class="shot"><img src="/img/features/usage-meters.png" alt="Jauges d'utilisation montrant les utilisateurs et les messages IA consommés par rapport au quota de l'offre" loading="lazy" decoding="async" width="1760" height="322"></div><figcaption><svg width="13" height="13" viewBox="0 0 24 24" fill="none"><rect x="2.5" y="6" width="19" height="14" rx="2.5" stroke="currentColor" stroke-width="2"/><circle cx="12" cy="13" r="3.4" stroke="currentColor" stroke-width="2"/><path d="M8.5 6l1.2-2h4.6L15.5 6" stroke="currentColor" stroke-width="2" stroke-linejoin="round"/></svg><span>Consommation des sièges et des messages IA par rapport au quota de votre offre, avec la possibilité d'ajouter de la capacité sans changer d'offre.</span></figcaption></figure>
<p>Consultez <a href="{{ url('/#pricing') }}">les tarifs</a> pour voir ce que comprend chaque offre.</p>
</section>
<section id="migrate"><h2>Faire migrer une équipe depuis un téléphone partagé</h2>
<p>La bascule est généralement moins perturbante que les équipes ne le craignent, car rien ne change du côté client.</p>
<div class="steps"><div class="step"><span class="n">1</span><div class="m"><div class="h">Connectez le numéro existant</div><p>Scannez le QR code avec le téléphone qui détient votre compte WhatsApp Business. Les conversations commencent à arriver dans le pool partagé.</p></div></div><div class="step"><span class="n">2</span><div class="m"><div class="h">Ajoutez les personnes qui répondent déjà</div><p>Donnez un siège à chacune. Commencez par le groupe qui se partage aujourd'hui le combiné.</p></div></div><div class="step"><span class="n">3</span><div class="m"><div class="h">Fixez une règle : prendre en charge avant de répondre</div><p>C'est le seul changement de comportement, et l'interface l'impose de toute façon.</p></div></div><div class="step"><span class="n">4</span><div class="m"><div class="h">Cessez de répondre depuis le combiné</div><p>C'est l'étape que les équipes sautent, et c'est celle qui compte. Les réponses envoyées depuis le téléphone contournent la file et le journal d'audit.</p></div></div></div>
<div class="note amber"><svg width="17" height="17" viewBox="0 0 24 24" fill="none"><path d="M12 8v5" stroke="#92400e" stroke-width="2.2" stroke-linecap="round"/><circle cx="12" cy="16.5" r="1.2" fill="#92400e"/><circle cx="12" cy="12" r="9" stroke="#92400e" stroke-width="2"/></svg><div class="m"><div class="h">Ne faites pas coexister les deux longtemps</div><p>Une semaine de recouvrement est acceptable le temps que chacun s'adapte. Au-delà, vous avez deux sources de vérité, c'est-à-dire précisément le problème que vous cherchiez à résoudre.</p></div></div>
</section>
